import { describe, test, expect, beforeEach } from 'vitest'
import { screen, waitFor } from '@testing-library/react'
import { render } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { http, HttpResponse } from 'msw'
import { createRouter, createMemoryHistory, RouterProvider } from '@tanstack/react-router'
import { QueryProvider } from '@/app/providers/QueryProvider'
import { queryClient } from '@/shared/lib/queryClient'
import { server } from '@/test/msw/server'
import { CLIENTES_ENDPOINT, CLIENTE_BY_ID_ENDPOINT, clienteNotFoundProblemDetails } from '@/test/msw/handlers'
import { createCliente } from '@/test/factories/cliente.factory'
// routeTree.gen.ts is regenerated by the TanStack Router Vite plugin now that
// routes/index.tsx, routes/_app.tsx, routes/_app/clientes.tsx,
// routes/_app/contactos.tsx and routes/_app/clientes.$clienteId.tsx
// (Story 2.2, Task 4) exist.
import { routeTree } from '../routeTree.gen'

// Covers AC #3 (deep linking) and AC #4 (root redirect).
//
// NOTE: filename is prefixed with "-" (TanStack Router's colocation-ignore
// convention, see company-standards.md) so the router-plugin does not treat
// this spec file as a route module.
//
// Wrapped in the real QueryProvider (same as main.tsx) since the routed
// Clientes view (Story 2.1) now fetches data via TanStack Query.

function renderAppAt(initialPath: string) {
  const router = createRouter({
    routeTree,
    history: createMemoryHistory({ initialEntries: [initialPath] }),
  })
  return render(
    <QueryProvider>
      <RouterProvider router={router} />
    </QueryProvider>,
  )
}

describe('Navigation shell routing', () => {
  describe('AC4 - Root redirect', () => {
    test('should redirect from "/" to "/clientes" as the default landing section', async () => {
      // GIVEN: the user navigates to the app root
      // WHEN: the page loads
      renderAppAt('/')

      // THEN: the user lands on the Clientes view (no redirect to a separate home screen)
      expect(await screen.findByTestId('clientes-view')).toBeInTheDocument()
    })
  })

  describe('AC3 - Deep linking', () => {
    test('should render the Clientes view when navigating directly to /clientes', async () => {
      // GIVEN: the user types "/clientes" directly in the URL bar
      // WHEN: the page loads
      renderAppAt('/clientes')

      // THEN: the Clientes view renders directly, without redirecting to a landing screen
      expect(await screen.findByTestId('clientes-view')).toBeInTheDocument()
    })

    test('should render the Contactos view when navigating directly to /contactos', async () => {
      // GIVEN: the user types "/contactos" directly in the URL bar
      // WHEN: the page loads
      renderAppAt('/contactos')

      // THEN: the Contactos view renders directly, without redirecting to a landing screen
      expect(await screen.findByTestId('contactos-view')).toBeInTheDocument()
    })
  })

  describe('AC5 - Unknown route handling', () => {
    test('should render the not-found view (not a blank screen or crash) for an unknown route', async () => {
      // GIVEN: the user navigates to an unknown route
      // WHEN: the page loads
      renderAppAt('/foo')

      // THEN: the graceful not-found view renders instead of a crash/blank screen
      expect(await screen.findByRole('heading', { name: /página no encontrada/i })).toBeInTheDocument()
    })

    test('[P2] should render the not-found view for a deeply nested unknown route', async () => {
      // Fixed in code review (Story 1.2): `_app.tsx` now registers its own
      // `notFoundComponent: NotFoundView`, so unmatched paths nested under
      // the `_app` pathless layout (e.g. "/clientes/does-not-exist/...")
      // resolve to the custom Spanish not-found view instead of TanStack's
      // built-in generic "<p>Not Found</p>" fallback.
      // GIVEN: the user navigates to a nested unknown route (not just a single segment)
      // WHEN: the page loads
      renderAppAt('/clientes/does-not-exist/nested/path')

      // THEN: the graceful not-found view still renders (no crash, no blank screen)
      expect(await screen.findByRole('heading', { name: /página no encontrada/i })).toBeInTheDocument()
    })

    test('[P2] should render the not-found view for an unknown route under an unrelated prefix', async () => {
      // GIVEN: the user navigates to an unknown top-level route unrelated to clientes/contactos
      // WHEN: the page loads
      renderAppAt('/configuracion')

      // THEN: the graceful not-found view renders with the recovery link back to /clientes
      await screen.findByRole('heading', { name: /página no encontrada/i })
      expect(screen.getByTestId('not-found-recovery-link')).toHaveAttribute('href', '/clientes')
    })
  })

  describe('AC1/AC2 - Shell renders within routed pages', () => {
    test('[P1] should render the navigation shell (rail or bottom nav) around the Clientes view when routed', async () => {
      // GIVEN: the user navigates to /clientes through the real route tree (not the isolated AppShell test harness)
      // WHEN: the page loads
      renderAppAt('/clientes')

      // THEN: the routed Clientes view is present alongside the shell's location marker
      await screen.findByTestId('clientes-view')
      expect(await screen.findByTestId('app-shell-location')).toHaveTextContent('/clientes')
    })
  })

  describe('Story 2.2 - Client Detail View routing', () => {
    // RED PHASE: routes/_app/clientes.$clienteId.tsx does not exist yet
    // (Story 2.2, Task 4). These tests define the expected deep-linking and
    // click-to-navigate behavior for AC #1, #2, #3, #4.
    //
    // Network-first: every route is registered via `server.use(...)` BEFORE
    // `renderAppAt` mounts (which triggers the initial fetch), per
    // network-first.md.
    //
    // `renderAppAt` uses the app's real singleton `queryClient` (staleTime
    // 60s, same as main.tsx) — clear its cache before each test in this
    // block so per-test MSW overrides (distinct client fixtures) aren't
    // masked by a previous test's cached ['clientes']/['clientes', id] data.
    beforeEach(() => {
      queryClient.clear()
    })

    describe('AC #1 - clicking a client item navigates and updates the URL', () => {
      test('should navigate to /clientes/:clienteId and update the URL when a client item is clicked', async () => {
        // GIVEN: the client list is displayed with one known client
        const cliente = createCliente({ nombre: 'Comercializadora Andina SAS' })
        server.use(
          http.get(CLIENTES_ENDPOINT, () => HttpResponse.json([cliente], { status: 200 })),
          http.get(CLIENTE_BY_ID_ENDPOINT, () => HttpResponse.json(cliente, { status: 200 })),
        )
        const user = userEvent.setup()
        renderAppAt('/clientes')
        const item = await screen.findByText('Comercializadora Andina SAS')

        // WHEN: the user clicks the client item
        await user.click(item);

        // THEN: the URL updates to /clientes/:clienteId (FR30 deep linking)
        await waitFor(() => {
          expect(window.location.pathname).toBe(`/clientes/${cliente.id}`)
        })
      })

      test('should mark the clicked client as selected via the route param (aria-selected)', async () => {
        // GIVEN: the client list is displayed with one known client
        const cliente = createCliente({ nombre: 'Distribuidora del Pacífico' })
        server.use(
          http.get(CLIENTES_ENDPOINT, () => HttpResponse.json([cliente], { status: 200 })),
          http.get(CLIENTE_BY_ID_ENDPOINT, () => HttpResponse.json(cliente, { status: 200 })),
        )
        const user = userEvent.setup()
        renderAppAt('/clientes')
        const item = await screen.findByText('Distribuidora del Pacífico')

        // WHEN: the user clicks the client item
        await user.click(item)

        // THEN: the matching ClientListItem is marked selected (matches route param)
        await waitFor(() => {
          expect(screen.getByTestId('cliente-list-item')).toHaveAttribute('aria-selected', 'true')
        })
      })

      test('should render the complete client details in the right panel after selection', async () => {
        // GIVEN: the client list is displayed
        const cliente = createCliente({
          nombre: 'Suministros del Norte',
          nit: '900555666',
          telefono: '3009998877',
          ciudad: 'Medellín',
        })
        server.use(
          http.get(CLIENTES_ENDPOINT, () => HttpResponse.json([cliente], { status: 200 })),
          http.get(CLIENTE_BY_ID_ENDPOINT, () => HttpResponse.json(cliente, { status: 200 })),
        )
        const user = userEvent.setup()
        renderAppAt('/clientes')
        const item = await screen.findByText('Suministros del Norte')

        // WHEN: the user clicks the client item
        await user.click(item)

        // THEN: the right panel shows Nombre, NIT/RUC, Teléfono, Ciudad
        await screen.findByTestId('cliente-detail-panel')
        expect(screen.getByText('900555666')).toBeInTheDocument()
        expect(screen.getByText('3009998877')).toBeInTheDocument()
        expect(screen.getByText('Medellín')).toBeInTheDocument()
      })
    })

    describe('AC #2 - direct deep link loads the correct client', () => {
      test('should load and display the correct client when navigating directly to /clientes/:clienteId', async () => {
        // GIVEN: a client exists in the backend
        const cliente = createCliente({ nombre: 'Comercial Andina SAS' })
        server.use(
          http.get(CLIENTES_ENDPOINT, () => HttpResponse.json([cliente], { status: 200 })),
          http.get(CLIENTE_BY_ID_ENDPOINT, () => HttpResponse.json(cliente, { status: 200 })),
        )

        // WHEN: the user accesses /clientes/:clienteId directly (no prior in-app navigation)
        renderAppAt(`/clientes/${cliente.id}`)

        // THEN: the correct client's details load and display
        expect(await screen.findByText('Comercial Andina SAS')).toBeInTheDocument()
      })
    })

    describe('AC #3 - non-existent clienteId shows a graceful not-found state', () => {
      test('should render a graceful not-found message for a well-formed but non-existent clienteId', async () => {
        // GIVEN: the backend has no client matching the given UUID
        const nonExistentId = '00000000-0000-0000-0000-000000000000'
        server.use(
          http.get(CLIENTES_ENDPOINT, () => HttpResponse.json([], { status: 200 })),
          http.get(CLIENTE_BY_ID_ENDPOINT, () =>
            HttpResponse.json(clienteNotFoundProblemDetails, { status: 404 }),
          ),
        )

        // WHEN: the page loads at that URL
        renderAppAt(`/clientes/${nonExistentId}`)

        // THEN: a graceful not-found block renders — no blank page, no crash
        expect(await screen.findByTestId('cliente-not-found')).toBeInTheDocument()
      })
    })

    describe('AC #4 - empty/default state when no client is selected', () => {
      test('should show the "no client selected" state on the base /clientes route', async () => {
        // GIVEN: the client list is displayed
        server.use(
          http.get(CLIENTES_ENDPOINT, () => HttpResponse.json([createCliente()], { status: 200 })),
        )

        // WHEN: the user navigates to /clientes without selecting any client
        renderAppAt('/clientes')

        // THEN: the right panel shows the empty/default "no selection" state
        expect(await screen.findByTestId('cliente-detail-empty')).toBeInTheDocument()
      })
    })
  })
})
