import { describe, test, expect } from 'vitest'
import { screen } from '@testing-library/react'
import { render } from '@testing-library/react'
import { createRouter, createMemoryHistory, RouterProvider } from '@tanstack/react-router'
// routeTree.gen.ts is regenerated by the TanStack Router Vite plugin now that
// routes/index.tsx, routes/_app.tsx, routes/_app/clientes.tsx and
// routes/_app/contactos.tsx exist (Task 2, GREEN phase).
import { routeTree } from '../routeTree.gen'

// Covers AC #3 (deep linking) and AC #4 (root redirect).
//
// NOTE: filename is prefixed with "-" (TanStack Router's colocation-ignore
// convention, see company-standards.md) so the router-plugin does not treat
// this spec file as a route module.

function renderAppAt(initialPath: string) {
  const router = createRouter({
    routeTree,
    history: createMemoryHistory({ initialEntries: [initialPath] }),
  })
  return render(<RouterProvider router={router} />)
}

describe('Navigation shell routing', () => {
  describe('AC4 - Root redirect', () => {
    test('should redirect from "/" to "/clientes" as the default landing section', async () => {
      // GIVEN: the user navigates to the app root
      // WHEN: the page loads
      renderAppAt('/')

      // THEN: the user lands on the Clientes view (no redirect to a separate home screen)
      expect(await screen.findByTestId('clientes-view')).toBeInTheDocument()
    })
  })

  describe('AC3 - Deep linking', () => {
    test('should render the Clientes view when navigating directly to /clientes', async () => {
      // GIVEN: the user types "/clientes" directly in the URL bar
      // WHEN: the page loads
      renderAppAt('/clientes')

      // THEN: the Clientes view renders directly, without redirecting to a landing screen
      expect(await screen.findByTestId('clientes-view')).toBeInTheDocument()
    })

    test('should render the Contactos view when navigating directly to /contactos', async () => {
      // GIVEN: the user types "/contactos" directly in the URL bar
      // WHEN: the page loads
      renderAppAt('/contactos')

      // THEN: the Contactos view renders directly, without redirecting to a landing screen
      expect(await screen.findByTestId('contactos-view')).toBeInTheDocument()
    })
  })

  describe('AC5 - Unknown route handling', () => {
    test('should render the not-found view (not a blank screen or crash) for an unknown route', async () => {
      // GIVEN: the user navigates to an unknown route
      // WHEN: the page loads
      renderAppAt('/foo')

      // THEN: the graceful not-found view renders instead of a crash/blank screen
      expect(await screen.findByRole('heading', { name: /página no encontrada/i })).toBeInTheDocument()
    })
  })
})
