import { describe, test, expect } from 'vitest'
import { screen } from '@testing-library/react'
import { render } from '@testing-library/react'
import { createRouter, createMemoryHistory, RouterProvider } from '@tanstack/react-router'
// routeTree.gen.ts is regenerated by the TanStack Router Vite plugin now that
// routes/index.tsx, routes/_app.tsx, routes/_app/clientes.tsx and
// routes/_app/contactos.tsx exist (Task 2, GREEN phase).
import { routeTree } from '../routeTree.gen'

// Covers AC #3 (deep linking) and AC #4 (root redirect).
//
// NOTE: filename is prefixed with "-" (TanStack Router's colocation-ignore
// convention, see company-standards.md) so the router-plugin does not treat
// this spec file as a route module.

function renderAppAt(initialPath: string) {
  const router = createRouter({
    routeTree,
    history: createMemoryHistory({ initialEntries: [initialPath] }),
  })
  return render(<RouterProvider router={router} />)
}

describe('Navigation shell routing', () => {
  describe('AC4 - Root redirect', () => {
    test('should redirect from "/" to "/clientes" as the default landing section', async () => {
      // GIVEN: the user navigates to the app root
      // WHEN: the page loads
      renderAppAt('/')

      // THEN: the user lands on the Clientes view (no redirect to a separate home screen)
      expect(await screen.findByTestId('clientes-view')).toBeInTheDocument()
    })
  })

  describe('AC3 - Deep linking', () => {
    test('should render the Clientes view when navigating directly to /clientes', async () => {
      // GIVEN: the user types "/clientes" directly in the URL bar
      // WHEN: the page loads
      renderAppAt('/clientes')

      // THEN: the Clientes view renders directly, without redirecting to a landing screen
      expect(await screen.findByTestId('clientes-view')).toBeInTheDocument()
    })

    test('should render the Contactos view when navigating directly to /contactos', async () => {
      // GIVEN: the user types "/contactos" directly in the URL bar
      // WHEN: the page loads
      renderAppAt('/contactos')

      // THEN: the Contactos view renders directly, without redirecting to a landing screen
      expect(await screen.findByTestId('contactos-view')).toBeInTheDocument()
    })
  })

  describe('AC5 - Unknown route handling', () => {
    test('should render the not-found view (not a blank screen or crash) for an unknown route', async () => {
      // GIVEN: the user navigates to an unknown route
      // WHEN: the page loads
      renderAppAt('/foo')

      // THEN: the graceful not-found view renders instead of a crash/blank screen
      expect(await screen.findByRole('heading', { name: /página no encontrada/i })).toBeInTheDocument()
    })

    test('[P2] should render the not-found view for a deeply nested unknown route', async () => {
      // Fixed in code review (Story 1.2): `_app.tsx` now registers its own
      // `notFoundComponent: NotFoundView`, so unmatched paths nested under
      // the `_app` pathless layout (e.g. "/clientes/does-not-exist/...")
      // resolve to the custom Spanish not-found view instead of TanStack's
      // built-in generic "<p>Not Found</p>" fallback.
      // GIVEN: the user navigates to a nested unknown route (not just a single segment)
      // WHEN: the page loads
      renderAppAt('/clientes/does-not-exist/nested/path')

      // THEN: the graceful not-found view still renders (no crash, no blank screen)
      expect(await screen.findByRole('heading', { name: /página no encontrada/i })).toBeInTheDocument()
    })

    test('[P2] should render the not-found view for an unknown route under an unrelated prefix', async () => {
      // GIVEN: the user navigates to an unknown top-level route unrelated to clientes/contactos
      // WHEN: the page loads
      renderAppAt('/configuracion')

      // THEN: the graceful not-found view renders with the recovery link back to /clientes
      await screen.findByRole('heading', { name: /página no encontrada/i })
      expect(screen.getByTestId('not-found-recovery-link')).toHaveAttribute('href', '/clientes')
    })
  })

  describe('AC1/AC2 - Shell renders within routed pages', () => {
    test('[P1] should render the navigation shell (rail or bottom nav) around the Clientes view when routed', async () => {
      // GIVEN: the user navigates to /clientes through the real route tree (not the isolated AppShell test harness)
      // WHEN: the page loads
      renderAppAt('/clientes')

      // THEN: the routed Clientes view is present alongside the shell's location marker
      await screen.findByTestId('clientes-view')
      expect(await screen.findByTestId('app-shell-location')).toHaveTextContent('/clientes')
    })
  })
})
