/**
 * Story 1.2: Frontend Navigation Shell
 * Epic 1: Project Foundation & Application Shell
 *
 * Automation Expansion — Edge Cases & Boundary Conditions (Component level)
 * Generated by *automate after the ATDD suite (routing.test.tsx) went GREEN.
 * Focus: scenarios NOT covered by the original ATDD suite — deep links carrying
 * query params, nested/partially-matching unknown paths, and a regression guard
 * that the "/" -> "/clientes" redirect does not over-fire on other routes.
 *
 * Acceptance Criteria covered:
 *   AC3 — Deep-linking renders the correct view (edge: query string present)
 *   AC4 — Only "/" redirects to "/clientes" (regression guard)
 *   AC5 — Unknown route renders NotFoundView (edge: nested/partial-match path)
 */

import { describe, test, expect } from 'vitest'
import { render, screen, waitFor } from '@testing-library/react'
import { createRouter, createMemoryHistory, RouterProvider } from '@tanstack/react-router'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { routeTree } from '../routeTree.gen'

// Story 2.1 wires `/clientes` to `ClienteListView`, which reads `useClientes()`
// (TanStack Query) — a QueryClientProvider is now required for the route tree to
// render without crashing, same as the real app shell (see main.tsx).
function renderAppAt(initialPath: string) {
  const router = createRouter({
    routeTree,
    history: createMemoryHistory({ initialEntries: [initialPath] }),
  })
  const queryClient = new QueryClient({ defaultOptions: { queries: { retry: false } } })
  render(
    <QueryClientProvider client={queryClient}>
      <RouterProvider router={router} />
    </QueryClientProvider>,
  )
  return router
}

describe('AC3 — Deep link with query string still renders the correct view', () => {
  test('[P2] navigating to "/clientes?ref=email" renders the Clientes view with no redirect', async () => {
    // GIVEN/WHEN: the user opens a deep link carrying a query string
    const router = renderAppAt('/clientes?ref=email')

    // THEN: the Clientes view renders directly, query string does not break route matching
    expect(await screen.findByRole('heading', { name: /clientes/i })).toBeInTheDocument()
    expect(router.state.location.pathname).toBe('/clientes')
  })
})

describe('AC5 — Nested unknown path sharing a route prefix still renders NotFoundView', () => {
  // Code-review fix (Story 1.2): this was a documented `test.skip()` — automation
  // found that a path sharing a prefix with a real route (e.g. "/clientes/no-existe")
  // resolves TanStack Router's not-found state at the nearest matched ancestor route
  // (the `/_app` pathless layout), not the root. Since `_app.tsx` didn't register its
  // own `notFoundComponent`, it fell back to TanStack's plain-text default instead of
  // the styled Spanish `NotFoundView`, violating AC5 for nested unknown routes.
  // Fixed by registering `notFoundComponent: NotFoundView` on the `/_app` route
  // (frontend/src/routes/_app.tsx), mirroring the root route's registration for the
  // fully-unmatched-path case. Un-skipped now that the product behavior is correct.
  //
  // Story 2.2 update: `/clientes/$clienteId` is now a real, deep-linkable route (FR30),
  // so a single-segment path like "/clientes/no-existe" legitimately matches it (rendering
  // the `cliente-not-found` EmptyState inside the detail panel per AC #3 — that is the
  // correct product behavior now, not a bug). This test is updated to use a two-segment
  // path instead, which still shares the "/clientes" prefix but matches no leaf route
  // (`$clienteId` only captures a single path segment), preserving the original edge case's
  // intent of "nested unknown path sharing a route prefix".
  test('[P2] navigating to "/clientes/no-existe/extra" (nested, non-matching path) shows the not-found message', async () => {
    // GIVEN/WHEN: the user navigates to a nested path that shares a prefix with a real route
    // but does not itself match any leaf route
    renderAppAt('/clientes/no-existe/extra')

    // THEN: a graceful not-found view is displayed, matching the fully-unmatched-path case
    expect(await screen.findByText(/página no encontrada/i)).toBeInTheDocument()
  })

  test('[P2] the navigation shell remains mounted for a nested unknown path', async () => {
    // GIVEN/WHEN: the user navigates to a nested unknown path
    renderAppAt('/clientes/no-existe/extra')
    await screen.findByText(/página no encontrada/i)

    // THEN: the desktop navigation container is still present (shell layout persists)
    expect(screen.getByTestId('nav-rail-container')).toBeInTheDocument()
  })
})

describe('AC4 — Regression guard: redirect is scoped to "/" only', () => {
  test('[P1] navigating directly to "/contactos" does not redirect to "/clientes"', async () => {
    // GIVEN/WHEN: the user opens a deep link to /contactos
    const router = renderAppAt('/contactos')

    // THEN: the Contactos view renders and the route is NOT redirected to /clientes
    expect(await screen.findByRole('heading', { name: /contactos/i })).toBeInTheDocument()
    await waitFor(() => expect(router.state.location.pathname).toBe('/contactos'))
  })
})
