/**
 * Story 1.2: Frontend Navigation Shell
 * Epic 1: Project Foundation & Application Shell
 *
 * Automation Expansion — Edge Cases & Boundary Conditions (Component level)
 * Generated by *automate after the ATDD suite (routing.test.tsx) went GREEN.
 * Focus: scenarios NOT covered by the original ATDD suite — deep links carrying
 * query params, nested/partially-matching unknown paths, and a regression guard
 * that the "/" -> "/clientes" redirect does not over-fire on other routes.
 *
 * Acceptance Criteria covered:
 *   AC3 — Deep-linking renders the correct view (edge: query string present)
 *   AC4 — Only "/" redirects to "/clientes" (regression guard)
 *   AC5 — Unknown route renders NotFoundView (edge: nested/partial-match path)
 */

import { describe, test, expect } from 'vitest'
import { render, screen, waitFor } from '@testing-library/react'
import { createRouter, createMemoryHistory, RouterProvider } from '@tanstack/react-router'
import { routeTree } from '../routeTree.gen'

function renderAppAt(initialPath: string) {
  const router = createRouter({
    routeTree,
    history: createMemoryHistory({ initialEntries: [initialPath] }),
  })
  render(<RouterProvider router={router} />)
  return router
}

describe('AC3 — Deep link with query string still renders the correct view', () => {
  test('[P2] navigating to "/clientes?ref=email" renders the Clientes view with no redirect', async () => {
    // GIVEN/WHEN: the user opens a deep link carrying a query string
    const router = renderAppAt('/clientes?ref=email')

    // THEN: the Clientes view renders directly, query string does not break route matching
    expect(await screen.findByRole('heading', { name: /clientes/i })).toBeInTheDocument()
    expect(router.state.location.pathname).toBe('/clientes')
  })
})

describe('AC5 — Nested unknown path sharing a route prefix still renders NotFoundView', () => {
  // Code-review fix (Story 1.2): this was a documented `test.skip()` — automation
  // found that a path sharing a prefix with a real route (e.g. "/clientes/no-existe")
  // resolves TanStack Router's not-found state at the nearest matched ancestor route
  // (the `/_app` pathless layout), not the root. Since `_app.tsx` didn't register its
  // own `notFoundComponent`, it fell back to TanStack's plain-text default instead of
  // the styled Spanish `NotFoundView`, violating AC5 for nested unknown routes.
  // Fixed by registering `notFoundComponent: NotFoundView` on the `/_app` route
  // (frontend/src/routes/_app.tsx), mirroring the root route's registration for the
  // fully-unmatched-path case. Un-skipped now that the product behavior is correct.
  test('[P2] navigating to "/clientes/no-existe" (partial prefix match) shows the not-found message', async () => {
    // GIVEN/WHEN: the user navigates to a path that shares a prefix with a real route
    // but does not itself match any leaf route
    renderAppAt('/clientes/no-existe')

    // THEN: a graceful not-found view is displayed, matching the fully-unmatched-path case
    expect(await screen.findByText(/página no encontrada/i)).toBeInTheDocument()
  })

  test('[P2] the navigation shell remains mounted for a nested unknown path', async () => {
    // GIVEN/WHEN: the user navigates to a nested unknown path
    renderAppAt('/clientes/no-existe')
    await screen.findByText(/página no encontrada/i)

    // THEN: the desktop navigation container is still present (shell layout persists)
    expect(screen.getByTestId('nav-rail-container')).toBeInTheDocument()
  })
})

describe('AC4 — Regression guard: redirect is scoped to "/" only', () => {
  test('[P1] navigating directly to "/contactos" does not redirect to "/clientes"', async () => {
    // GIVEN/WHEN: the user opens a deep link to /contactos
    const router = renderAppAt('/contactos')

    // THEN: the Contactos view renders and the route is NOT redirected to /clientes
    expect(await screen.findByRole('heading', { name: /contactos/i })).toBeInTheDocument()
    await waitFor(() => expect(router.state.location.pathname).toBe('/contactos'))
  })
})
