/**
 * Story 1.2: Frontend Navigation Shell
 * Epic 1: Project Foundation & Application Shell
 *
 * ATDD Acceptance Tests — RED Phase
 * These tests are intentionally FAILING until the route tree (`_app.tsx`,
 * `_app/clientes.tsx`, `_app/contactos.tsx`, root `notFoundComponent`, and the
 * `/` redirect) is implemented AND `routeTree.gen.ts` has been regenerated by
 * running `pnpm --filter frontend dev` (or `vite build`) at least once — the
 * TanStack Router Vite plugin (not Vitest) is what regenerates that file.
 *
 * Acceptance Criteria covered:
 *   AC4 — Navigating to "/" redirects to "/clientes"
 *   AC5 — Navigating to an unknown route shows a NotFoundView, nav stays visible, no crash
 */

import { describe, test, expect } from 'vitest'
import { render, screen, waitFor } from '@testing-library/react'
import { createRouter, createMemoryHistory, RouterProvider } from '@tanstack/react-router'
import { routeTree } from '../routeTree.gen'

function renderAppAt(initialPath: string) {
  const router = createRouter({
    routeTree,
    history: createMemoryHistory({ initialEntries: [initialPath] }),
  })
  render(<RouterProvider router={router} />)
  return router
}

describe('AC4 — Root route redirects to /clientes', () => {
  test('navigating to "/" redirects to "/clientes" and renders the Clientes view', async () => {
    // GIVEN: the user opens the app at the root path
    const router = renderAppAt('/')

    // WHEN: the root route's beforeLoad redirect resolves
    await waitFor(() => expect(router.state.location.pathname).toBe('/clientes'))

    // THEN: the Clientes view content is rendered (not a blank page at "/")
    expect(await screen.findByRole('heading', { name: /clientes/i })).toBeInTheDocument()
  })
})

describe('AC5 — Unknown route renders NotFoundView inside the app shell', () => {
  test('navigating to an unmatched path shows the "Página no encontrada" message', async () => {
    // GIVEN/WHEN: the user navigates to a route that does not exist
    renderAppAt('/ruta-que-no-existe')

    // THEN: a graceful not-found view is displayed (Spanish copy), no blank page, no crash
    expect(await screen.findByText(/página no encontrada/i)).toBeInTheDocument()
  })

  test('the navigation shell remains mounted while showing the not-found view', async () => {
    // GIVEN/WHEN: the user navigates to a route that does not exist
    renderAppAt('/ruta-que-no-existe')
    await screen.findByText(/página no encontrada/i)

    // THEN: the desktop navigation container is still present (shell layout persists)
    expect(screen.getByTestId('nav-rail-container')).toBeInTheDocument()
  })
})
