/**
 * Story 1.2 — Frontend Navigation Shell
 * Epic 1: Project Foundation & Application Shell
 *
 * AppShell expanded component tests — edge cases, error paths, and behavioral
 * contracts NOT covered by AppShell.test.tsx (happy-path ATDD).
 *
 * Generated by testarch-automate (BMad-Integrated Mode).
 *
 * Scope:
 *   - Rapid SPA navigation (Clientes ↔ Contactos several times) — shell wrapper
 *     identity stays stable (no remount of the chrome).
 *   - Browser-style back navigation via memory history — active state follows.
 *   - Mobile + desktop nav surfaces both render the SAME id set (no drift).
 *   - aria-hidden toggles between rail (desktop) and mobile bar based on
 *     window.matchMedia — proves the dedup of the a11y tree (one accessible
 *     entry per id per viewport).
 *   - matchMedia missing → component does not throw (defensive SSR-ish guard).
 *   - Clicking the SAME active entry is a no-op for the URL (idempotent).
 *   - Route children render exactly ONCE (single tree identity) — guards the
 *     critical Dev Note that LayoutBase was rejected because it mounted children
 *     twice.
 *
 * Selector strategy: data-testid > role > text. No CSS selectors. No hard waits.
 */

import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest'
import {
  act,
  cleanup,
  fireEvent,
  render,
  screen,
  waitFor,
} from '@testing-library/react'
import {
  RouterProvider,
  createMemoryHistory,
  createRootRoute,
  createRoute,
  createRouter,
  Outlet,
} from '@tanstack/react-router'

import { AppShell } from './AppShell'

function buildTestRouter(initialPath: string) {
  const rootRoute = createRootRoute({
    component: () => (
      <AppShell>
        <Outlet />
      </AppShell>
    ),
  })

  const clientesRoute = createRoute({
    getParentRoute: () => rootRoute,
    path: '/clientes',
    component: () => <div data-testid="clientes-view">Clientes Body</div>,
  })

  const contactosRoute = createRoute({
    getParentRoute: () => rootRoute,
    path: '/contactos',
    component: () => <div data-testid="contactos-view">Contactos Body</div>,
  })

  return createRouter({
    routeTree: rootRoute.addChildren([clientesRoute, contactosRoute]),
    history: createMemoryHistory({ initialEntries: [initialPath] }),
  })
}

function setDesktopViewport() {
  Object.defineProperty(window, 'innerWidth', { writable: true, configurable: true, value: 1280 })
  Object.defineProperty(window, 'matchMedia', {
    writable: true,
    configurable: true,
    value: (query: string) => ({
      matches: query.includes('min-width: 1024px'),
      media: query,
      onchange: null,
      addEventListener: () => undefined,
      removeEventListener: () => undefined,
      addListener: () => undefined,
      removeListener: () => undefined,
      dispatchEvent: () => false,
    }),
  })
}

function setMobileViewport() {
  Object.defineProperty(window, 'innerWidth', { writable: true, configurable: true, value: 375 })
  Object.defineProperty(window, 'matchMedia', {
    writable: true,
    configurable: true,
    value: (query: string) => ({
      matches: false,
      media: query,
      onchange: null,
      addEventListener: () => undefined,
      removeEventListener: () => undefined,
      addListener: () => undefined,
      removeListener: () => undefined,
      dispatchEvent: () => false,
    }),
  })
}

describe('AppShell — SPA navigation stability (Story 1.2, AC #1)', () => {
  beforeEach(() => {
    setDesktopViewport()
  })

  afterEach(() => {
    cleanup()
    vi.restoreAllMocks()
  })

  it('[P1] shell wrapper identity is preserved across multiple round-trip navigations', async () => {
    // GIVEN: the user starts at /clientes on desktop
    const router = buildTestRouter('/clientes')
    render(<RouterProvider router={router} />)

    const shellBefore = await screen.findByTestId('app-root')

    // WHEN: the user clicks back and forth Clientes → Contactos → Clientes → Contactos
    const goContactos = screen.getByRole('button', { name: /ir a contactos/i })
    const goClientes = screen.getByRole('button', { name: /ir a clientes/i })

    await act(async () => {
      fireEvent.click(goContactos)
    })
    await waitFor(() => expect(router.state.location.pathname).toBe('/contactos'))

    await act(async () => {
      fireEvent.click(goClientes)
    })
    await waitFor(() => expect(router.state.location.pathname).toBe('/clientes'))

    await act(async () => {
      fireEvent.click(goContactos)
    })
    await waitFor(() => expect(router.state.location.pathname).toBe('/contactos'))

    // THEN: the same DOM node is still the app shell root (no remount of the chrome)
    expect(screen.getByTestId('app-root')).toBe(shellBefore)
  })

  it('[P1] router back navigation restores the prior active state', async () => {
    // GIVEN: the user navigates from /clientes to /contactos
    const router = buildTestRouter('/clientes')
    render(<RouterProvider router={router} />)

    const goContactos = await screen.findByRole('button', { name: /ir a contactos/i })
    await act(async () => {
      fireEvent.click(goContactos)
    })
    await waitFor(() => expect(router.state.location.pathname).toBe('/contactos'))

    // WHEN: the router goes back (browser-style)
    await act(async () => {
      router.history.back()
    })

    // THEN: pathname returns to /clientes and the Clientes entry is the active one
    await waitFor(() => expect(router.state.location.pathname).toBe('/clientes'))
    const clientesNav = screen.getByRole('button', { name: /ir a clientes/i })
    await waitFor(() => {
      const ariaCurrent = clientesNav.getAttribute('aria-current')
      const dataActive = clientesNav.getAttribute('data-active')
      expect(ariaCurrent === 'page' || dataActive === 'true').toBe(true)
    })
  })

  it('[P1] clicking the already-active nav entry is a no-op for the pathname (idempotent)', async () => {
    // GIVEN: the user is on /clientes
    const router = buildTestRouter('/clientes')
    render(<RouterProvider router={router} />)
    await waitFor(() => expect(router.state.location.pathname).toBe('/clientes'))

    // WHEN: the user clicks "Ir a Clientes" again (already active)
    const goClientes = screen.getByRole('button', { name: /ir a clientes/i })
    await act(async () => {
      fireEvent.click(goClientes)
    })

    // THEN: pathname stays /clientes (no spurious change)
    expect(router.state.location.pathname).toBe('/clientes')
  })

  it('[P1] route children render exactly ONCE — children are not double-mounted across viewports', async () => {
    // GIVEN/WHEN: the shell mounts on desktop
    const router = buildTestRouter('/clientes')
    render(<RouterProvider router={router} />)
    await waitFor(() => expect(router.state.location.pathname).toBe('/clientes'))

    // THEN: the clientes-view body appears exactly once (the AppShell Dev Note explicitly
    // documents that LayoutBase was rejected because it would double-mount children)
    const viewMatches = screen.getAllByTestId('clientes-view')
    expect(viewMatches).toHaveLength(1)
  })

  it('[P1] both viewports keep the SAME nav ids in the DOM — no drift between rail and mobile bar', async () => {
    // GIVEN: the shell mounts on desktop
    const router = buildTestRouter('/clientes')
    render(<RouterProvider router={router} />)

    // Wait until the rail has rendered at least one accessible button.
    await screen.findByRole('button', { name: /ir a clientes/i })

    // The off-viewport container carries aria-hidden, so its buttons are EXCLUDED from
    // the accessible role tree (this dedup is intentional — one a11y entry per item).
    // For the "no drift" check we query the raw DOM (including aria-hidden containers)
    // by aria-label, which is consistent across both surfaces by contract (AC #8).
    const clientesByAria = document.querySelectorAll('[aria-label="Ir a Clientes"]')
    const contactosByAria = document.querySelectorAll('[aria-label="Ir a Contactos"]')

    // THEN: each id is present in BOTH the rail and the mobile bar (≥ 2 occurrences each)
    expect(clientesByAria.length).toBeGreaterThanOrEqual(2)
    expect(contactosByAria.length).toBeGreaterThanOrEqual(2)
  })
})

describe('AppShell — responsive a11y (Story 1.2, AC #1, #2, #8)', () => {
  afterEach(() => {
    cleanup()
    vi.restoreAllMocks()
  })

  it('[P1] desktop: the desktop rail container is aria-visible AND the mobile nav is aria-hidden', async () => {
    // GIVEN: matchMedia reports desktop (≥ 1024px)
    setDesktopViewport()
    const router = buildTestRouter('/clientes')
    render(<RouterProvider router={router} />)

    // WHEN: the shell renders
    const rail = await screen.findByTestId('shell-rail-container')
    const mobileNav = await screen.findByTestId('shell-mobile-nav')

    // THEN: only the desktop rail is in the active a11y tree (mobile nav is aria-hidden)
    // Implementation uses aria-hidden={isDesktop || undefined} on the mobile container
    expect(rail.getAttribute('aria-hidden')).not.toBe('true')
    expect(mobileNav.getAttribute('aria-hidden')).toBe('true')
  })

  it('[P1] mobile: the mobile nav container is aria-visible AND the rail is aria-hidden', async () => {
    // GIVEN: matchMedia reports mobile (< 1024px)
    setMobileViewport()
    const router = buildTestRouter('/clientes')
    render(<RouterProvider router={router} />)

    // WHEN: the shell renders
    const rail = await screen.findByTestId('shell-rail-container')
    const mobileNav = await screen.findByTestId('shell-mobile-nav')

    // THEN: only the mobile surface is in the active a11y tree
    expect(mobileNav.getAttribute('aria-hidden')).not.toBe('true')
    expect(rail.getAttribute('aria-hidden')).toBe('true')
  })

  it('[P2] the shell renders without throwing when window.matchMedia is undefined (SSR-ish guard)', async () => {
    // GIVEN: matchMedia is intentionally removed (some jsdom versions / SSR contexts)
    const originalMatchMedia = window.matchMedia
    Object.defineProperty(window, 'matchMedia', {
      writable: true,
      configurable: true,
      value: undefined,
    })

    // WHEN: the shell mounts
    const router = buildTestRouter('/clientes')
    expect(() => render(<RouterProvider router={router} />)).not.toThrow()

    // THEN: the shell root is still present
    const root = await screen.findByTestId('app-root')
    expect(root).toBeInTheDocument()

    // Restore for follow-up tests
    Object.defineProperty(window, 'matchMedia', {
      writable: true,
      configurable: true,
      value: originalMatchMedia,
    })
  })

  it('[P2] mobile NavigationBar exposes Spanish ariaLabel "Navegación principal" on its container', async () => {
    // GIVEN: matchMedia reports mobile
    setMobileViewport()
    const router = buildTestRouter('/clientes')
    render(<RouterProvider router={router} />)

    // WHEN: the shell renders
    // THEN: an element with the Spanish aria-label "Navegación principal" is present
    // (siesa-ui-kit NavigationBar applies ariaLabel to its nav element)
    await waitFor(() => {
      const navByLabel =
        screen.queryByRole('navigation', { name: /navegación principal/i }) ||
        document.querySelector('[aria-label="Navegación principal"]')
      expect(navByLabel).toBeTruthy()
    })
  })
})
