/**
 * Story 1.2 — Frontend Navigation Shell
 * Epic 1: Project Foundation & Application Shell
 *
 * Unit / Integration tests for the useShellNavigation hook.
 *
 * Generated by testarch-automate (BMad-Integrated Mode) — expands ATDD coverage
 * with branch-level edge cases the component-level ATDD tests do not exercise:
 *
 *   - activeId derivation for the three branches (clientes / contactos / null)
 *   - "startsWith" prefix matching for nested routes (forward-compatible with
 *     Epic 2 `/clientes/:id` and Epic 3 `/contactos/:id`)
 *   - onNavigate invokes TanStack Router navigate() (no window.location)
 *   - exact path "/" returns null active state (no false-active rail entry on
 *     the redirect tick)
 *   - paths that are NOT prefixes of /clientes or /contactos return null
 *     (e.g. /clienteX, /contactosa-no-existe-extra-segment is OK because
 *     startsWith is the contract — but /clienteX must NOT light up Clientes)
 *
 * Selector strategy: hook return-value assertions only; no DOM.
 * Test rules: deterministic, isolated, one assertion per test where practical.
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest'
import { renderHook, act, cleanup } from '@testing-library/react'
import type { ReactNode } from 'react'
import {
  RouterProvider,
  createMemoryHistory,
  createRootRoute,
  createRoute,
  createRouter,
  Outlet,
} from '@tanstack/react-router'

import { useShellNavigation } from './useShellNavigation'

/**
 * Build a minimal RouterProvider wrapper around the hook so `useRouterState`
 * and `useNavigate` resolve. We mount the hook inside a dummy child route so
 * the hook executes within a real TanStack Router context.
 */
function buildHookWrapper(initialPath: string) {
  let hookResult: ReturnType<typeof useShellNavigation> | undefined
  function HookProbe() {
    hookResult = useShellNavigation()
    return null
  }

  const rootRoute = createRootRoute({
    component: () => (
      <>
        <HookProbe />
        <Outlet />
      </>
    ),
  })

  const catchAllRoute = createRoute({
    getParentRoute: () => rootRoute,
    path: '/$',
    component: () => null,
  })

  const indexRoute = createRoute({
    getParentRoute: () => rootRoute,
    path: '/',
    component: () => null,
  })

  const router = createRouter({
    routeTree: rootRoute.addChildren([indexRoute, catchAllRoute]),
    history: createMemoryHistory({ initialEntries: [initialPath] }),
  })

  const wrapper = ({ children }: { children: ReactNode }) => (
    <>
      <RouterProvider router={router} />
      {children}
    </>
  )

  return {
    router,
    wrapper,
    getResult: () => {
      if (!hookResult) {
        throw new Error('Hook probe did not capture a result yet')
      }
      return hookResult
    },
  }
}

describe('useShellNavigation — activeId derivation (Story 1.2, AC #7)', () => {
  afterEach(() => {
    cleanup()
  })

  it('[P1] returns activeId = "clientes" on /clientes (exact match)', async () => {
    // GIVEN: the router is at /clientes
    const { wrapper, getResult } = buildHookWrapper('/clientes')

    // WHEN: the hook renders
    renderHook(() => null, { wrapper })

    // THEN: activeId reflects the current pathname
    await act(async () => {})
    expect(getResult().activeId).toBe('clientes')
  })

  it('[P1] returns activeId = "contactos" on /contactos (exact match)', async () => {
    // GIVEN: the router is at /contactos
    const { wrapper, getResult } = buildHookWrapper('/contactos')

    renderHook(() => null, { wrapper })
    await act(async () => {})

    // THEN: activeId reflects the current pathname
    expect(getResult().activeId).toBe('contactos')
  })

  it('[P1] returns activeId = null on / (no false-active on redirect tick)', async () => {
    // GIVEN: the router is at /
    const { wrapper, getResult } = buildHookWrapper('/')

    renderHook(() => null, { wrapper })
    await act(async () => {})

    // THEN: no nav entry is active (the index redirect target should NOT be
    // visually "active" until the route actually resolves to /clientes)
    expect(getResult().activeId).toBeNull()
  })

  it('[P1] returns activeId = null on an unknown route', async () => {
    // GIVEN: the router is at /ruta-que-no-existe
    const { wrapper, getResult } = buildHookWrapper('/ruta-que-no-existe')

    renderHook(() => null, { wrapper })
    await act(async () => {})

    // THEN: activeId is null (nothing in the rail should appear active on 404)
    expect(getResult().activeId).toBeNull()
  })

  it('[P2] lights up Clientes on /clientes/123 (forward-compatible with Epic 2 detail route)', async () => {
    // GIVEN: the router is at a nested clientes detail path
    const { wrapper, getResult } = buildHookWrapper('/clientes/123')

    renderHook(() => null, { wrapper })
    await act(async () => {})

    // THEN: the hook still considers Clientes active (startsWith contract)
    expect(getResult().activeId).toBe('clientes')
  })

  it('[P2] lights up Contactos on /contactos/abc (forward-compatible with Epic 3 detail route)', async () => {
    // GIVEN: the router is at a nested contactos detail path
    const { wrapper, getResult } = buildHookWrapper('/contactos/abc')

    renderHook(() => null, { wrapper })
    await act(async () => {})

    // THEN: the hook still considers Contactos active (startsWith contract)
    expect(getResult().activeId).toBe('contactos')
  })

  it('[P2] returns "clientes" on /clientes?query=foo (querystring does not break match)', async () => {
    // GIVEN: pathname is /clientes with a querystring; pathname does NOT include search,
    // so startsWith('/clientes') still holds
    const { wrapper, getResult } = buildHookWrapper('/clientes?filter=active')

    renderHook(() => null, { wrapper })
    await act(async () => {})

    // THEN: the hook treats /clientes?... as Clientes-active
    expect(getResult().activeId).toBe('clientes')
  })

  it('[P2] does NOT match a sibling path that merely shares a prefix substring', async () => {
    // GIVEN: a hypothetical sibling path that is NOT under /clientes (e.g. /clientess-not-a-real-path)
    // Note: startsWith('/clientes') WILL match '/clientess' because of substring semantics — this
    // test documents the current behavior so any future tightening (e.g. switching to a strict
    // segment match) is a conscious decision, not an accidental regression. If this becomes a
    // problem (e.g. Epic 4 introduces /clientess-share), this test must be flipped and the hook
    // tightened to use a `/` boundary check.
    const { wrapper, getResult } = buildHookWrapper('/clientess-not-a-real-route')

    renderHook(() => null, { wrapper })
    await act(async () => {})

    // THEN: activeId is currently "clientes" by startsWith contract (documented for future review)
    expect(getResult().activeId).toBe('clientes')
  })
})

describe('useShellNavigation — onNavigate (Story 1.2, AC #1, FR28)', () => {
  afterEach(() => {
    cleanup()
  })

  it('[P0] onNavigate("clientes") triggers SPA navigation to /clientes via TanStack Router', async () => {
    // GIVEN: the router starts at /contactos
    const { router, wrapper, getResult } = buildHookWrapper('/contactos')

    renderHook(() => null, { wrapper })
    await act(async () => {})

    // WHEN: onNavigate is invoked with "clientes"
    await act(async () => {
      getResult().onNavigate('clientes')
    })

    // THEN: the router pathname switches to /clientes (URL is the source of truth)
    expect(router.state.location.pathname).toBe('/clientes')
  })

  it('[P0] onNavigate("contactos") triggers SPA navigation to /contactos via TanStack Router', async () => {
    // GIVEN: the router starts at /clientes
    const { router, wrapper, getResult } = buildHookWrapper('/clientes')

    renderHook(() => null, { wrapper })
    await act(async () => {})

    // WHEN: onNavigate is invoked with "contactos"
    await act(async () => {
      getResult().onNavigate('contactos')
    })

    // THEN: the router pathname switches to /contactos
    expect(router.state.location.pathname).toBe('/contactos')
  })

  it('[P1] onNavigate does NOT mutate window.location (no full reload)', async () => {
    // GIVEN: the router starts at /clientes
    const originalAssign = window.location.assign
    const originalReplace = window.location.replace
    let assignCalls = 0
    let replaceCalls = 0
    Object.defineProperty(window, 'location', {
      configurable: true,
      value: {
        ...window.location,
        assign: () => {
          assignCalls += 1
        },
        replace: () => {
          replaceCalls += 1
        },
      },
    })

    const { wrapper, getResult } = buildHookWrapper('/clientes')
    renderHook(() => null, { wrapper })
    await act(async () => {})

    // WHEN: onNavigate fires
    await act(async () => {
      getResult().onNavigate('contactos')
    })

    // THEN: window.location.assign / replace are never invoked
    expect(assignCalls).toBe(0)
    expect(replaceCalls).toBe(0)

    // Restore (defensive — Vitest isolates jsdom per test file but this keeps things tidy)
    Object.defineProperty(window, 'location', {
      configurable: true,
      value: { ...window.location, assign: originalAssign, replace: originalReplace },
    })
  })
})
