using SiesaAgents.Application.Contactos.Commands;
using SiesaAgents.Application.Contactos.Validators;
using SiesaAgents.Domain.Contactos.Entities;
using SiesaAgents.Domain.Contactos.Interfaces;

namespace SiesaAgents.UnitTests.Handlers;

/// <summary>
/// Unit tests for CreateContactoCommandHandler.
///
/// Tests are in RED phase — CreateContactoCommandHandler does not exist yet.
/// Make these tests GREEN by implementing:
///   backend/src/SiesaAgents.Application/Contactos/Commands/CreateContactoCommandHandler.cs
///   backend/src/SiesaAgents.Domain/Contactos/Interfaces/IContactoRepository.cs (add CreateAsync)
///   backend/src/SiesaAgents.Infrastructure/Repositories/ContactoRepository.cs (implement CreateAsync)
///
/// Test IDs: UNIT-B-CT-04
/// </summary>
public class ContactoHandlerTests
{
    // ---------------------------------------------------------------------------
    // UNIT-B-CT-04 (P1 · AC2)
    // Given a valid CreateContactoCommand
    // When CreateContactoCommandHandler.HandleAsync is called
    // Then it returns a ContactoDto
    //   AND the dto.Id is a non-empty UUID
    //   AND the dto.ClienteId is null (Epic 3 scope boundary: ContactoEntity.Create sets ClienteId = null)
    //   AND the dto fields match the command fields
    // ---------------------------------------------------------------------------
    [Fact]
    public async Task HandleAsync_ValidCommand_ReturnsDtoWithUuidIdAndNullClienteId()
    {
        // GIVEN — a capturing repository and a valid command
        var repository = new CapturingContactoRepository();
        var validator = new CreateContactoCommandValidator();
        var handler = new CreateContactoCommandHandler(repository, validator);
        var command = new CreateContactoCommand(
            Nombre: "María García",
            Cargo: "Gerente Comercial",
            Telefono: "+57 1 234 5679",
            Email: "m.garcia@empresa.com"
        );

        // WHEN — handler processes the command
        var dto = await handler.HandleAsync(command, CancellationToken.None);

        // THEN — dto.Id is a non-empty UUID (generated by ContactoEntity.Create factory)
        Assert.NotEqual(Guid.Empty, dto.Id);

        // AND — dto fields match the command
        Assert.Equal("María García", dto.Nombre);
        Assert.Equal("Gerente Comercial", dto.Cargo);
        Assert.Equal("+57 1 234 5679", dto.Telefono);
        Assert.Equal("m.garcia@empresa.com", dto.Email);

        // AND — ClienteId is null (Epic 3 scope boundary)
        Assert.Null(dto.ClienteId);
    }

    // ---------------------------------------------------------------------------
    // Additional: Handler delegates to repository.CreateAsync exactly once
    // ---------------------------------------------------------------------------
    [Fact]
    public async Task HandleAsync_ValidCommand_InvokesRepositoryCreateAsyncOnce()
    {
        // GIVEN
        var repository = new CapturingContactoRepository();
        var validator = new CreateContactoCommandValidator();
        var handler = new CreateContactoCommandHandler(repository, validator);
        var command = new CreateContactoCommand(
            Nombre: "Juan Pérez",
            Cargo: "Analista",
            Telefono: "+57 1 234 5680",
            Email: "j.perez@empresa.com"
        );

        // WHEN
        await handler.HandleAsync(command, CancellationToken.None);

        // THEN — repository.CreateAsync was called exactly once
        Assert.Equal(1, repository.CreateCallCount);
    }

    // ---------------------------------------------------------------------------
    // Additional: Handler passes entity with matching fields to repository
    // ---------------------------------------------------------------------------
    [Fact]
    public async Task HandleAsync_ValidCommand_PassesEntityWithMatchingFieldsToRepository()
    {
        // GIVEN
        var repository = new CapturingContactoRepository();
        var validator = new CreateContactoCommandValidator();
        var handler = new CreateContactoCommandHandler(repository, validator);
        var command = new CreateContactoCommand(
            Nombre: "Ana Rodríguez",
            Cargo: "Directora Comercial",
            Telefono: "+57 1 234 5681",
            Email: "a.rodriguez@empresa.com"
        );

        // WHEN
        await handler.HandleAsync(command, CancellationToken.None);

        // THEN — repository received an entity with matching fields
        Assert.NotNull(repository.LastCreated);
        Assert.Equal("Ana Rodríguez", repository.LastCreated!.Nombre);
        Assert.Equal("Directora Comercial", repository.LastCreated.Cargo);
        Assert.Equal("+57 1 234 5681", repository.LastCreated.Telefono);
        Assert.Equal("a.rodriguez@empresa.com", repository.LastCreated.Email);
        Assert.Null(repository.LastCreated.ClienteId);
    }

    // ---------------------------------------------------------------------------
    // Fakes
    // ---------------------------------------------------------------------------

    /// <summary>
    /// Fake IContactoRepository that captures the entity passed to CreateAsync.
    /// Implements both the existing interface and the new CreateAsync method
    /// required by Story 3.3.
    /// </summary>
    private sealed class CapturingContactoRepository : IContactoRepository
    {
        public int CreateCallCount { get; private set; }
        public ContactoEntity? LastCreated { get; private set; }

        public Task<IEnumerable<ContactoEntity>> GetAllAsync(CancellationToken ct)
            => Task.FromResult<IEnumerable<ContactoEntity>>(Array.Empty<ContactoEntity>());

        public Task<ContactoEntity?> GetByIdAsync(Guid id, CancellationToken ct)
            => Task.FromResult<ContactoEntity?>(null);

        public Task<ContactoEntity> CreateAsync(ContactoEntity entity, CancellationToken ct)
        {
            CreateCallCount++;
            LastCreated = entity;
            return Task.FromResult(entity);
        }
    }
}
