using SiesaAgents.Application.Contactos.Commands;
using SiesaAgents.Application.Contactos.Validators;
using SiesaAgents.Domain.Contactos.Entities;
using SiesaAgents.Domain.Contactos.Interfaces;

namespace SiesaAgents.UnitTests.Handlers;

/// <summary>
/// Unit tests for CreateContactoCommandHandler.
///
/// Tests are in RED phase — CreateContactoCommandHandler does not exist yet.
/// Make these tests GREEN by implementing:
///   backend/src/SiesaAgents.Application/Contactos/Commands/CreateContactoCommandHandler.cs
///   backend/src/SiesaAgents.Domain/Contactos/Interfaces/IContactoRepository.cs (add CreateAsync)
///   backend/src/SiesaAgents.Infrastructure/Repositories/ContactoRepository.cs (implement CreateAsync)
///
/// Test IDs: UNIT-B-CT-04
/// </summary>
public class ContactoHandlerTests
{
    // ---------------------------------------------------------------------------
    // UNIT-B-CT-04 (P1 · AC2)
    // Given a valid CreateContactoCommand
    // When CreateContactoCommandHandler.HandleAsync is called
    // Then it returns a ContactoDto
    //   AND the dto.Id is a non-empty UUID
    //   AND the dto.ClienteId is null (Epic 3 scope boundary: ContactoEntity.Create sets ClienteId = null)
    //   AND the dto fields match the command fields
    // ---------------------------------------------------------------------------
    [Fact]
    public async Task HandleAsync_ValidCommand_ReturnsDtoWithUuidIdAndNullClienteId()
    {
        // GIVEN — a capturing repository and a valid command
        var repository = new CapturingContactoRepository();
        var validator = new CreateContactoCommandValidator();
        var handler = new CreateContactoCommandHandler(repository, validator);
        var command = new CreateContactoCommand(
            Nombre: "María García",
            Cargo: "Gerente Comercial",
            Telefono: "+57 1 234 5679",
            Email: "m.garcia@empresa.com"
        );

        // WHEN — handler processes the command
        var dto = await handler.HandleAsync(command, CancellationToken.None);

        // THEN — dto.Id is a non-empty UUID (generated by ContactoEntity.Create factory)
        Assert.NotEqual(Guid.Empty, dto.Id);

        // AND — dto fields match the command
        Assert.Equal("María García", dto.Nombre);
        Assert.Equal("Gerente Comercial", dto.Cargo);
        Assert.Equal("+57 1 234 5679", dto.Telefono);
        Assert.Equal("m.garcia@empresa.com", dto.Email);

        // AND — ClienteId is null (Epic 3 scope boundary)
        Assert.Null(dto.ClienteId);
    }

    // ---------------------------------------------------------------------------
    // Additional: Handler delegates to repository.CreateAsync exactly once
    // ---------------------------------------------------------------------------
    [Fact]
    public async Task HandleAsync_ValidCommand_InvokesRepositoryCreateAsyncOnce()
    {
        // GIVEN
        var repository = new CapturingContactoRepository();
        var validator = new CreateContactoCommandValidator();
        var handler = new CreateContactoCommandHandler(repository, validator);
        var command = new CreateContactoCommand(
            Nombre: "Juan Pérez",
            Cargo: "Analista",
            Telefono: "+57 1 234 5680",
            Email: "j.perez@empresa.com"
        );

        // WHEN
        await handler.HandleAsync(command, CancellationToken.None);

        // THEN — repository.CreateAsync was called exactly once
        Assert.Equal(1, repository.CreateCallCount);
    }

    // ---------------------------------------------------------------------------
    // Additional: Handler passes entity with matching fields to repository
    // ---------------------------------------------------------------------------
    [Fact]
    public async Task HandleAsync_ValidCommand_PassesEntityWithMatchingFieldsToRepository()
    {
        // GIVEN
        var repository = new CapturingContactoRepository();
        var validator = new CreateContactoCommandValidator();
        var handler = new CreateContactoCommandHandler(repository, validator);
        var command = new CreateContactoCommand(
            Nombre: "Ana Rodríguez",
            Cargo: "Directora Comercial",
            Telefono: "+57 1 234 5681",
            Email: "a.rodriguez@empresa.com"
        );

        // WHEN
        await handler.HandleAsync(command, CancellationToken.None);

        // THEN — repository received an entity with matching fields
        Assert.NotNull(repository.LastCreated);
        Assert.Equal("Ana Rodríguez", repository.LastCreated!.Nombre);
        Assert.Equal("Directora Comercial", repository.LastCreated.Cargo);
        Assert.Equal("+57 1 234 5681", repository.LastCreated.Telefono);
        Assert.Equal("a.rodriguez@empresa.com", repository.LastCreated.Email);
        Assert.Null(repository.LastCreated.ClienteId);
    }

    // ---------------------------------------------------------------------------
    // UNIT-B-CT-06 (P1 · AC2)
    // Given a valid UpdateContactoCommand with an existing contact ID
    // When UpdateContactoCommandHandler.HandleAsync is called
    // Then it returns an updated ContactoDto with the new field values
    // ---------------------------------------------------------------------------
    [Fact]
    public async Task UpdateContactoHandler_ExistingContact_ReturnsUpdatedDto()
    {
        // GIVEN — repository has a contact, handler is configured
        var existing = ContactoEntity.Create("Nombre Original", "Cargo Original", "+57 1 000 0000", "original@empresa.com");
        var repository = new CapturingContactoRepository(existing);
        var validator = new UpdateContactoCommandValidator();
        var handler = new UpdateContactoCommandHandler(repository, validator);

        var command = new UpdateContactoCommand(
            Id: existing.Id,
            Nombre: "Nombre Actualizado",
            Cargo: "Cargo Actualizado",
            Telefono: "+57 1 999 9999",
            Email: "actualizado@empresa.com"
        );

        // WHEN — handler processes the command
        var dto = await handler.HandleAsync(command, CancellationToken.None);

        // THEN — dto contains the updated fields
        Assert.Equal(existing.Id, dto.Id);
        Assert.Equal("Nombre Actualizado", dto.Nombre);
        Assert.Equal("Cargo Actualizado", dto.Cargo);
        Assert.Equal("+57 1 999 9999", dto.Telefono);
        Assert.Equal("actualizado@empresa.com", dto.Email);
        Assert.Null(dto.ClienteId);
    }

    // ---------------------------------------------------------------------------
    // UNIT-B-CT-07 (P1 · AC2)
    // Given a UpdateContactoCommand with a non-existent contact ID
    // When UpdateContactoCommandHandler.HandleAsync is called
    // Then it throws KeyNotFoundException
    // ---------------------------------------------------------------------------
    [Fact]
    public async Task UpdateContactoHandler_NonExistentId_ThrowsKeyNotFoundException()
    {
        // GIVEN — repository returns null for any id (contact not found)
        var repository = new CapturingContactoRepository(null);
        var validator = new UpdateContactoCommandValidator();
        var handler = new UpdateContactoCommandHandler(repository, validator);

        var command = new UpdateContactoCommand(
            Id: Guid.NewGuid(),
            Nombre: "Nombre",
            Cargo: "Cargo",
            Telefono: "+57 1 000 0000",
            Email: "test@empresa.com"
        );

        // WHEN / THEN — handler throws KeyNotFoundException
        await Assert.ThrowsAsync<KeyNotFoundException>(
            () => handler.HandleAsync(command, CancellationToken.None)
        );
    }

    // ---------------------------------------------------------------------------
    // UNIT-B-CT-05 (P1 · AC2)
    // Given an existing ContactoEntity and a DeleteContactoCommandHandler
    // When HandleAsync is called with the entity's id
    // Then it does not throw
    // ---------------------------------------------------------------------------
    [Fact]
    public async Task DeleteContactoHandler_ExistingContact_DoesNotThrow()
    {
        // GIVEN — repository has a contact
        var existing = ContactoEntity.Create("Contacto Eliminar", "Cargo", "+57 1 000 0000", "eliminar@empresa.com");
        var repository = new CapturingContactoRepository(existing);
        var handler = new DeleteContactoCommandHandler(repository);
        var command = new DeleteContactoCommand(existing.Id);

        // WHEN / THEN — handler completes without throwing
        var exception = await Record.ExceptionAsync(() => handler.HandleAsync(command, CancellationToken.None));
        Assert.Null(exception);
    }

    // ---------------------------------------------------------------------------
    // UNIT-B-CT-10 (P1 · AC2)
    // Given a non-existent contact ID
    // When DeleteContactoCommandHandler.HandleAsync is called
    // Then it throws KeyNotFoundException
    // ---------------------------------------------------------------------------
    [Fact]
    public async Task DeleteContactoHandler_NonExistentId_ThrowsKeyNotFoundException()
    {
        // GIVEN — repository returns null for any id
        var repository = new CapturingContactoRepository(null);
        var handler = new DeleteContactoCommandHandler(repository);
        var command = new DeleteContactoCommand(Guid.NewGuid());

        // WHEN / THEN — handler throws KeyNotFoundException
        await Assert.ThrowsAsync<KeyNotFoundException>(
            () => handler.HandleAsync(command, CancellationToken.None)
        );
    }

    // ---------------------------------------------------------------------------
    // Fakes
    // ---------------------------------------------------------------------------

    /// <summary>
    /// Fake IContactoRepository that captures the entity passed to CreateAsync.
    /// Implements both the existing interface and the new CreateAsync method
    /// required by Story 3.3.
    /// </summary>
    private sealed class CapturingContactoRepository : IContactoRepository
    {
        private readonly ContactoEntity? _existingEntity;
        public int CreateCallCount { get; private set; }
        public ContactoEntity? LastCreated { get; private set; }
        public int UpdateCallCount { get; private set; }
        public ContactoEntity? LastUpdated { get; private set; }
        public int DeleteCallCount { get; private set; }
        public ContactoEntity? LastDeleted { get; private set; }

        public CapturingContactoRepository() : this(null) { }

        public CapturingContactoRepository(ContactoEntity? existingEntity)
        {
            _existingEntity = existingEntity;
        }

        public Task<IEnumerable<ContactoEntity>> GetAllAsync(CancellationToken ct)
            => Task.FromResult<IEnumerable<ContactoEntity>>(Array.Empty<ContactoEntity>());

        public Task<ContactoEntity?> GetByIdAsync(Guid id, CancellationToken ct)
            => Task.FromResult(_existingEntity is not null && _existingEntity.Id == id
                ? _existingEntity
                : null);

        public Task<IEnumerable<ContactoEntity>> GetByClienteIdAsync(Guid clienteId, CancellationToken ct)
            => Task.FromResult<IEnumerable<ContactoEntity>>(
                _existingEntity is not null && _existingEntity.ClienteId == clienteId
                    ? new[] { _existingEntity }
                    : Array.Empty<ContactoEntity>());

        public Task<IEnumerable<ContactoEntity>> GetOrphanAsync(CancellationToken ct)
            => Task.FromResult<IEnumerable<ContactoEntity>>(
                _existingEntity is not null && _existingEntity.ClienteId == null
                    ? new[] { _existingEntity }
                    : Array.Empty<ContactoEntity>());

        public Task<ContactoEntity> CreateAsync(ContactoEntity entity, CancellationToken ct)
        {
            CreateCallCount++;
            LastCreated = entity;
            return Task.FromResult(entity);
        }

        public Task<ContactoEntity> UpdateAsync(ContactoEntity entity, CancellationToken ct)
        {
            UpdateCallCount++;
            LastUpdated = entity;
            return Task.FromResult(entity);
        }

        public Task DeleteAsync(ContactoEntity entity, CancellationToken ct)
        {
            DeleteCallCount++;
            LastDeleted = entity;
            return Task.CompletedTask;
        }
    }
}
