using SiesaAgents.Application.Contactos.Commands;
using SiesaAgents.Application.Contactos.Validators;
using SiesaAgents.Domain.Contactos.Entities;
using SiesaAgents.Domain.Contactos.Interfaces;

namespace SiesaAgents.UnitTests.Handlers;

/// <summary>
/// Unit tests for CreateContactoCommandHandler, UpdateContactoCommandHandler,
/// and DeleteContactoCommandHandler.
///
/// Story 3.3 tests (UNIT-B-CT-04): CreateContactoCommandHandler
/// Story 3.4 tests (UNIT-B-CT-06, UNIT-B-CT-07): UpdateContactoCommandHandler
/// Story 3.5 tests (UNIT-B-CT-05, UNIT-B-CT-10): DeleteContactoCommandHandler — RED phase
///
/// Story 3.5 tests are in RED phase — DeleteContactoCommandHandler does not exist yet.
/// Make these tests GREEN by implementing:
///   backend/src/SiesaAgents.Application/Contactos/Commands/DeleteContactoCommand.cs
///   backend/src/SiesaAgents.Application/Contactos/Commands/DeleteContactoCommandHandler.cs
///   backend/src/SiesaAgents.Domain/Contactos/Interfaces/IContactoRepository.cs (add DeleteAsync)
///   backend/src/SiesaAgents.Infrastructure/Repositories/ContactoRepository.cs (implement DeleteAsync)
/// </summary>
public class ContactoHandlerTests
{
    // ---------------------------------------------------------------------------
    // UNIT-B-CT-04 (P1 · AC2)
    // Given a valid CreateContactoCommand
    // When CreateContactoCommandHandler.HandleAsync is called
    // Then it returns a ContactoDto
    //   AND the dto.Id is a non-empty UUID
    //   AND the dto.ClienteId is null (Epic 3 scope boundary: ContactoEntity.Create sets ClienteId = null)
    //   AND the dto fields match the command fields
    // ---------------------------------------------------------------------------
    [Fact]
    public async Task HandleAsync_ValidCommand_ReturnsDtoWithUuidIdAndNullClienteId()
    {
        // GIVEN — a capturing repository and a valid command
        var repository = new CapturingContactoRepository();
        var validator = new CreateContactoCommandValidator();
        var handler = new CreateContactoCommandHandler(repository, validator);
        var command = new CreateContactoCommand(
            Nombre: "María García",
            Cargo: "Gerente Comercial",
            Telefono: "+57 1 234 5679",
            Email: "m.garcia@empresa.com"
        );

        // WHEN — handler processes the command
        var dto = await handler.HandleAsync(command, CancellationToken.None);

        // THEN — dto.Id is a non-empty UUID (generated by ContactoEntity.Create factory)
        Assert.NotEqual(Guid.Empty, dto.Id);

        // AND — dto fields match the command
        Assert.Equal("María García", dto.Nombre);
        Assert.Equal("Gerente Comercial", dto.Cargo);
        Assert.Equal("+57 1 234 5679", dto.Telefono);
        Assert.Equal("m.garcia@empresa.com", dto.Email);

        // AND — ClienteId is null (Epic 3 scope boundary)
        Assert.Null(dto.ClienteId);
    }

    // ---------------------------------------------------------------------------
    // Additional: Handler delegates to repository.CreateAsync exactly once
    // ---------------------------------------------------------------------------
    [Fact]
    public async Task HandleAsync_ValidCommand_InvokesRepositoryCreateAsyncOnce()
    {
        // GIVEN
        var repository = new CapturingContactoRepository();
        var validator = new CreateContactoCommandValidator();
        var handler = new CreateContactoCommandHandler(repository, validator);
        var command = new CreateContactoCommand(
            Nombre: "Juan Pérez",
            Cargo: "Analista",
            Telefono: "+57 1 234 5680",
            Email: "j.perez@empresa.com"
        );

        // WHEN
        await handler.HandleAsync(command, CancellationToken.None);

        // THEN — repository.CreateAsync was called exactly once
        Assert.Equal(1, repository.CreateCallCount);
    }

    // ---------------------------------------------------------------------------
    // Additional: Handler passes entity with matching fields to repository
    // ---------------------------------------------------------------------------
    [Fact]
    public async Task HandleAsync_ValidCommand_PassesEntityWithMatchingFieldsToRepository()
    {
        // GIVEN
        var repository = new CapturingContactoRepository();
        var validator = new CreateContactoCommandValidator();
        var handler = new CreateContactoCommandHandler(repository, validator);
        var command = new CreateContactoCommand(
            Nombre: "Ana Rodríguez",
            Cargo: "Directora Comercial",
            Telefono: "+57 1 234 5681",
            Email: "a.rodriguez@empresa.com"
        );

        // WHEN
        await handler.HandleAsync(command, CancellationToken.None);

        // THEN — repository received an entity with matching fields
        Assert.NotNull(repository.LastCreated);
        Assert.Equal("Ana Rodríguez", repository.LastCreated!.Nombre);
        Assert.Equal("Directora Comercial", repository.LastCreated.Cargo);
        Assert.Equal("+57 1 234 5681", repository.LastCreated.Telefono);
        Assert.Equal("a.rodriguez@empresa.com", repository.LastCreated.Email);
        Assert.Null(repository.LastCreated.ClienteId);
    }

    // ---------------------------------------------------------------------------
    // UNIT-B-CT-06 (P1 · AC2 — Story 3.4)
    // Given an UpdateContactoCommand with a contactoId that exists
    // When UpdateContactoCommandHandler.HandleAsync is called
    // Then it returns a ContactoDto
    //   AND the dto fields match the updated command fields
    //   AND the dto.Id matches the original contact Id
    // ---------------------------------------------------------------------------
    [Fact]
    public async Task UpdateHandleAsync_ExistingContact_ReturnsUpdatedDto()
    {
        // GIVEN — an existing contact in the repository
        var existing = ContactoEntity.Create(
            nombre: "María García Original",
            cargo: "Analista",
            telefono: "+57 1 234 5679",
            email: "m.garcia@empresa.com"
        );
        var repository = new UpdatableContactoRepository(existing);
        var validator = new UpdateContactoCommandValidator();
        var handler = new UpdateContactoCommandHandler(repository, validator);
        var command = new UpdateContactoCommand(
            Id: existing.Id,
            Nombre: "María García Actualizada",
            Cargo: "Directora Comercial",
            Telefono: "+57 1 234 5680",
            Email: "m.garcia.new@empresa.com"
        );

        // WHEN — handler processes the update command
        var dto = await handler.HandleAsync(command, CancellationToken.None);

        // THEN — dto.Id matches the original contact id
        Assert.Equal(existing.Id, dto.Id);

        // AND — dto fields reflect the updated values from the command
        Assert.Equal("María García Actualizada", dto.Nombre);
        Assert.Equal("Directora Comercial", dto.Cargo);
        Assert.Equal("+57 1 234 5680", dto.Telefono);
        Assert.Equal("m.garcia.new@empresa.com", dto.Email);
    }

    // ---------------------------------------------------------------------------
    // UNIT-B-CT-07 (P1 · AC2 — Story 3.4)
    // Given an UpdateContactoCommand with a contactoId that does NOT exist
    // When UpdateContactoCommandHandler.HandleAsync is called
    // Then it throws KeyNotFoundException
    // ---------------------------------------------------------------------------
    [Fact]
    public async Task UpdateHandleAsync_NotExistingContact_ThrowsKeyNotFoundException()
    {
        // GIVEN — repository returns null for any id (contact does not exist)
        var repository = new CapturingContactoRepository(); // GetByIdAsync returns null
        var validator = new UpdateContactoCommandValidator();
        var handler = new UpdateContactoCommandHandler(repository, validator);
        var command = new UpdateContactoCommand(
            Id: Guid.NewGuid(),
            Nombre: "Nombre",
            Cargo: "Cargo",
            Telefono: "+57 1 234 5679",
            Email: "test@empresa.com"
        );

        // WHEN / THEN — handler throws KeyNotFoundException
        await Assert.ThrowsAsync<KeyNotFoundException>(
            () => handler.HandleAsync(command, CancellationToken.None));
    }

    // ---------------------------------------------------------------------------
    // UNIT-B-CT-05 (P1 · AC2 — Story 3.5)
    // Given a DeleteContactoCommand with a contactoId that exists in the system
    // When DeleteContactoCommandHandler.HandleAsync is called
    // Then it completes without throwing any exception
    //   AND the repository's DeleteAsync is invoked exactly once
    // ---------------------------------------------------------------------------
    [Fact]
    public async Task DeleteHandleAsync_ExistingContact_CompletesWithoutThrow()
    {
        // GIVEN — an existing contact in the repository
        var existing = ContactoEntity.Create(
            nombre: "Contacto Para Eliminar",
            cargo: "Analista",
            telefono: "+57 1 234 5679",
            email: "contacto.eliminar@empresa.com"
        );
        var repository = new DeletableContactoRepository(existing);
        var handler = new DeleteContactoCommandHandler(repository);
        var command = new DeleteContactoCommand(existing.Id);

        // WHEN — handler processes the delete command
        // THEN — no exception is thrown (handler completes successfully)
        var exception = await Record.ExceptionAsync(
            () => handler.HandleAsync(command, CancellationToken.None));

        Assert.Null(exception);

        // AND — repository.DeleteAsync was called exactly once
        Assert.Equal(1, repository.DeleteCallCount);
    }

    // ---------------------------------------------------------------------------
    // UNIT-B-CT-10 (P1 · AC2 — Story 3.5)
    // Given a DeleteContactoCommand with a contactoId that does NOT exist
    // When DeleteContactoCommandHandler.HandleAsync is called
    // Then it throws KeyNotFoundException
    // ---------------------------------------------------------------------------
    [Fact]
    public async Task DeleteHandleAsync_NotExistingContact_ThrowsKeyNotFoundException()
    {
        // GIVEN — repository returns null for any id (contact does not exist)
        var repository = new CapturingContactoRepository(); // GetByIdAsync returns null
        var handler = new DeleteContactoCommandHandler(repository);
        var command = new DeleteContactoCommand(Guid.NewGuid());

        // WHEN / THEN — handler throws KeyNotFoundException
        await Assert.ThrowsAsync<KeyNotFoundException>(
            () => handler.HandleAsync(command, CancellationToken.None));
    }

    // ---------------------------------------------------------------------------
    // Fakes
    // ---------------------------------------------------------------------------

    /// <summary>
    /// Fake IContactoRepository that captures the entity passed to CreateAsync.
    /// Implements both the existing interface and the new CreateAsync method
    /// required by Story 3.3.
    /// </summary>
    private sealed class CapturingContactoRepository : IContactoRepository
    {
        public int CreateCallCount { get; private set; }
        public ContactoEntity? LastCreated { get; private set; }

        public Task<IEnumerable<ContactoEntity>> GetAllAsync(CancellationToken ct)
            => Task.FromResult<IEnumerable<ContactoEntity>>(Array.Empty<ContactoEntity>());

        public Task<ContactoEntity?> GetByIdAsync(Guid id, CancellationToken ct)
            => Task.FromResult<ContactoEntity?>(null);

        public Task<ContactoEntity> CreateAsync(ContactoEntity entity, CancellationToken ct)
        {
            CreateCallCount++;
            LastCreated = entity;
            return Task.FromResult(entity);
        }

        public Task<ContactoEntity> UpdateAsync(ContactoEntity entity, CancellationToken ct)
            => Task.FromResult(entity);

        public Task DeleteAsync(ContactoEntity entity, CancellationToken ct)
            => Task.CompletedTask;
    }

    /// <summary>
    /// Fake IContactoRepository that returns a specific existing contact from GetByIdAsync
    /// and captures the entity passed to UpdateAsync. Used by Story 3.4 tests.
    /// </summary>
    private sealed class UpdatableContactoRepository : IContactoRepository
    {
        private readonly ContactoEntity _entity;

        public UpdatableContactoRepository(ContactoEntity entity)
        {
            _entity = entity;
        }

        public Task<IEnumerable<ContactoEntity>> GetAllAsync(CancellationToken ct)
            => Task.FromResult<IEnumerable<ContactoEntity>>(new[] { _entity });

        public Task<ContactoEntity?> GetByIdAsync(Guid id, CancellationToken ct)
            => Task.FromResult<ContactoEntity?>(_entity.Id == id ? _entity : null);

        public Task<ContactoEntity> CreateAsync(ContactoEntity entity, CancellationToken ct)
            => Task.FromResult(entity);

        public Task<ContactoEntity> UpdateAsync(ContactoEntity entity, CancellationToken ct)
            => Task.FromResult(entity);

        public Task DeleteAsync(ContactoEntity entity, CancellationToken ct)
            => Task.CompletedTask;
    }

    /// <summary>
    /// Fake IContactoRepository that holds an existing entity and tracks DeleteAsync calls.
    /// Used by Story 3.5 tests (UNIT-B-CT-05).
    /// </summary>
    private sealed class DeletableContactoRepository : IContactoRepository
    {
        private readonly ContactoEntity _entity;
        public int DeleteCallCount { get; private set; }

        public DeletableContactoRepository(ContactoEntity entity)
        {
            _entity = entity;
        }

        public Task<IEnumerable<ContactoEntity>> GetAllAsync(CancellationToken ct)
            => Task.FromResult<IEnumerable<ContactoEntity>>(new[] { _entity });

        public Task<ContactoEntity?> GetByIdAsync(Guid id, CancellationToken ct)
            => Task.FromResult<ContactoEntity?>(_entity.Id == id ? _entity : null);

        public Task<ContactoEntity> CreateAsync(ContactoEntity entity, CancellationToken ct)
            => Task.FromResult(entity);

        public Task<ContactoEntity> UpdateAsync(ContactoEntity entity, CancellationToken ct)
            => Task.FromResult(entity);

        public Task DeleteAsync(ContactoEntity entity, CancellationToken ct)
        {
            DeleteCallCount++;
            return Task.CompletedTask;
        }
    }
}
