using FluentValidation;
using SiesaAgents.Application.Contactos.Commands;
using SiesaAgents.Application.Contactos.Validators;
using SiesaAgents.Domain.Contactos.Entities;
using SiesaAgents.Domain.Contactos.Interfaces;

namespace SiesaAgents.UnitTests.Handlers;

/// <summary>
/// Edge case unit tests for CreateContactoCommandHandler — Story 3.3.
/// BMad-Integrated: expands coverage beyond ATDD test UNIT-B-CT-04.
///
/// Test IDs: UNIT-B-CT-CREATE-EDGE-01 … UNIT-B-CT-CREATE-EDGE-07
///
/// Risks covered:
///   - Handler throws ValidationException when command is invalid (empty nombre)
///   - Handler throws ValidationException when email format is invalid
///   - Handler throws ValidationException when all fields are empty
///   - Thrown ValidationException contains the localized error message
///   - Handler with valid command sets CreatedAt and UpdatedAt (recent UTC values)
///   - Repository exception propagates through the handler (error path)
///   - Entity Id generated by handler is a valid non-empty GUID
/// </summary>
public class CreateContactoCommandHandlerEdgeCaseTests
{
    // ---------------------------------------------------------------------------
    // UNIT-B-CT-CREATE-EDGE-01: Handler throws ValidationException for empty Nombre
    // The handler calls validator.ValidateAsync before creating the entity.
    // A ValidationException must be thrown — NOT silently ignored.
    // ---------------------------------------------------------------------------
    [Fact]
    public async Task HandleAsync_EmptyNombre_ThrowsValidationException()
    {
        // GIVEN — repository and handler; command with empty Nombre
        var repository = new CapturingContactoRepository();
        var validator = new CreateContactoCommandValidator();
        var handler = new CreateContactoCommandHandler(repository, validator);
        var command = new CreateContactoCommand(
            Nombre: string.Empty,
            Cargo: "Analista",
            Telefono: "+57 310 000 0001",
            Email: "test@empresa.com"
        );

        // WHEN / THEN — handler throws ValidationException
        await Assert.ThrowsAsync<ValidationException>(
            () => handler.HandleAsync(command, CancellationToken.None));
    }

    // ---------------------------------------------------------------------------
    // UNIT-B-CT-CREATE-EDGE-02: Handler throws ValidationException for invalid email
    // The application layer must enforce email format before reaching the repository.
    // ---------------------------------------------------------------------------
    [Fact]
    public async Task HandleAsync_InvalidEmailFormat_ThrowsValidationException()
    {
        // GIVEN
        var repository = new CapturingContactoRepository();
        var validator = new CreateContactoCommandValidator();
        var handler = new CreateContactoCommandHandler(repository, validator);
        var command = new CreateContactoCommand(
            Nombre: "María García",
            Cargo: "Analista",
            Telefono: "+57 310 000 0002",
            Email: "not-an-email"
        );

        // WHEN / THEN
        await Assert.ThrowsAsync<ValidationException>(
            () => handler.HandleAsync(command, CancellationToken.None));
    }

    // ---------------------------------------------------------------------------
    // UNIT-B-CT-CREATE-EDGE-03: Handler throws ValidationException for all-empty command
    // All four required fields are empty — ValidationException must expose all errors.
    // ---------------------------------------------------------------------------
    [Fact]
    public async Task HandleAsync_AllFieldsEmpty_ThrowsValidationExceptionWithMultipleErrors()
    {
        // GIVEN
        var repository = new CapturingContactoRepository();
        var validator = new CreateContactoCommandValidator();
        var handler = new CreateContactoCommandHandler(repository, validator);
        var command = new CreateContactoCommand(
            Nombre: string.Empty,
            Cargo: string.Empty,
            Telefono: string.Empty,
            Email: string.Empty
        );

        // WHEN / THEN — throws with at least one error for each empty field
        var ex = await Assert.ThrowsAsync<ValidationException>(
            () => handler.HandleAsync(command, CancellationToken.None));

        Assert.NotNull(ex.Errors);
        Assert.True(ex.Errors.Count() >= 4,
            $"Expected at least 4 validation errors, got {ex.Errors.Count()}");
    }

    // ---------------------------------------------------------------------------
    // UNIT-B-CT-CREATE-EDGE-04: ValidationException thrown by handler contains localized message
    // The Spanish error message defined in CreateContactoCommandValidator must surface.
    // ---------------------------------------------------------------------------
    [Fact]
    public async Task HandleAsync_EmptyNombre_ValidationExceptionContainsLocalizedMessage()
    {
        // GIVEN
        var repository = new CapturingContactoRepository();
        var validator = new CreateContactoCommandValidator();
        var handler = new CreateContactoCommandHandler(repository, validator);
        var command = new CreateContactoCommand(
            Nombre: string.Empty,
            Cargo: "Analista",
            Telefono: "+57 310 000 0004",
            Email: "test@empresa.com"
        );

        // WHEN / THEN
        var ex = await Assert.ThrowsAsync<ValidationException>(
            () => handler.HandleAsync(command, CancellationToken.None));

        // AND — the exception contains a non-empty Spanish message for Nombre
        var nombreError = ex.Errors.FirstOrDefault(e => e.PropertyName == nameof(CreateContactoCommand.Nombre));
        Assert.NotNull(nombreError);
        Assert.False(string.IsNullOrWhiteSpace(nombreError.ErrorMessage));
    }

    // ---------------------------------------------------------------------------
    // UNIT-B-CT-CREATE-EDGE-05: Handler does NOT call repository when validation fails
    // If validation throws, CreateAsync must NOT be called (prevents partial writes).
    // ---------------------------------------------------------------------------
    [Fact]
    public async Task HandleAsync_InvalidCommand_DoesNotCallRepository()
    {
        // GIVEN
        var repository = new CapturingContactoRepository();
        var validator = new CreateContactoCommandValidator();
        var handler = new CreateContactoCommandHandler(repository, validator);
        var command = new CreateContactoCommand(
            Nombre: string.Empty,
            Cargo: string.Empty,
            Telefono: string.Empty,
            Email: string.Empty
        );

        // WHEN — handler throws (invalid input)
        await Assert.ThrowsAsync<ValidationException>(
            () => handler.HandleAsync(command, CancellationToken.None));

        // THEN — repository was NOT called (transaction guard)
        Assert.Equal(0, repository.CreateCallCount);
    }

    // ---------------------------------------------------------------------------
    // UNIT-B-CT-CREATE-EDGE-06: Valid command — returned DTO has recent CreatedAt (UTC)
    // The entity's CreatedAt must be a DateTimeOffset with UTC offset (not plain DateTime).
    // ---------------------------------------------------------------------------
    [Fact]
    public async Task HandleAsync_ValidCommand_ReturnsDtoWithRecentUtcCreatedAt()
    {
        // GIVEN
        var repository = new CapturingContactoRepository();
        var validator = new CreateContactoCommandValidator();
        var handler = new CreateContactoCommandHandler(repository, validator);
        var command = new CreateContactoCommand(
            Nombre: "Carlos López",
            Cargo: "Analista TI",
            Telefono: "+57 310 000 0006",
            Email: "c.lopez@empresa.com"
        );

        var before = DateTimeOffset.UtcNow.AddSeconds(-5);

        // WHEN
        var dto = await handler.HandleAsync(command, CancellationToken.None);

        var after = DateTimeOffset.UtcNow.AddSeconds(5);

        // THEN — CreatedAt is within a recent UTC window
        Assert.InRange(dto.CreatedAt, before, after);
        Assert.Equal(TimeSpan.Zero, dto.CreatedAt.Offset); // UTC offset
    }

    // ---------------------------------------------------------------------------
    // UNIT-B-CT-CREATE-EDGE-07: Repository exception propagates through handler
    // Error path: if the DB save fails, the exception must surface to the caller.
    // The handler must NOT swallow infrastructure errors.
    // ---------------------------------------------------------------------------
    [Fact]
    public async Task HandleAsync_RepositoryThrows_PropagatesException()
    {
        // GIVEN — repository that throws on CreateAsync
        var repository = new ThrowingContactoRepository(new Exception("Database connection lost"));
        var validator = new CreateContactoCommandValidator();
        var handler = new CreateContactoCommandHandler(repository, validator);
        var command = new CreateContactoCommand(
            Nombre: "Ana Rodríguez",
            Cargo: "Directora",
            Telefono: "+57 310 000 0007",
            Email: "a.rodriguez@empresa.com"
        );

        // WHEN / THEN — exception from repository propagates unchanged
        var ex = await Assert.ThrowsAsync<Exception>(
            () => handler.HandleAsync(command, CancellationToken.None));

        Assert.Equal("Database connection lost", ex.Message);
    }

    // ---------------------------------------------------------------------------
    // Fakes
    // ---------------------------------------------------------------------------

    /// <summary>
    /// Fake IContactoRepository that captures the entity passed to CreateAsync.
    /// Supports tracking call count and last-created entity for assertion.
    /// </summary>
    private sealed class CapturingContactoRepository : IContactoRepository
    {
        public int CreateCallCount { get; private set; }
        public ContactoEntity? LastCreated { get; private set; }

        public Task<IEnumerable<ContactoEntity>> GetAllAsync(CancellationToken ct)
            => Task.FromResult<IEnumerable<ContactoEntity>>(Array.Empty<ContactoEntity>());

        public Task<ContactoEntity?> GetByIdAsync(Guid id, CancellationToken ct)
            => Task.FromResult<ContactoEntity?>(null);

        public Task<IEnumerable<ContactoEntity>> GetByClienteIdAsync(Guid clienteId, CancellationToken ct)
            => Task.FromResult<IEnumerable<ContactoEntity>>(Array.Empty<ContactoEntity>());

        public Task<ContactoEntity> CreateAsync(ContactoEntity entity, CancellationToken ct)
        {
            CreateCallCount++;
            LastCreated = entity;
            return Task.FromResult(entity);
        }

        public Task<ContactoEntity> UpdateAsync(ContactoEntity entity, CancellationToken ct)
            => Task.FromResult(entity);

        public Task DeleteAsync(ContactoEntity entity, CancellationToken ct)
            => Task.CompletedTask;
    }

    /// <summary>
    /// Fake IContactoRepository that throws on CreateAsync to simulate DB failures.
    /// </summary>
    private sealed class ThrowingContactoRepository : IContactoRepository
    {
        private readonly Exception _exception;

        public ThrowingContactoRepository(Exception exception) => _exception = exception;

        public Task<IEnumerable<ContactoEntity>> GetAllAsync(CancellationToken ct)
            => Task.FromResult<IEnumerable<ContactoEntity>>(Array.Empty<ContactoEntity>());

        public Task<ContactoEntity?> GetByIdAsync(Guid id, CancellationToken ct)
            => Task.FromResult<ContactoEntity?>(null);

        public Task<IEnumerable<ContactoEntity>> GetByClienteIdAsync(Guid clienteId, CancellationToken ct)
            => Task.FromException<IEnumerable<ContactoEntity>>(_exception);

        public Task<ContactoEntity> CreateAsync(ContactoEntity entity, CancellationToken ct)
            => Task.FromException<ContactoEntity>(_exception);

        public Task<ContactoEntity> UpdateAsync(ContactoEntity entity, CancellationToken ct)
            => Task.FromException<ContactoEntity>(_exception);

        public Task DeleteAsync(ContactoEntity entity, CancellationToken ct)
            => Task.FromException(_exception);
    }
}
