using System.Linq;
using System.Net;
using System.Text.Json;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using SiesaAgents.Infrastructure.Data;
using Xunit;

namespace SiesaAgents.IntegrationTests;

/// <summary>
/// Story 2.1 — Client List & Search (Epic 2)
/// ATDD API Integration Tests — RED phase. Generated by testarch-atdd.
///
/// Failing until DEV implements per AC-2.1.e (Task 3):
///   - <c>GET /api/v1/clientes</c> via <c>ClienteEndpoints.MapClienteEndpoints()</c>
///   - <c>app.MapClienteEndpoints()</c> wired in <c>Program.cs</c>
///   - <c>IClienteRepository</c> DI registration
///
/// The test overrides the production Postgres DbContext with EF Core InMemory
/// (mirroring the pattern documented in story Task 4 + existing
/// ProblemDetailsTests). This keeps the suite in <c>Category=Api</c> — the
/// schema-truth <c>Category=Db</c> tests are QA-owned (TC-E2-P2-03).
///
/// Expected RED failure: 404 (route not mounted) — once the endpoint is
/// registered, the assertions for shape and contract take over.
/// </summary>
[Trait("Category", "Api")]
public class ClienteEndpointsTests : IClassFixture<WebApplicationFactory<Program>>
{
    private readonly WebApplicationFactory<Program> _factory;

    public ClienteEndpointsTests(WebApplicationFactory<Program> factory)
    {
        // GIVEN: a test host that swaps Postgres for EF Core InMemory so the
        //        integration test does NOT require Docker/Postgres.
        _factory = factory.WithWebHostBuilder(builder =>
        {
            builder.UseEnvironment("Development");
            builder.ConfigureServices(services =>
            {
                // Remove EVERY descriptor that contributes to AppDbContext (the
                // options, the context itself, and any IDbContextOptionsConfiguration
                // registered by Program.cs's AddDbContext call). Then register a fresh
                // InMemory-backed AppDbContext for this test host.
                var toRemove = services
                    .Where(d =>
                        d.ServiceType == typeof(DbContextOptions<AppDbContext>) ||
                        d.ServiceType == typeof(DbContextOptions) ||
                        d.ServiceType == typeof(AppDbContext) ||
                        (d.ServiceType.IsGenericType &&
                         d.ServiceType.GetGenericTypeDefinition().Name.StartsWith("IDbContextOptionsConfiguration", StringComparison.Ordinal)))
                    .ToList();
                foreach (var d in toRemove)
                {
                    services.Remove(d);
                }

                services.AddDbContext<AppDbContext>(options =>
                {
                    options.UseInMemoryDatabase($"clientes-endpoints-tests-{Guid.NewGuid()}");
                });
            });
        });
    }

    [Fact]
    public async Task GetClientes_ReturnsOk()
    {
        // GIVEN: an empty in-memory database — the endpoint exists
        var client = _factory.CreateClient();

        // WHEN
        var response = await client.GetAsync("/api/v1/clientes");

        // THEN: 200 OK (NOT 404 — the route must be mounted)
        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
    }

    [Fact]
    public async Task GetClientes_ContentTypeIsJson()
    {
        // GIVEN
        var client = _factory.CreateClient();

        // WHEN
        var response = await client.GetAsync("/api/v1/clientes");

        // THEN: response media type is application/json (NOT problem+json)
        Assert.Equal("application/json", response.Content.Headers.ContentType?.MediaType);
    }

    [Fact]
    public async Task GetClientes_ReturnsJsonArray_WhenEmpty()
    {
        // GIVEN: an empty database
        var client = _factory.CreateClient();

        // WHEN
        var response = await client.GetAsync("/api/v1/clientes");
        var body = await response.Content.ReadAsStringAsync();
        using var doc = JsonDocument.Parse(body);

        // THEN: body is a JSON array (NO wrapper object) of length 0
        Assert.Equal(JsonValueKind.Array, doc.RootElement.ValueKind);
        Assert.Equal(0, doc.RootElement.GetArrayLength());
    }

    [Fact]
    public async Task GetClientes_DoesNotExpose_SwaggerOrUnrelatedRoutes()
    {
        // GIVEN: Story 2.1 must NOT introduce a query parameter (?q=) — search
        //        is 100% client-side per architecture line 233.
        //        Hitting the endpoint with a bogus query MUST still return the
        //        full list (i.e. the param is ignored, not honored).
        var client = _factory.CreateClient();

        // WHEN
        var response = await client.GetAsync("/api/v1/clientes?q=anything");

        // THEN: still 200 OK with the array shape — the parameter is silently ignored.
        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
        var body = await response.Content.ReadAsStringAsync();
        using var doc = JsonDocument.Parse(body);
        Assert.Equal(JsonValueKind.Array, doc.RootElement.ValueKind);
    }
}
