namespace SiesaAgents.IntegrationTests;

/// <summary>
/// Edge-case coverage for <c>ExceptionHandlingMiddleware</c> beyond what
/// <see cref="ExceptionHandlingMiddlewareTests"/> exercises in the ATDD phase.
///
/// Focuses on NFR6 (no information leakage) and RFC 7807 contract details:
///   * <c>instance</c> reflects the actual request path (not a hardcoded value).
///   * <c>status</c> is an INTEGER 500, not a quoted string.
///   * <c>title</c> exists and is non-empty.
///   * <c>type</c> is a well-formed absolute URI (RFC 7807 recommends a URI).
///   * The middleware does NOT echo arbitrary attacker-supplied query strings into
///     the body or headers (defense against reflected-content attacks).
///   * Repeated calls to the same endpoint produce independent, isolated responses
///     (no state leakage across requests inside the middleware).
///   * The middleware does NOT add a <c>Detail</c> property populated from <c>ex.Message</c>.
/// </summary>
public class ExceptionHandlingMiddlewareEdgeCasesTests
{
    /// <summary>
    /// AC #3 edge case — the <c>instance</c> RFC 7807 member must reflect the actual
    /// request path so operators can correlate the failure with their request log.
    /// </summary>
    [Fact]
    public async Task TestError_Body_InstanceFieldEqualsRequestPath()
    {
        // GIVEN
        await using var factory = new SiesaAgentsWebApplicationFactory();
        var client = factory.CreateClient();

        // WHEN
        var response = await client.GetAsync("/api/v1/test-error");
        var body = await response.Content.ReadAsStringAsync();
        using var json = JsonDocument.Parse(body);

        // THEN
        Assert.True(json.RootElement.TryGetProperty("instance", out var instance));
        Assert.Equal("/api/v1/test-error", instance.GetString());
    }

    /// <summary>
    /// AC #3 edge case — <c>status</c> must serialize as a JSON number (integer),
    /// not as a string. Clients consuming the Problem Details spec rely on the
    /// type to drive error-handling logic (RFC 7807 §3.1 "status" — "MUST be set
    /// to the HTTP status code generated by the origin server").
    /// </summary>
    [Fact]
    public async Task TestError_Body_StatusIsIntegerNumber()
    {
        // GIVEN
        await using var factory = new SiesaAgentsWebApplicationFactory();
        var client = factory.CreateClient();

        // WHEN
        var response = await client.GetAsync("/api/v1/test-error");
        var body = await response.Content.ReadAsStringAsync();
        using var json = JsonDocument.Parse(body);

        // THEN
        Assert.True(json.RootElement.TryGetProperty("status", out var status));
        Assert.Equal(JsonValueKind.Number, status.ValueKind);
        Assert.Equal(500, status.GetInt32());
    }

    /// <summary>
    /// AC #3 edge case — <c>title</c> must be a non-empty human-readable string.
    /// </summary>
    [Fact]
    public async Task TestError_Body_TitleIsNonEmptyString()
    {
        // GIVEN
        await using var factory = new SiesaAgentsWebApplicationFactory();
        var client = factory.CreateClient();

        // WHEN
        var response = await client.GetAsync("/api/v1/test-error");
        var body = await response.Content.ReadAsStringAsync();
        using var json = JsonDocument.Parse(body);

        // THEN
        Assert.True(json.RootElement.TryGetProperty("title", out var title));
        Assert.Equal(JsonValueKind.String, title.ValueKind);
        Assert.False(string.IsNullOrWhiteSpace(title.GetString()));
    }

    /// <summary>
    /// AC #3 edge case — RFC 7807 §3.1 "type" is a URI reference. The current
    /// implementation uses <c>https://tools.ietf.org/html/rfc7231#section-6.6.1</c>;
    /// assert it is a well-formed absolute URI rather than literal text.
    /// </summary>
    [Fact]
    public async Task TestError_Body_TypeIsWellFormedAbsoluteUri()
    {
        // GIVEN
        await using var factory = new SiesaAgentsWebApplicationFactory();
        var client = factory.CreateClient();

        // WHEN
        var response = await client.GetAsync("/api/v1/test-error");
        var body = await response.Content.ReadAsStringAsync();
        using var json = JsonDocument.Parse(body);

        // THEN
        Assert.True(json.RootElement.TryGetProperty("type", out var type));
        Assert.Equal(JsonValueKind.String, type.ValueKind);
        var typeValue = type.GetString();
        Assert.NotNull(typeValue);
        Assert.True(Uri.IsWellFormedUriString(typeValue, UriKind.Absolute),
            $"'type' must be an absolute URI but was '{typeValue}'.");
    }

    /// <summary>
    /// AC #3 / NFR6 edge case — the middleware must NOT populate the optional
    /// <c>detail</c> RFC 7807 field with the raw exception message (or anything
    /// that could leak implementation details).
    /// </summary>
    [Fact]
    public async Task TestError_Body_DetailFieldIsAbsentOrNull()
    {
        // GIVEN
        await using var factory = new SiesaAgentsWebApplicationFactory();
        var client = factory.CreateClient();

        // WHEN
        var response = await client.GetAsync("/api/v1/test-error");
        var body = await response.Content.ReadAsStringAsync();
        using var json = JsonDocument.Parse(body);

        // THEN
        if (json.RootElement.TryGetProperty("detail", out var detail))
        {
            // If present, must be null or empty — never carry "internal test".
            Assert.True(detail.ValueKind == JsonValueKind.Null
                        || string.IsNullOrEmpty(detail.GetString()),
                "'detail' must not be populated (NFR6 — no leakage).");
        }
    }

    /// <summary>
    /// AC #3 edge case — repeated invocations of the same throw-test endpoint
    /// must each produce an independent 500 response (no state leakage).
    /// </summary>
    [Fact]
    public async Task TestError_MultipleInvocations_AllReturn500Independently()
    {
        // GIVEN
        await using var factory = new SiesaAgentsWebApplicationFactory();
        var client = factory.CreateClient();

        // WHEN
        var first = await client.GetAsync("/api/v1/test-error");
        var second = await client.GetAsync("/api/v1/test-error");
        var third = await client.GetAsync("/api/v1/test-error");

        // THEN
        Assert.Equal(HttpStatusCode.InternalServerError, first.StatusCode);
        Assert.Equal(HttpStatusCode.InternalServerError, second.StatusCode);
        Assert.Equal(HttpStatusCode.InternalServerError, third.StatusCode);
        Assert.Equal("application/problem+json", first.Content.Headers.ContentType?.MediaType);
        Assert.Equal("application/problem+json", second.Content.Headers.ContentType?.MediaType);
        Assert.Equal("application/problem+json", third.Content.Headers.ContentType?.MediaType);
    }

    /// <summary>
    /// AC #3 edge case — concurrent requests to the throw-test endpoint must each
    /// receive their own 500/problem+json response. Catches accidental shared
    /// HttpContext / ProblemDetails state inside the middleware.
    /// </summary>
    [Fact]
    public async Task TestError_ConcurrentInvocations_AllReturn500()
    {
        // GIVEN
        await using var factory = new SiesaAgentsWebApplicationFactory();
        var client = factory.CreateClient();

        // WHEN
        var tasks = Enumerable.Range(0, 8)
            .Select(_ => client.GetAsync("/api/v1/test-error"))
            .ToArray();
        var responses = await Task.WhenAll(tasks);

        // THEN
        Assert.All(responses, r =>
        {
            Assert.Equal(HttpStatusCode.InternalServerError, r.StatusCode);
            Assert.Equal("application/problem+json", r.Content.Headers.ContentType?.MediaType);
        });
    }

    /// <summary>
    /// AC #3 / NFR6 edge case — query-string content supplied by the caller must
    /// NOT be reflected into the response body or any header. Defends against
    /// reflected XSS / log-injection via the <c>instance</c> field.
    /// </summary>
    [Fact]
    public async Task TestError_AttackerSuppliedQueryString_IsNotReflectedIntoBody()
    {
        // GIVEN
        await using var factory = new SiesaAgentsWebApplicationFactory();
        var client = factory.CreateClient();
        var malicious = "?attack=<script>alert(1)</script>&leak=__SECRET__";

        // WHEN
        var response = await client.GetAsync("/api/v1/test-error" + malicious);
        var body = await response.Content.ReadAsStringAsync();

        // THEN
        Assert.Equal(HttpStatusCode.InternalServerError, response.StatusCode);
        Assert.DoesNotContain("<script>", body, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("__SECRET__", body, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("alert(1)", body, StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>
    /// AC #3 edge case — the response must use the exact MIME type
    /// <c>application/problem+json</c> (with no charset suffix relied upon by
    /// the tests, but charset parameters are tolerated per RFC).
    /// </summary>
    [Fact]
    public async Task TestError_ContentType_IsApplicationProblemJson_NotPlainJson()
    {
        // GIVEN
        await using var factory = new SiesaAgentsWebApplicationFactory();
        var client = factory.CreateClient();

        // WHEN
        var response = await client.GetAsync("/api/v1/test-error");

        // THEN — explicit negative: must NOT be plain application/json
        var mediaType = response.Content.Headers.ContentType?.MediaType;
        Assert.Equal("application/problem+json", mediaType);
        Assert.NotEqual("application/json", mediaType);
    }
}
