using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using SiesaAgents.Domain.Clientes.Entities;
using SiesaAgents.Infrastructure.Data;
using SiesaAgents.Infrastructure.Data.Configurations;
using SiesaAgents.Infrastructure.Data.Extensions;
using Xunit;

namespace SiesaAgents.UnitTests.Infrastructure;

/// <summary>
/// Story 2.1 — Client List & Search (Epic 2)
/// ATDD Unit Tests — RED phase. Generated by testarch-atdd.
///
/// Failing until DEV creates per AC-2.1.f (Task 1):
///   - <c>SiesaAgents.Infrastructure.Data.Configurations.ClienteConfiguration</c>
///   - <c>AppDbContext.Clientes</c> DbSet
///   - <c>OnModelCreating</c> applies the configuration BEFORE <c>ApplySnakeCaseNaming()</c>
///
/// Approach: spin up an in-memory <see cref="AppDbContext"/> so the real
/// <c>OnModelCreating</c> runs (including <c>ApplyConfigurationsFromAssembly</c> +
/// <c>ApplySnakeCaseNaming</c>); then inspect the materialized model.
/// This pattern matches the existing MigrationCreatesDbTests style.
///
/// Expected RED failure:
///   "The type or namespace name 'ClienteConfiguration' could not be found"
///   or "AppDbContext does not contain a definition for 'Clientes'".
/// </summary>
public class ClienteConfigurationTests
{
    private static AppDbContext CreateContext()
    {
        var options = new DbContextOptionsBuilder<AppDbContext>()
            .UseInMemoryDatabase($"clientes-cfg-tests-{System.Guid.NewGuid()}")
            .Options;
        return new AppDbContext(options);
    }

    [Fact]
    public void ClienteEntity_IsRegistered_InDbContextModel()
    {
        // GIVEN: a freshly-built AppDbContext
        using var ctx = CreateContext();

        // WHEN: we inspect the EF Core model
        var entityType = ctx.Model.FindEntityType(typeof(ClienteEntity));

        // THEN: the ClienteEntity is part of the model (DbSet wired + configuration applied)
        Assert.NotNull(entityType);
    }

    [Fact]
    public void ClienteEntity_TableName_IsSnakeCase_Clientes()
    {
        // GIVEN
        using var ctx = CreateContext();
        var entityType = ctx.Model.FindEntityType(typeof(ClienteEntity));

        // THEN: the table is named "clientes" (snake_case extension lowercased it)
        Assert.NotNull(entityType);
        Assert.Equal("clientes", entityType!.GetTableName());
    }

    [Fact]
    public void Nit_HasUniqueIndex_NamedUkClientesNit()
    {
        // GIVEN
        using var ctx = CreateContext();
        var entityType = ctx.Model.FindEntityType(typeof(ClienteEntity));
        Assert.NotNull(entityType);

        // WHEN: we look for an index targeting the Nit column
        var nitIndex = entityType!.GetIndexes()
            .FirstOrDefault(i => i.Properties.Any(p => p.Name == nameof(ClienteEntity.Nit)));

        // THEN: a unique index exists and is named "uk_clientes_nit" (snake_case preserved
        //       because the configuration set HasDatabaseName("uk_clientes_nit") explicitly).
        Assert.NotNull(nitIndex);
        Assert.True(nitIndex!.IsUnique, "Expected uniqueness constraint on Nit.");
        Assert.Equal("uk_clientes_nit", nitIndex.GetDatabaseName());
    }

    [Fact]
    public void Nombre_IsRequired_WithMaxLength200()
    {
        // GIVEN
        using var ctx = CreateContext();
        var entityType = ctx.Model.FindEntityType(typeof(ClienteEntity));
        Assert.NotNull(entityType);

        var nombre = entityType!.FindProperty(nameof(ClienteEntity.Nombre));
        Assert.NotNull(nombre);

        // THEN
        Assert.False(nombre!.IsNullable);
        Assert.Equal(200, nombre.GetMaxLength());
    }

    [Fact]
    public void Nit_IsRequired_WithMaxLength50()
    {
        // GIVEN
        using var ctx = CreateContext();
        var entityType = ctx.Model.FindEntityType(typeof(ClienteEntity));
        Assert.NotNull(entityType);

        var nit = entityType!.FindProperty(nameof(ClienteEntity.Nit));
        Assert.NotNull(nit);

        // THEN
        Assert.False(nit!.IsNullable);
        Assert.Equal(50, nit.GetMaxLength());
    }

    [Fact]
    public void Telefono_IsRequired_WithMaxLength50()
    {
        // GIVEN
        using var ctx = CreateContext();
        var entityType = ctx.Model.FindEntityType(typeof(ClienteEntity));
        Assert.NotNull(entityType);
        var telefono = entityType!.FindProperty(nameof(ClienteEntity.Telefono));

        // THEN
        Assert.NotNull(telefono);
        Assert.False(telefono!.IsNullable);
        Assert.Equal(50, telefono.GetMaxLength());
    }

    [Fact]
    public void Ciudad_IsRequired_WithMaxLength100()
    {
        // GIVEN
        using var ctx = CreateContext();
        var entityType = ctx.Model.FindEntityType(typeof(ClienteEntity));
        Assert.NotNull(entityType);
        var ciudad = entityType!.FindProperty(nameof(ClienteEntity.Ciudad));

        // THEN
        Assert.NotNull(ciudad);
        Assert.False(ciudad!.IsNullable);
        Assert.Equal(100, ciudad.GetMaxLength());
    }

    [Fact]
    public void IdColumn_IsSnakeCase_id()
    {
        // GIVEN
        using var ctx = CreateContext();
        var entityType = ctx.Model.FindEntityType(typeof(ClienteEntity));
        Assert.NotNull(entityType);

        // WHEN
        var id = entityType!.FindProperty(nameof(ClienteEntity.Id));
        Assert.NotNull(id);

        // THEN: ApplySnakeCaseNaming() lowercased the column to "id"
        var columnName = id!.GetColumnName();
        Assert.Equal("id", columnName);
    }

    [Fact]
    public void CreatedAtColumn_IsSnakeCase_created_at()
    {
        // GIVEN
        using var ctx = CreateContext();
        var entityType = ctx.Model.FindEntityType(typeof(ClienteEntity));
        Assert.NotNull(entityType);

        // WHEN
        var createdAt = entityType!.FindProperty(nameof(ClienteEntity.CreatedAt));
        Assert.NotNull(createdAt);

        // THEN
        Assert.Equal("created_at", createdAt!.GetColumnName());
    }
}
