using Xunit;

namespace SiesaAgents.UnitTests.Data;

/// <summary>
/// Architecture guard for Story 1.3 AC #1, AC #2 — the migrations folder is
/// generated by `dotnet ef migrations add InitialCreate` and MUST conform to:
///
///   - lives under <c>SiesaAgents.Infrastructure/Data/Migrations/</c>
///   - contains EXACTLY one <c>*_InitialCreate.cs</c> + its <c>.Designer.cs</c>
///   - contains <c>AppDbContextModelSnapshot.cs</c>
///   - the <c>Up()</c> and <c>Down()</c> bodies are empty (no <c>CreateTable</c>)
///
/// This does NOT touch a database (so it is NOT tagged Category=Db). It parses
/// the on-disk migration files as text — the DB-touching coverage is QA-owned
/// <see cref="SiesaAgents.IntegrationTests.MigrationCreatesDbTests"/>.
///
/// Priority: P1 — High (closes the scope-note gap "no domain tables in 1.3").
/// </summary>
public class MigrationsStructureTests
{
    private static string FindBackendRoot()
    {
        var assemblyLocation = typeof(MigrationsStructureTests).Assembly.Location;
        var dir = new DirectoryInfo(Path.GetDirectoryName(assemblyLocation)!);
        while (dir is not null && !File.Exists(Path.Combine(dir.FullName, "SiesaAgents.slnx")))
        {
            dir = dir.Parent;
        }
        Assert.NotNull(dir);
        return dir!.FullName;
    }

    private static string MigrationsFolder() =>
        Path.Combine(
            FindBackendRoot(),
            "src",
            "SiesaAgents.Infrastructure",
            "Data",
            "Migrations");

    [Fact]
    public void MigrationsFolder_Exists_UnderInfrastructureData()
    {
        // GIVEN: Story 1.3 mandates `Data/Migrations/` inside SiesaAgents.Infrastructure
        var folder = MigrationsFolder();

        // WHEN / THEN: the folder must exist on disk (Task 4 deliverable)
        Assert.True(Directory.Exists(folder),
            $"Expected migrations folder at {folder} — generated by `dotnet ef migrations add InitialCreate --output-dir Data/Migrations`.");
    }

    [Fact]
    public void MigrationsFolder_ContainsExactlyOneInitialCreateMigration()
    {
        // GIVEN: the migrations folder
        var folder = MigrationsFolder();
        Assert.True(Directory.Exists(folder));

        // WHEN: we enumerate files matching the `{timestamp}_InitialCreate.cs` pattern
        //       (exclude .Designer.cs so we count the migration class only ONCE).
        var initialMigrations = Directory
            .GetFiles(folder, "*_InitialCreate.cs", SearchOption.TopDirectoryOnly)
            .Where(p => !p.EndsWith(".Designer.cs", StringComparison.OrdinalIgnoreCase))
            .ToList();

        // THEN: exactly one InitialCreate migration exists (regenerating without removing
        //       the old one is a common foot-gun this guards against).
        Assert.Single(initialMigrations);
    }

    [Fact]
    public void MigrationsFolder_ContainsDesignerAndModelSnapshot()
    {
        // GIVEN: the migrations folder
        var folder = MigrationsFolder();
        Assert.True(Directory.Exists(folder));

        // WHEN: we look for the EF Core companion files
        var hasDesigner = Directory
            .GetFiles(folder, "*_InitialCreate.Designer.cs", SearchOption.TopDirectoryOnly)
            .Any();
        var hasSnapshot = File.Exists(Path.Combine(folder, "AppDbContextModelSnapshot.cs"));

        // THEN: both must exist — required by the EF Core migration toolchain.
        Assert.True(hasDesigner, "Expected at least one `*_InitialCreate.Designer.cs` file.");
        Assert.True(hasSnapshot, "Expected `AppDbContextModelSnapshot.cs` in the migrations folder.");
    }

    [Fact]
    public void InitialCreateMigration_UpAndDownBodies_AreEmpty_NoCreateTableCalls()
    {
        // GIVEN: the single InitialCreate migration file
        var folder = MigrationsFolder();
        var initialMigration = Directory
            .GetFiles(folder, "*_InitialCreate.cs", SearchOption.TopDirectoryOnly)
            .Single(p => !p.EndsWith(".Designer.cs", StringComparison.OrdinalIgnoreCase));

        // WHEN: we read its contents
        var contents = File.ReadAllText(initialMigration);

        // THEN: no `CreateTable` calls — Story 1.3 scope-note explicitly forbids
        //       `clientes`, `contactos`, or any domain table in the initial migration.
        Assert.DoesNotContain("CreateTable", contents);
        Assert.DoesNotContain("clientes", contents, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("contactos", contents, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void ModelSnapshot_TargetsAppDbContext_NotADifferentContext()
    {
        // GIVEN: the model snapshot file
        var snapshot = Path.Combine(MigrationsFolder(), "AppDbContextModelSnapshot.cs");
        Assert.True(File.Exists(snapshot));

        // WHEN: we read its contents
        var contents = File.ReadAllText(snapshot);

        // THEN: the snapshot is bound to AppDbContext (the only DbContext in this story).
        //       Regenerating against a different context would shift the namespace —
        //       this catches that drift before it hits CI.
        Assert.Contains("AppDbContext", contents);
        Assert.Contains("SiesaAgents.Infrastructure.Data", contents);
    }
}
