import { render, screen, waitFor, fireEvent } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { createElement } from 'react';
import { http, HttpResponse } from 'msw';
import { setupServer } from 'msw/node';
import { beforeAll, afterAll, afterEach, describe, it, expect, vi } from 'vitest';
import { ClienteListPanel } from './ClienteListPanel';
import type { Cliente } from '../domain/Cliente';

// Generate 500 mock client records for performance test
function generateMockClientes(count: number): Cliente[] {
  return Array.from({ length: count }, (_, i) => ({
    id: `id-${i}`,
    nombre: `Empresa ${i}`,
    nit: `90000${i}-${i % 10}`,
    telefono: `60100${i}`,
    ciudad: 'Bogotá',
    createdAt: new Date(2026, 0, 1).toISOString(),
    updatedAt: new Date(2026, 0, 1).toISOString(),
  }));
}

const server = setupServer();

beforeAll(() => server.listen());
afterEach(() => server.resetHandlers());
afterAll(() => server.close());

function renderWithQuery(ui: React.ReactElement) {
  const queryClient = new QueryClient({
    defaultOptions: { queries: { retry: false } },
  });
  return render(
    createElement(QueryClientProvider, { client: queryClient }, ui)
  );
}

// TC-E2-P1-05: Filter renders within 1000ms with 500 mock records
describe('ClienteListPanel — TC-E2-P1-05: filter performance with 500 records', () => {
  it('filters 500 records within 1000ms', async () => {
    const mocks = generateMockClientes(500);
    server.use(
      http.get('*/api/v1/clientes', () => HttpResponse.json(mocks))
    );

    renderWithQuery(<ClienteListPanel />);

    // Wait for list to load
    await waitFor(() => expect(screen.getByPlaceholderText('Buscar por nombre o NIT/RUC…')).toBeInTheDocument(), {
      timeout: 2000,
    });

    const start = performance.now();
    const searchInput = screen.getByPlaceholderText('Buscar por nombre o NIT/RUC…');
    fireEvent.change(searchInput, { target: { value: 'Empresa 1' } });

    await waitFor(() => {
      // Should show items matching "Empresa 1"
      const items = screen.getAllByRole('button', { name: /Empresa 1/ });
      expect(items.length).toBeGreaterThan(0);
    });

    const elapsed = performance.now() - start;
    expect(elapsed).toBeLessThan(1000);
  });
});

// TC-E2-P1-06: Empty state displayed when server returns []
describe('ClienteListPanel — TC-E2-P1-06: empty state', () => {
  it('shows empty state when no clients are returned', async () => {
    server.use(
      http.get('*/api/v1/clientes', () => HttpResponse.json([]))
    );

    renderWithQuery(<ClienteListPanel />);

    await waitFor(() =>
      expect(screen.getByText('No hay clientes registrados')).toBeInTheDocument()
    );
  });
});

// TC-E2-P1-07: ErrorPanel with "Reintentar" shown on 500 → retry → success
describe('ClienteListPanel — TC-E2-P1-07: error state and retry', () => {
  it('shows error panel on fetch failure and retries on button click', async () => {
    let callCount = 0;
    const mockData: Cliente[] = [
      {
        id: '1',
        nombre: 'Empresa Alpha',
        nit: '900123456-1',
        telefono: '6014567890',
        ciudad: 'Bogotá',
        createdAt: '2026-01-01T00:00:00Z',
        updatedAt: '2026-01-01T00:00:00Z',
      },
    ];

    server.use(
      http.get('*/api/v1/clientes', () => {
        callCount++;
        if (callCount === 1) {
          return HttpResponse.json({ error: 'Internal Server Error' }, { status: 500 });
        }
        return HttpResponse.json(mockData);
      })
    );

    renderWithQuery(<ClienteListPanel />);

    // Wait for error panel
    await waitFor(() =>
      expect(screen.getByText('Error al cargar los clientes')).toBeInTheDocument()
    );

    // Click retry button
    const retryButton = screen.getByRole('button', { name: 'Reintentar' });
    expect(retryButton).toBeInTheDocument();
    fireEvent.click(retryButton);

    // After retry, list should appear
    await waitFor(() =>
      expect(screen.getByText('Empresa Alpha')).toBeInTheDocument()
    );
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// EXPANDED COVERAGE — Edge cases NOT in ATDD tests
// Generated by TEA testarch-automate (BMad-Integrated mode)
// ─────────────────────────────────────────────────────────────────────────────

// [P1] Loading skeleton state
describe('ClienteListPanel — loading skeleton', () => {
  it('[P1] should render exactly 5 skeleton rows while data is loading', async () => {
    // GIVEN: A slow API (never responds during this test)
    server.use(
      http.get('*/api/v1/clientes', async () => {
        // Delay forever — we only care about the loading state
        await new Promise(() => {});
        return HttpResponse.json([]);
      })
    );

    // WHEN: Component is rendered and data has not arrived yet
    renderWithQuery(<ClienteListPanel />);

    // THEN: The loading container is shown with aria-label "Cargando clientes"
    const loadingContainer = screen.getByLabelText('Cargando clientes');
    expect(loadingContainer).toBeInTheDocument();
  });

  it('[P1] should NOT show the client list while loading', async () => {
    // GIVEN: A slow API
    server.use(
      http.get('*/api/v1/clientes', async () => {
        await new Promise(() => {});
        return HttpResponse.json([]);
      })
    );

    // WHEN: Component is rendered in loading state
    renderWithQuery(<ClienteListPanel />);

    // THEN: The client list is not visible
    expect(screen.queryByTestId('cliente-list')).not.toBeInTheDocument();
  });

  it('[P1] should NOT show the empty state while loading', async () => {
    // GIVEN: A slow API
    server.use(
      http.get('*/api/v1/clientes', async () => {
        await new Promise(() => {});
        return HttpResponse.json([]);
      })
    );

    // WHEN: Component is rendered in loading state
    renderWithQuery(<ClienteListPanel />);

    // THEN: EmptyState is not visible during loading
    expect(screen.queryByTestId('empty-state')).not.toBeInTheDocument();
  });

  it('[P1] should NOT show the error panel while loading', async () => {
    // GIVEN: A slow API (not a failed one)
    server.use(
      http.get('*/api/v1/clientes', async () => {
        await new Promise(() => {});
        return HttpResponse.json([]);
      })
    );

    // WHEN: Component is rendered before fetch completes
    renderWithQuery(<ClienteListPanel />);

    // THEN: Error panel is not visible during loading
    expect(screen.queryByTestId('error-panel')).not.toBeInTheDocument();
  });
});

// [P1] Search input edge cases
describe('ClienteListPanel — search edge cases', () => {
  const twoClients: Cliente[] = [
    {
      id: 'a1',
      nombre: 'Empresa Alpha',
      nit: '900111111-1',
      telefono: '6014567890',
      ciudad: 'Bogotá',
      createdAt: '2026-01-01T00:00:00Z',
      updatedAt: '2026-01-01T00:00:00Z',
    },
    {
      id: 'b2',
      nombre: 'Beta Corp',
      nit: '900222222-2',
      telefono: '6024567890',
      ciudad: 'Medellín',
      createdAt: '2026-01-01T00:00:00Z',
      updatedAt: '2026-01-01T00:00:00Z',
    },
  ];

  it('[P1] should show all clients when search input is cleared after typing', async () => {
    // GIVEN: Two clients loaded, user has typed a search term
    server.use(http.get('*/api/v1/clientes', () => HttpResponse.json(twoClients)));
    renderWithQuery(<ClienteListPanel />);

    const searchInput = await screen.findByPlaceholderText('Buscar por nombre o NIT/RUC…');

    // Type a filter
    fireEvent.change(searchInput, { target: { value: 'Alpha' } });
    await waitFor(() =>
      expect(screen.queryByText('Beta Corp')).not.toBeInTheDocument()
    );

    // WHEN: User clears the search input
    fireEvent.change(searchInput, { target: { value: '' } });

    // THEN: Both clients are visible again
    await waitFor(() => {
      expect(screen.getByText('Empresa Alpha')).toBeInTheDocument();
      expect(screen.getByText('Beta Corp')).toBeInTheDocument();
    });
  });

  it('[P1] should show empty state when search produces no matches', async () => {
    // GIVEN: Two clients loaded
    server.use(http.get('*/api/v1/clientes', () => HttpResponse.json(twoClients)));
    renderWithQuery(<ClienteListPanel />);

    // Wait for data to load
    await screen.findByText('Empresa Alpha');

    // WHEN: User types a search term that matches no client
    const searchInput = screen.getByPlaceholderText('Buscar por nombre o NIT/RUC…');
    fireEvent.change(searchInput, { target: { value: 'XYZ NO MATCH' } });

    // THEN: EmptyState is displayed (no results after filter)
    await waitFor(() =>
      expect(screen.getByTestId('empty-state')).toBeInTheDocument()
    );

    // AND: No client list items are rendered
    expect(screen.queryByTestId('cliente-list')).not.toBeInTheDocument();
  });

  it('[P1] should filter case-insensitively (lowercase query matches uppercase nombre)', async () => {
    // GIVEN: Client with uppercase nombre
    const clients: Cliente[] = [
      {
        id: 'c3',
        nombre: 'EMPRESA MAYÚSCULAS',
        nit: '900333333-3',
        telefono: '6034567890',
        ciudad: 'Cali',
        createdAt: '2026-01-01T00:00:00Z',
        updatedAt: '2026-01-01T00:00:00Z',
      },
    ];
    server.use(http.get('*/api/v1/clientes', () => HttpResponse.json(clients)));
    renderWithQuery(<ClienteListPanel />);

    await screen.findByText('EMPRESA MAYÚSCULAS');

    // WHEN: User types lowercase
    const searchInput = screen.getByPlaceholderText('Buscar por nombre o NIT/RUC…');
    fireEvent.change(searchInput, { target: { value: 'empresa mayúsculas' } });

    // THEN: The client is still visible (case-insensitive filter)
    await waitFor(() =>
      expect(screen.getByText('EMPRESA MAYÚSCULAS')).toBeInTheDocument()
    );
  });

  it('[P2] should treat whitespace-only search as no filter (shows all clients)', async () => {
    // GIVEN: Two clients loaded
    server.use(http.get('*/api/v1/clientes', () => HttpResponse.json(twoClients)));
    renderWithQuery(<ClienteListPanel />);

    await screen.findByText('Empresa Alpha');

    // WHEN: User types only spaces in the search field
    const searchInput = screen.getByPlaceholderText('Buscar por nombre o NIT/RUC…');
    fireEvent.change(searchInput, { target: { value: '   ' } });

    // THEN: All clients remain visible (spaces trim to empty string)
    await waitFor(() => {
      expect(screen.getByText('Empresa Alpha')).toBeInTheDocument();
      expect(screen.getByText('Beta Corp')).toBeInTheDocument();
    });
  });

  it('[P2] should filter by partial NIT match', async () => {
    // GIVEN: Two clients, one with NIT containing "111"
    server.use(http.get('*/api/v1/clientes', () => HttpResponse.json(twoClients)));
    renderWithQuery(<ClienteListPanel />);

    await screen.findByText('Empresa Alpha');

    // WHEN: User types partial NIT "111" which matches only Alpha
    const searchInput = screen.getByPlaceholderText('Buscar por nombre o NIT/RUC…');
    fireEvent.change(searchInput, { target: { value: '111' } });

    // THEN: Only the matching client is shown
    await waitFor(() => {
      expect(screen.getByText('Empresa Alpha')).toBeInTheDocument();
      expect(screen.queryByText('Beta Corp')).not.toBeInTheDocument();
    });
  });

  it('[P2] should show multiple clients when search matches more than one', async () => {
    // GIVEN: Both clients share "Corp" in their names
    const sharedClients: Cliente[] = [
      { id: 'd1', nombre: 'Alpha Corp', nit: '900444444-1', telefono: '601', ciudad: 'Bogotá', createdAt: '2026-01-01T00:00:00Z', updatedAt: '2026-01-01T00:00:00Z' },
      { id: 'd2', nombre: 'Beta Corp', nit: '900555555-2', telefono: '602', ciudad: 'Cali', createdAt: '2026-01-01T00:00:00Z', updatedAt: '2026-01-01T00:00:00Z' },
    ];
    server.use(http.get('*/api/v1/clientes', () => HttpResponse.json(sharedClients)));
    renderWithQuery(<ClienteListPanel />);

    await screen.findByText('Alpha Corp');

    // WHEN: User types "Corp" which matches both
    const searchInput = screen.getByPlaceholderText('Buscar por nombre o NIT/RUC…');
    fireEvent.change(searchInput, { target: { value: 'Corp' } });

    // THEN: Both clients are visible
    await waitFor(() => {
      expect(screen.getByText('Alpha Corp')).toBeInTheDocument();
      expect(screen.getByText('Beta Corp')).toBeInTheDocument();
    });
  });
});

// [P1] Successful load state — rendered list and search input
describe('ClienteListPanel — successful load rendering', () => {
  it('[P1] should render the search input with correct placeholder text after load', async () => {
    // GIVEN: API returns a client
    server.use(
      http.get('*/api/v1/clientes', () =>
        HttpResponse.json([
          { id: 'z1', nombre: 'Empresa Test', nit: '900000000-1', telefono: '600', ciudad: 'Bogotá', createdAt: '2026-01-01T00:00:00Z', updatedAt: '2026-01-01T00:00:00Z' },
        ])
      )
    );
    renderWithQuery(<ClienteListPanel />);

    // WHEN: Data loads
    const searchInput = await screen.findByPlaceholderText('Buscar por nombre o NIT/RUC…');

    // THEN: The search input is present with the correct Spanish placeholder
    expect(searchInput).toBeInTheDocument();
  });

  it('[P1] should render the search input with data-testid="search-input"', async () => {
    // GIVEN: API returns a client
    server.use(
      http.get('*/api/v1/clientes', () => HttpResponse.json([
        { id: 'z2', nombre: 'Empresa Test', nit: '900000000-2', telefono: '600', ciudad: 'Bogotá', createdAt: '2026-01-01T00:00:00Z', updatedAt: '2026-01-01T00:00:00Z' },
      ]))
    );
    renderWithQuery(<ClienteListPanel />);

    // WHEN: Component renders
    await screen.findByTestId('search-input');

    // THEN: data-testid is present for E2E selectors
    expect(screen.getByTestId('search-input')).toBeInTheDocument();
  });

  it('[P1] should NOT show empty state or error panel when clients are loaded', async () => {
    // GIVEN: API returns clients
    server.use(
      http.get('*/api/v1/clientes', () => HttpResponse.json([
        { id: 'z3', nombre: 'Empresa Con Datos', nit: '900000000-3', telefono: '600', ciudad: 'Bogotá', createdAt: '2026-01-01T00:00:00Z', updatedAt: '2026-01-01T00:00:00Z' },
      ]))
    );
    renderWithQuery(<ClienteListPanel />);

    // WHEN: Data loads successfully
    await screen.findByText('Empresa Con Datos');

    // THEN: No error or empty state is shown
    expect(screen.queryByTestId('empty-state')).not.toBeInTheDocument();
    expect(screen.queryByTestId('error-panel')).not.toBeInTheDocument();
  });
});

// [P2] Error state does not render list or empty state
describe('ClienteListPanel — error state isolation', () => {
  it('[P2] should NOT show the empty state when error panel is visible', async () => {
    // GIVEN: Backend returns 500
    server.use(
      http.get('*/api/v1/clientes', () =>
        HttpResponse.json({ error: 'Server error' }, { status: 500 })
      )
    );
    renderWithQuery(<ClienteListPanel />);

    // WHEN: Error panel appears
    await waitFor(() =>
      expect(screen.getByTestId('error-panel')).toBeInTheDocument()
    );

    // THEN: Empty state is not shown simultaneously
    expect(screen.queryByTestId('empty-state')).not.toBeInTheDocument();
  });

  it('[P2] should NOT show the client list when error panel is visible', async () => {
    // GIVEN: Backend returns 500
    server.use(
      http.get('*/api/v1/clientes', () =>
        HttpResponse.json({ error: 'Server error' }, { status: 500 })
      )
    );
    renderWithQuery(<ClienteListPanel />);

    // WHEN: Error panel appears
    await waitFor(() =>
      expect(screen.getByTestId('error-panel')).toBeInTheDocument()
    );

    // THEN: Client list is not rendered
    expect(screen.queryByTestId('cliente-list')).not.toBeInTheDocument();
  });
});
