/**
 * Story 2.1 — Client List & Search (Epic 2)
 *
 * ATDD Performance Test — RED Phase (TC-E2-P0-06 / NFR1)
 * Generated by testarch-atdd.
 *
 * NFR1 mandates keystroke-to-paint < 1 s @ 500 records. We assert the much
 * tighter contract from the test design: p95 render commit < 200 ms across
 * 10 iterations of typing "ACM", AND zero additional MSW requests during
 * typing (entire dataset is pre-warmed once in the `['clientes']` cache).
 *
 * Strategy (per Task 8 / Dev Notes "Why Search Is Client-Side"):
 *   1. Deterministically build 500 fixtures via makeClientes(500, 20260601).
 *   2. Create a QueryClient and pre-warm `['clientes']` with the fixtures.
 *   3. Render ClienteListView wrapped in QueryClientProvider.
 *   4. Install an MSW request spy on `/api/v1/clientes` (must record 0 hits).
 *   5. Type "ACM" 10 times around `performance.now()` measurements.
 *   6. Assert p95(deltas) < 200 ms AND spy.count === 0.
 *
 * Expected RED failure reasons:
 *   - "Cannot find module './ClienteListView'" (component missing)
 *   - downstream missing-module errors for useClientes / shared components
 */

import { describe, it, expect, afterEach } from 'vitest'
import { cleanup, screen, fireEvent, act } from '@testing-library/react'
import { QueryClient } from '@tanstack/react-query'
import { http, HttpResponse } from 'msw'
import { renderWithQuery } from '@/test/utils/renderWithQuery'
import { server } from '@/test/setup'
import { makeClientes } from '../application/__fixtures__/clientes.fixtures'
import { ClienteListView } from './ClienteListView'

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

function p95(deltas: number[]): number {
  if (deltas.length === 0) return 0
  const sorted = [...deltas].sort((a, b) => a - b)
  const idx = Math.min(sorted.length - 1, Math.ceil(0.95 * sorted.length) - 1)
  return sorted[idx]
}

describe('ClienteListView — TC-E2-P0-06 NFR1 perf @ 500 records', () => {
  afterEach(() => cleanup())

  it('[P0] p95 keystroke-render < 200 ms AND zero network requests during typing', async () => {
    // GIVEN: a deterministic 500-record dataset preloaded into the cache.
    const fixtures = makeClientes(500, 20260601)

    const queryClient = new QueryClient({
      defaultOptions: { queries: { retry: false, staleTime: Infinity, gcTime: Infinity } },
    })
    queryClient.setQueryData(['clientes'], fixtures)

    // AND an MSW spy that counts ANY hit to the endpoint during typing.
    let networkHits = 0
    const BASE = import.meta.env.VITE_API_URL ?? 'http://localhost:5000'
    server.use(
      http.get(`${BASE}/api/v1/clientes`, () => {
        networkHits += 1
        return HttpResponse.json(fixtures)
      }),
    )

    // WHEN: the view is rendered with the pre-warmed cache.
    renderWithQuery(
      <ClienteListView
        searchQuery=""
        onSearchChange={() => {}}
        selectedClienteId={null}
        onSelectCliente={() => {}}
      />,
      { queryClient },
    )

    const input = await screen.findByRole('searchbox', { name: /buscar cliente/i })

    // Reset the spy AFTER the initial render so we only measure typing.
    networkHits = 0

    // WHEN: the user types "ACM" 10 times, measuring render commit each time.
    const deltas: number[] = []
    for (let i = 0; i < 10; i++) {
      const start = performance.now()
      await act(async () => {
        fireEvent.change(input, { target: { value: `ACM${i}` } })
      })
      const end = performance.now()
      deltas.push(end - start)
    }

    // THEN: p95 of the render-commit deltas is under the 200 ms ceiling
    expect(p95(deltas)).toBeLessThan(200)

    // AND: NO additional network requests fired during typing (search is 100 % client-side)
    expect(networkHits).toBe(0)
  })
})
