/**
 * Story 2.1 — Client List & Search (Epic 2)
 *
 * ATDD Component Tests — RED Phase (Presentation orchestration)
 * Generated by testarch-atdd. Failing until DEV implements:
 *   - `ClienteListView.tsx` (AC-2.1.h / Task 7)
 *   - `useClientes` hook (AC-2.1.g / Task 5)
 *   - `EmptyState` + `ErrorPanel` + `ClientListItem` (AC-2.1.c, .d, .h / Task 6)
 *
 * Test mapping:
 *   - TC-E2-P1-01 — 280 px panel + Nombre + NIT visible
 *   - TC-E2-P1-02 — Dual search (Nombre OR NIT, diacritic-insensitive)
 *   - TC-E2-P1-03 — EmptyState when MSW returns []
 *   - TC-E2-P1-04 — ErrorPanel + Reintentar on 500; Reintentar re-fetches success
 *
 * Network-first pattern:
 *   - MSW handlers are registered via `server.use(...)` BEFORE render
 *     (the route component mounts → `useClientes` queryFn → Axios → MSW intercept).
 *   - Per-test cleanup is handled by the global setup.ts `afterEach`.
 *
 * Expected RED failure reasons:
 *   - "Cannot find module './ClienteListView'" (presentation file missing)
 *   - "Cannot find module '../application/useClientes'" (hook missing)
 *   - downstream missing-module errors for shared components
 */

import { describe, it, expect, afterEach } from 'vitest'
import { cleanup, screen, fireEvent, waitFor, within } from '@testing-library/react'
import { renderWithQuery } from '@/test/utils/renderWithQuery'
import { server } from '@/test/setup'
import {
  clientesSuccessEmpty,
  clientesSuccessThree,
  clientesErrorThenSuccess,
} from '@/test/handlers/clientes.handlers'
import { THREE_CLIENTES } from '../application/__fixtures__/clientes.fixtures'
import { ClienteListView } from './ClienteListView'

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

function renderView(initialQuery = '') {
  const props = {
    searchQuery: initialQuery,
    onSearchChange: () => {},
    selectedClienteId: null,
    onSelectCliente: () => {},
  }
  return renderWithQuery(<ClienteListView {...props} />)
}

describe('ClienteListView — orchestration of states (Story 2.1)', () => {
  afterEach(() => cleanup())

  // ───────────────────────────── TC-E2-P1-01 ─────────────────────────────
  describe('TC-E2-P1-01 — 280 px panel + Nombre + NIT visible', () => {
    it('[P1] renders the panel root with the w-[280px] Tailwind class on lg viewports', async () => {
      // GIVEN: backend returns 3 fixtures
      server.use(clientesSuccessThree(THREE_CLIENTES))

      // WHEN: the route is rendered
      renderView()

      // THEN: the asynchronously-fetched list materializes AND the panel root
      //       carries the canonical 280-px width class.
      await screen.findByText('Acme S.A.')
      const panel = screen.getByRole('complementary', { name: /lista de clientes/i })
      expect(panel.className).toMatch(/\bw-\[280px\]/)
    })

    it('[P1] renders one list item per cliente showing nombre + nit', async () => {
      // GIVEN: 3 fixtures
      server.use(clientesSuccessThree(THREE_CLIENTES))

      // WHEN
      renderView()

      // THEN: every cliente's nombre AND nit appear
      for (const c of THREE_CLIENTES) {
        await screen.findByText(c.nombre)
        expect(screen.getByText(c.nit)).toBeInTheDocument()
      }
    })
  })

  // ───────────────────────────── TC-E2-P1-02 ─────────────────────────────
  describe('TC-E2-P1-02 — Dual search (Nombre OR NIT, diacritic-insensitive)', () => {
    it('[P1] typing "ACM" filters to just Acme (nombre match, case-insensitive)', async () => {
      // GIVEN: list is loaded with 3 fixtures (Acme, Beta, José)
      server.use(clientesSuccessThree(THREE_CLIENTES))
      renderView()
      await screen.findByText('Acme S.A.')

      // WHEN: the user types "ACM"
      const input = screen.getByRole('searchbox', { name: /buscar cliente/i })
      fireEvent.change(input, { target: { value: 'ACM' } })

      // THEN: Acme is visible, Beta and José are not
      await waitFor(() => expect(screen.getByText('Acme S.A.')).toBeInTheDocument())
      expect(screen.queryByText('Beta Corp')).toBeNull()
      expect(screen.queryByText(/José Pérez/)).toBeNull()
    })

    it('[P1] typing "900" filters to just Acme via NIT', async () => {
      // GIVEN
      server.use(clientesSuccessThree(THREE_CLIENTES))
      renderView()
      await screen.findByText('Acme S.A.')

      // WHEN: user types a partial NIT
      const input = screen.getByRole('searchbox', { name: /buscar cliente/i })
      fireEvent.change(input, { target: { value: '900' } })

      // THEN: Acme matches via NIT; the others are filtered out
      await waitFor(() => expect(screen.getByText('Acme S.A.')).toBeInTheDocument())
      expect(screen.queryByText('Beta Corp')).toBeNull()
    })

    it('[P1] typing "jose" matches "José Pérez" (diacritic-insensitive)', async () => {
      // GIVEN
      server.use(clientesSuccessThree(THREE_CLIENTES))
      renderView()
      await screen.findByText(/José Pérez/)

      // WHEN
      const input = screen.getByRole('searchbox', { name: /buscar cliente/i })
      fireEvent.change(input, { target: { value: 'jose' } })

      // THEN: José is still rendered (NFD + strip diacritics on both sides)
      await waitFor(() => expect(screen.getByText(/José Pérez/)).toBeInTheDocument())
      expect(screen.queryByText('Acme S.A.')).toBeNull()
    })
  })

  // ───────────────────────────── TC-E2-P1-03 ─────────────────────────────
  describe('TC-E2-P1-03 — EmptyState when zero clients', () => {
    it('[P1] renders the EmptyState with Spanish copy + "Nuevo cliente" CTA when API returns []', async () => {
      // GIVEN: backend returns an empty array
      server.use(clientesSuccessEmpty)

      // WHEN
      renderView()

      // THEN: the EmptyState test id appears and the Spanish copy + CTA are visible.
      //       NO list items rendered.
      const empty = await screen.findByTestId('empty-state')
      expect(within(empty).getByText(/aún no hay clientes/i)).toBeInTheDocument()
      expect(within(empty).getByRole('button', { name: /nuevo cliente/i })).toBeInTheDocument()
    })
  })

  // ───────────────────────────── TC-E2-P1-04 ─────────────────────────────
  describe('TC-E2-P1-04 — ErrorPanel + Reintentar (NFR6)', () => {
    it('[P1] renders the ErrorPanel when the initial fetch fails with 500', async () => {
      // GIVEN: first request returns 500
      server.use(clientesErrorThenSuccess(THREE_CLIENTES))

      // WHEN
      renderView()

      // THEN: the ErrorPanel appears with the canned Spanish copy and Reintentar CTA
      const panel = await screen.findByTestId('error-panel')
      expect(within(panel).getByText(/no se pudo cargar la lista de clientes/i)).toBeInTheDocument()
      expect(within(panel).getByRole('button', { name: /^reintentar$/i })).toBeInTheDocument()
    })

    it('[P1] NFR6 — does NOT leak Problem Details `detail` or stack trace text', async () => {
      // GIVEN: 500 + Problem Details body containing a sensitive marker
      server.use(clientesErrorThenSuccess(THREE_CLIENTES))

      // WHEN
      renderView()
      await screen.findByTestId('error-panel')

      // THEN: the sensitive marker NEVER reaches the DOM (NFR6)
      const SENSITIVE = 'INTERNAL_DB_LEAK_SENSITIVE_STACK_TRACE'
      expect(document.body.textContent ?? '').not.toContain(SENSITIVE)
    })

    it('[P1] clicking Reintentar refetches and renders the list on success', async () => {
      // GIVEN: first 500, second success
      server.use(clientesErrorThenSuccess(THREE_CLIENTES))
      renderView()
      const panel = await screen.findByTestId('error-panel')

      // WHEN: the user clicks Reintentar
      fireEvent.click(within(panel).getByRole('button', { name: /^reintentar$/i }))

      // THEN: the ErrorPanel disappears and the list materializes
      await waitFor(() => expect(screen.queryByTestId('error-panel')).toBeNull())
      await screen.findByText('Acme S.A.')
    })
  })
})
