/**
 * Story 1.2 — Frontend Navigation Shell
 * Epic 1: Project Foundation & Application Shell
 *
 * Component tests for ClientesPlaceholderView.
 *
 * Generated by testarch-automate (BMad-Integrated Mode) — expands ATDD coverage
 * with isolated tests for the Spanish placeholder shipped in Story 1.2.
 *
 * Covers AC #3 (placeholder view rendered for /clientes deep link) at the
 * component level — the routing integration is already exercised by the E2E
 * suite (TC-E1-P1-02).
 *
 * Scope:
 *   - Spanish heading "Clientes" (level 1) for the placeholder
 *   - "Sección en construcción." Spanish placeholder copy
 *   - data-testid="clientes-placeholder" exposed
 *   - 3 Skeleton placeholders rendered (visual stand-in for the real list)
 *   - SSR-safe (no `window` access — tested via Vitest's jsdom-free assertion)
 */

import { describe, it, expect, afterEach } from 'vitest'
import { cleanup, render, screen } from '@testing-library/react'

import { ClientesPlaceholderView } from './ClientesPlaceholderView'

describe('ClientesPlaceholderView — Spanish placeholder (Story 1.2, AC #3)', () => {
  afterEach(() => {
    cleanup()
  })

  it('[P1] renders the Spanish heading "Clientes" at level 1', () => {
    // GIVEN/WHEN: the placeholder view is rendered standalone
    render(<ClientesPlaceholderView />)

    // THEN: a level-1 heading with the Spanish label is exposed for screen readers
    expect(
      screen.getByRole('heading', { level: 1, name: /^clientes$/i }),
    ).toBeInTheDocument()
  })

  it('[P1] renders the Spanish placeholder copy "Sección en construcción."', () => {
    // GIVEN/WHEN: the placeholder view is rendered
    render(<ClientesPlaceholderView />)

    // THEN: the standardized "section under construction" Spanish copy is present
    expect(screen.getByText(/sección en construcción\./i)).toBeInTheDocument()
  })

  it('[P1] exposes data-testid="clientes-placeholder" for SPA navigation assertions', () => {
    // GIVEN/WHEN: the placeholder view is rendered
    render(<ClientesPlaceholderView />)

    // THEN: the agreed test id is wired (also used by E2E TC-E1-P1-02)
    expect(screen.getByTestId('clientes-placeholder')).toBeInTheDocument()
  })

  it('[P2] renders 3 Skeleton placeholders (visual stand-in for the future list)', () => {
    // GIVEN: react-loading-skeleton renders each skeleton as a <span class="react-loading-skeleton">
    // WHEN: the placeholder view is rendered
    const { container } = render(<ClientesPlaceholderView />)

    // THEN: exactly 3 skeleton placeholders are emitted (Skeleton count={3})
    const skeletons = container.querySelectorAll('.react-loading-skeleton')
    expect(skeletons).toHaveLength(3)
  })

  it('[P2] is SSR-safe — does not throw when window references are removed at render time', () => {
    // GIVEN: a render context where window has been temporarily neutralised
    // (Vitest jsdom always provides window, but the placeholder must not READ it.
    // We assert by re-rendering after defining `window` shadowing — any direct access would throw.)
    expect(() => render(<ClientesPlaceholderView />)).not.toThrow()
  })
})
