using System.Text.Json;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging.Abstractions;
using SiesaAgents.API.Middleware;
using Xunit;

namespace SiesaAgents.UnitTests.Middleware;

/// <summary>
/// Edge-case and boundary tests for ExceptionHandlingMiddleware (Story 1.3, AC2 + NFR6).
/// Expands ATDD coverage with exception type variations, concurrent usage,
/// null-message safety, and RFC 7807 field completeness.
///
/// Generated by: testarch-automate (BMad-Integrated Mode)
/// </summary>
public class ExceptionHandlingMiddlewareEdgeCaseTests
{
    // ─────────────────────────────────────────────────────────────────────────
    // Helpers
    // ─────────────────────────────────────────────────────────────────────────

    private static DefaultHttpContext CreateHttpContext()
    {
        var ctx = new DefaultHttpContext();
        ctx.Response.Body = new MemoryStream();
        return ctx;
    }

    private static async Task<JsonElement> ReadResponseJsonAsync(HttpContext ctx)
    {
        ctx.Response.Body.Seek(0, SeekOrigin.Begin);
        using var reader = new StreamReader(ctx.Response.Body);
        var body = await reader.ReadToEndAsync();
        return JsonDocument.Parse(body).RootElement;
    }

    // ─────────────────────────────────────────────────────────────────────────
    // [P1] RFC 7807 completeness — "detail" field must be present
    //
    // ATDD Test 2 checks "status" and "title" but NOT "detail".
    // AC2 + Dev Notes explicitly require all three: status, title, detail.
    //
    // Given: an unhandled exception occurs
    // When:  middleware writes the Problem Details response
    // Then:  the JSON body contains a "detail" field with a non-empty safe message
    // ─────────────────────────────────────────────────────────────────────────
    [Fact]
    public async Task InvokeAsync_WhenExceptionThrown_ResponseBodyContainsDetailField()
    {
        // Arrange
        var logger = NullLogger<ExceptionHandlingMiddleware>.Instance;
        RequestDelegate next = _ => throw new Exception("raw-detail-error");
        var middleware = new ExceptionHandlingMiddleware(next, logger);
        var ctx = CreateHttpContext();

        // Act
        await middleware.InvokeAsync(ctx);

        // Assert
        var root = await ReadResponseJsonAsync(ctx);
        Assert.True(root.TryGetProperty("detail", out var detailProp),
            "RFC 7807 requires a 'detail' field");
        var detail = detailProp.GetString() ?? string.Empty;
        Assert.False(string.IsNullOrWhiteSpace(detail), "'detail' must not be empty");
        // The raw exception message must not appear in detail (NFR6)
        Assert.DoesNotContain("raw-detail-error", detail, StringComparison.OrdinalIgnoreCase);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // [P1] RFC 7807 — "type" field must be present
    //
    // Dev Notes state: fields required are type, title, status, detail.
    // Reference implementation sets Type = "https://tools.ietf.org/html/rfc7807".
    //
    // Given: an unhandled exception occurs
    // When:  middleware writes the Problem Details response
    // Then:  the JSON body contains a "type" field (RFC 7807 reference URI)
    // ─────────────────────────────────────────────────────────────────────────
    [Fact]
    public async Task InvokeAsync_WhenExceptionThrown_ResponseBodyContainsTypeField()
    {
        // Arrange
        var logger = NullLogger<ExceptionHandlingMiddleware>.Instance;
        RequestDelegate next = _ => throw new Exception("type-check-error");
        var middleware = new ExceptionHandlingMiddleware(next, logger);
        var ctx = CreateHttpContext();

        // Act
        await middleware.InvokeAsync(ctx);

        // Assert
        var root = await ReadResponseJsonAsync(ctx);
        Assert.True(root.TryGetProperty("type", out var typeProp),
            "RFC 7807 requires a 'type' field");
        var type = typeProp.GetString() ?? string.Empty;
        Assert.False(string.IsNullOrWhiteSpace(type), "'type' must not be empty");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // [P1] Exception with null message — middleware must not throw internally
    //
    // Boundary: Exception(null) is valid in .NET. Middleware must handle it
    // gracefully and still return a well-formed Problem Details response.
    //
    // Given: an exception with a null message is thrown
    // When:  middleware processes it
    // Then:  response is HTTP 500 with valid Problem Details (no NullReferenceException)
    // ─────────────────────────────────────────────────────────────────────────
    [Fact]
    public async Task InvokeAsync_WhenExceptionHasNullMessage_ReturnsValidProblemDetails()
    {
        // Arrange
        var logger = NullLogger<ExceptionHandlingMiddleware>.Instance;
        // Exception(null) produces an exception whose Message property is not null
        // but whose inner content could trip string interpolation — verify safety.
        RequestDelegate next = _ => throw new InvalidOperationException(null as string);
        var middleware = new ExceptionHandlingMiddleware(next, logger);
        var ctx = CreateHttpContext();

        // Act
        var exception = await Record.ExceptionAsync(() => middleware.InvokeAsync(ctx));

        // Assert — middleware itself must not throw
        Assert.Null(exception);
        Assert.Equal(StatusCodes.Status500InternalServerError, ctx.Response.StatusCode);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // [P1] NullReferenceException — common production exception type
    //
    // Given: a NullReferenceException is thrown
    // When:  middleware processes it
    // Then:  HTTP 500 + Problem Details (same behavior as generic Exception)
    // ─────────────────────────────────────────────────────────────────────────
    [Fact]
    public async Task InvokeAsync_WhenNullReferenceExceptionThrown_Returns500WithProblemDetails()
    {
        // Arrange
        var logger = NullLogger<ExceptionHandlingMiddleware>.Instance;
        RequestDelegate next = _ => throw new NullReferenceException("nre-test");
        var middleware = new ExceptionHandlingMiddleware(next, logger);
        var ctx = CreateHttpContext();

        // Act
        await middleware.InvokeAsync(ctx);

        // Assert
        Assert.Equal(StatusCodes.Status500InternalServerError, ctx.Response.StatusCode);
        var root = await ReadResponseJsonAsync(ctx);
        Assert.True(root.TryGetProperty("status", out _));
        Assert.True(root.TryGetProperty("title", out _));
        // Raw exception message must NOT appear
        var body = root.GetRawText();
        Assert.DoesNotContain("nre-test", body, StringComparison.OrdinalIgnoreCase);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // [P1] ArgumentException — common validation exception type
    //
    // Given: an ArgumentException is thrown by the next delegate
    // When:  middleware processes it
    // Then:  HTTP 500 + Problem Details without exposing parameter name or message
    // ─────────────────────────────────────────────────────────────────────────
    [Fact]
    public async Task InvokeAsync_WhenArgumentExceptionThrown_Returns500WithoutExposingParameter()
    {
        // Arrange
        var logger = NullLogger<ExceptionHandlingMiddleware>.Instance;
        const string sensitiveParam = "secretParameterName";
        RequestDelegate next = _ => throw new ArgumentException("bad arg", sensitiveParam);
        var middleware = new ExceptionHandlingMiddleware(next, logger);
        var ctx = CreateHttpContext();

        // Act
        await middleware.InvokeAsync(ctx);

        // Assert
        Assert.Equal(StatusCodes.Status500InternalServerError, ctx.Response.StatusCode);

        ctx.Response.Body.Seek(0, SeekOrigin.Begin);
        using var reader = new StreamReader(ctx.Response.Body);
        var body = await reader.ReadToEndAsync();

        // Neither the parameter name nor the argument message must be exposed
        Assert.DoesNotContain(sensitiveParam, body, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("bad arg", body, StringComparison.OrdinalIgnoreCase);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // [P2] Async exception via Task.FromException — covers async delegate pattern
    //
    // The next delegate may return a faulted Task rather than throwing synchronously.
    // Middleware must handle both forms equally.
    //
    // Given: the next delegate returns a faulted Task
    // When:  middleware awaits the delegate
    // Then:  HTTP 500 + Problem Details (identical to synchronous throw)
    // ─────────────────────────────────────────────────────────────────────────
    [Fact]
    public async Task InvokeAsync_WhenNextReturnsFaultedTask_Returns500WithProblemDetails()
    {
        // Arrange
        var logger = NullLogger<ExceptionHandlingMiddleware>.Instance;
        RequestDelegate next = _ => Task.FromException(new InvalidOperationException("faulted-task-error"));
        var middleware = new ExceptionHandlingMiddleware(next, logger);
        var ctx = CreateHttpContext();

        // Act
        await middleware.InvokeAsync(ctx);

        // Assert
        Assert.Equal(StatusCodes.Status500InternalServerError, ctx.Response.StatusCode);
        Assert.Contains("application/problem+json", ctx.Response.ContentType);

        var root = await ReadResponseJsonAsync(ctx);
        Assert.True(root.TryGetProperty("status", out _));

        var body = root.GetRawText();
        Assert.DoesNotContain("faulted-task-error", body, StringComparison.OrdinalIgnoreCase);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // [P2] Content-Type includes charset — verify exact match or subset
    //
    // The Content-Type header must contain "application/problem+json".
    // ASP.NET may append "; charset=utf-8" — both are acceptable.
    //
    // Given: middleware handles an exception
    // When:  the response is written
    // Then:  Content-Type starts with "application/problem+json"
    // ─────────────────────────────────────────────────────────────────────────
    [Fact]
    public async Task InvokeAsync_WhenExceptionThrown_ContentTypeStartsWithProblemJson()
    {
        // Arrange
        var logger = NullLogger<ExceptionHandlingMiddleware>.Instance;
        RequestDelegate next = _ => throw new Exception("content-type-test");
        var middleware = new ExceptionHandlingMiddleware(next, logger);
        var ctx = CreateHttpContext();

        // Act
        await middleware.InvokeAsync(ctx);

        // Assert — must start with the media type (charset suffix is acceptable)
        Assert.NotNull(ctx.Response.ContentType);
        Assert.StartsWith("application/problem+json", ctx.Response.ContentType,
            StringComparison.OrdinalIgnoreCase);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // [P2] Concurrent requests — each gets an independent response
    //
    // Boundary: middleware is a singleton in the pipeline (one instance serves
    // all requests). Concurrent exceptions must not bleed state between contexts.
    //
    // Given: two concurrent requests both throw exceptions
    // When:  middleware processes them simultaneously
    // Then:  both responses are HTTP 500 with valid Problem Details
    //   And: there is no shared mutable state between the two contexts
    // ─────────────────────────────────────────────────────────────────────────
    [Fact]
    public async Task InvokeAsync_WhenConcurrentExceptions_EachContextGetsIndependentResponse()
    {
        // Arrange
        var logger = NullLogger<ExceptionHandlingMiddleware>.Instance;
        RequestDelegate next = _ => throw new Exception("concurrent-error");
        var middleware = new ExceptionHandlingMiddleware(next, logger);

        var ctx1 = CreateHttpContext();
        var ctx2 = CreateHttpContext();

        // Act — run both invocations concurrently
        await Task.WhenAll(
            middleware.InvokeAsync(ctx1),
            middleware.InvokeAsync(ctx2)
        );

        // Assert — both contexts have independent, correct responses
        Assert.Equal(StatusCodes.Status500InternalServerError, ctx1.Response.StatusCode);
        Assert.Equal(StatusCodes.Status500InternalServerError, ctx2.Response.StatusCode);

        ctx1.Response.Body.Seek(0, SeekOrigin.Begin);
        ctx2.Response.Body.Seek(0, SeekOrigin.Begin);

        Assert.True(ctx1.Response.Body.Length > 0, "ctx1 response body must not be empty");
        Assert.True(ctx2.Response.Body.Length > 0, "ctx2 response body must not be empty");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // [P2] Happy path preserves non-default status codes
    //
    // When the next delegate sets a 404 status (no exception), middleware
    // must NOT override it to 200 or 500.
    //
    // Given: the next delegate sets HTTP 404 and returns without exception
    // When:  middleware processes the request
    // Then:  the response status code remains 404
    // ─────────────────────────────────────────────────────────────────────────
    [Fact]
    public async Task InvokeAsync_WhenNextSets404_StatusCodeIsNotOverridden()
    {
        // Arrange
        var logger = NullLogger<ExceptionHandlingMiddleware>.Instance;
        RequestDelegate next = ctx =>
        {
            ctx.Response.StatusCode = StatusCodes.Status404NotFound;
            return Task.CompletedTask;
        };
        var middleware = new ExceptionHandlingMiddleware(next, logger);
        var ctx = CreateHttpContext();

        // Act
        await middleware.InvokeAsync(ctx);

        // Assert
        Assert.Equal(StatusCodes.Status404NotFound, ctx.Response.StatusCode);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // [P2] Exception is swallowed by middleware — next delegate is NOT re-called
    //
    // Verifies that after handling an exception the middleware does NOT retry
    // or re-invoke the next delegate (which would cause double-processing).
    //
    // Given: the next delegate throws on first call
    // When:  middleware handles the exception
    // Then:  the next delegate is invoked exactly once (not twice)
    // ─────────────────────────────────────────────────────────────────────────
    [Fact]
    public async Task InvokeAsync_WhenExceptionThrown_NextDelegateIsCalledExactlyOnce()
    {
        // Arrange
        var logger = NullLogger<ExceptionHandlingMiddleware>.Instance;
        var callCount = 0;
        RequestDelegate next = _ =>
        {
            callCount++;
            throw new Exception("counting-exception");
        };
        var middleware = new ExceptionHandlingMiddleware(next, logger);
        var ctx = CreateHttpContext();

        // Act
        await middleware.InvokeAsync(ctx);

        // Assert
        Assert.Equal(1, callCount);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // [P3] Stack trace markers not present in "type" or "detail" fields
    //
    // Ensures that RFC 7807 fields do not smuggle stack trace content even
    // indirectly through the "type" or "detail" values.
    //
    // Given: an exception with a long stack trace is thrown
    // When:  middleware serializes the Problem Details
    // Then:  neither "type" nor "detail" contain stack trace text
    // ─────────────────────────────────────────────────────────────────────────
    [Fact]
    public async Task InvokeAsync_WhenExceptionThrown_TypeAndDetailFieldsDoNotContainStackTrace()
    {
        // Arrange
        var logger = NullLogger<ExceptionHandlingMiddleware>.Instance;
        // Throw from a named method to ensure a real stack trace is present
        RequestDelegate next = async _ =>
        {
            await Task.Yield(); // Ensure async context
            throw new InvalidOperationException("stack-trace-field-test");
        };
        var middleware = new ExceptionHandlingMiddleware(next, logger);
        var ctx = CreateHttpContext();

        // Act
        await middleware.InvokeAsync(ctx);

        // Assert
        var root = await ReadResponseJsonAsync(ctx);

        if (root.TryGetProperty("type", out var typeProp))
        {
            var typeValue = typeProp.GetString() ?? string.Empty;
            Assert.DoesNotContain("   at ", typeValue, StringComparison.Ordinal);
        }

        if (root.TryGetProperty("detail", out var detailProp))
        {
            var detailValue = detailProp.GetString() ?? string.Empty;
            Assert.DoesNotContain("   at ", detailValue, StringComparison.Ordinal);
            Assert.DoesNotContain("stack-trace-field-test", detailValue, StringComparison.OrdinalIgnoreCase);
        }
    }
}
