// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SiesaAgents.Infrastructure.Data;

#nullable disable

namespace SiesaAgents.Infrastructure.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("SiesaAgents.Domain.Entities.ClienteEntity", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<string>("Ciudad")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("character varying(100)")
                .HasColumnName("ciudad");

            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at");

            b.Property<string>("Nombre")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("character varying(200)")
                .HasColumnName("nombre");

            b.Property<string>("Nit")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("character varying(50)")
                .HasColumnName("nit");

            b.Property<string>("Telefono")
                .IsRequired()
                .HasMaxLength(30)
                .HasColumnType("character varying(30)")
                .HasColumnName("telefono");

            b.Property<DateTimeOffset>("UpdatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("updated_at");

            b.HasKey("Id")
                .HasName("pk_clientes");

            b.HasIndex("Nit")
                .IsUnique()
                .HasDatabaseName("uk_clientes_nit");

            b.ToTable("clientes");
        });

        modelBuilder.Entity("SiesaAgents.Domain.Entities.ContactoEntity", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<string>("Nombre")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("character varying(200)")
                .HasColumnName("nombre");

            b.Property<string>("Cargo")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("character varying(100)")
                .HasColumnName("cargo");

            b.Property<string>("Telefono")
                .IsRequired()
                .HasMaxLength(30)
                .HasColumnType("character varying(30)")
                .HasColumnName("telefono");

            b.Property<string>("Email")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("character varying(200)")
                .HasColumnName("email");

            b.Property<Guid?>("ClienteId")
                .HasColumnType("uuid")
                .HasColumnName("cliente_id");

            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at");

            b.Property<DateTimeOffset>("UpdatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("updated_at");

            b.HasKey("Id")
                .HasName("pk_contactos");

            b.HasIndex("Email")
                .HasDatabaseName("ix_contactos_email");

            b.HasIndex("ClienteId")
                .HasDatabaseName("ix_contactos_cliente_id");

            b.ToTable("contactos");
        });

        modelBuilder.Entity("SiesaAgents.Domain.Entities.ContactoEntity", b =>
        {
            b.HasOne("SiesaAgents.Domain.Entities.ClienteEntity", null)
                .WithMany()
                .HasForeignKey("ClienteId")
                .HasConstraintName("fk_contactos_clientes")
                .OnDelete(DeleteBehavior.SetNull);
        });
#pragma warning restore 612, 618
    }
}
