/**
 * Story 2.1 — Client List & Search
 * Epic 2: Client Management
 *
 * ATDD Unit Tests — RED Phase (Application layer)
 * Generated by testarch-atdd. These tests are intentionally FAILING until
 * `filterClientes` and `normalizeText` are implemented per AC-2.1.b (Task 5).
 *
 * Covers (story AC #2 / TC-E2-P1-02):
 *   - Case-insensitive nombre match
 *   - Case-insensitive NIT match (dual search)
 *   - Diacritic-insensitive match (`José` ↔ `jose`)
 *   - Empty query returns full input list
 *   - Whitespace-only query returns full input list
 *
 * Expected RED failure reason:
 *   "Cannot find module '../application/filterClientes'" (module does not yet exist).
 *   Once DEV creates the file per the AC-2.1.b spec, all assertions must turn green.
 */

import { describe, it, expect } from 'vitest'
import { filterClientes } from './filterClientes'
import type { Cliente } from '../domain/Cliente'

const FIXTURES: Cliente[] = [
  {
    id: '00000000-0000-4000-8000-000000000001',
    nombre: 'Acme S.A.',
    nit: '900123456-1',
    telefono: '+57 1 2223333',
    ciudad: 'Bogota',
    createdAt: '2026-05-30T10:00:00.000Z',
    updatedAt: '2026-05-30T10:00:00.000Z',
  },
  {
    id: '00000000-0000-4000-8000-000000000002',
    nombre: 'Beta Corp',
    nit: '800000000-2',
    telefono: '+57 4 5556666',
    ciudad: 'Medellin',
    createdAt: '2026-05-29T10:00:00.000Z',
    updatedAt: '2026-05-29T10:00:00.000Z',
  },
  {
    id: '00000000-0000-4000-8000-000000000003',
    nombre: 'José Pérez',
    nit: '700111222-3',
    telefono: '+57 2 7778888',
    ciudad: 'Cali',
    createdAt: '2026-05-28T10:00:00.000Z',
    updatedAt: '2026-05-28T10:00:00.000Z',
  },
]

describe('filterClientes — pure dual-search filter (AC-2.1.b, TC-E2-P1-02)', () => {
  it('[P1] returns the full input list when the query is empty', () => {
    // GIVEN: a populated dataset
    // WHEN: the query is the empty string
    const result = filterClientes(FIXTURES, '')

    // THEN: every input cliente is returned (no filtering)
    expect(result).toHaveLength(FIXTURES.length)
  })

  it('[P1] returns the full input list when the query is whitespace-only', () => {
    // GIVEN: a populated dataset
    // WHEN: the query is only spaces (must be trimmed before matching)
    const result = filterClientes(FIXTURES, '   ')

    // THEN: every input cliente is returned
    expect(result).toHaveLength(FIXTURES.length)
  })

  it('[P1] matches by nombre, case-insensitive ("ACM" -> "Acme S.A.")', () => {
    // GIVEN: the canonical 3-fixture dataset
    // WHEN: the user types "ACM" (uppercase)
    const result = filterClientes(FIXTURES, 'ACM')

    // THEN: only Acme is returned (case must be ignored)
    expect(result).toHaveLength(1)
    expect(result[0].nombre).toBe('Acme S.A.')
  })

  it('[P1] matches by NIT, case-insensitive ("900" -> "900123456-1")', () => {
    // GIVEN: the canonical 3-fixture dataset
    // WHEN: the user types a partial NIT
    const result = filterClientes(FIXTURES, '900')

    // THEN: only Acme is returned (matched via NIT, not nombre)
    expect(result).toHaveLength(1)
    expect(result[0].nit).toBe('900123456-1')
  })

  it('[P1] matches diacritic-insensitively ("jose" -> "José Pérez")', () => {
    // GIVEN: a dataset with accented nombre
    // WHEN: the user types the unaccented form
    const result = filterClientes(FIXTURES, 'jose')

    // THEN: the accented record is matched (NFD normalize + strip diacritics)
    expect(result).toHaveLength(1)
    expect(result[0].nombre).toBe('José Pérez')
  })

  it('[P1] returns an empty array when nothing matches', () => {
    // GIVEN: the canonical 3-fixture dataset
    // WHEN: the user types a query that matches neither nombre nor NIT
    const result = filterClientes(FIXTURES, 'zzz-no-match-zzz')

    // THEN: the result is an empty array (not null/undefined)
    expect(result).toEqual([])
  })
})
