import { renderHook, waitFor } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { createElement } from 'react';
import { http, HttpResponse } from 'msw';
import { setupServer } from 'msw/node';
import { beforeAll, afterAll, afterEach, describe, it, expect } from 'vitest';
import { useClientes } from './useClientes';
import type { Cliente } from '../domain/Cliente';

const mockClientes: Cliente[] = [
  {
    id: '1',
    nombre: 'Empresa Alpha',
    nit: '900123456-1',
    telefono: '6014567890',
    ciudad: 'Bogotá',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
];

const server = setupServer(
  http.get('*/api/v1/clientes', () => {
    return HttpResponse.json(mockClientes);
  })
);

beforeAll(() => server.listen());
afterEach(() => server.resetHandlers());
afterAll(() => server.close());

function createWrapper() {
  const queryClient = new QueryClient({
    defaultOptions: { queries: { retry: false } },
  });
  return ({ children }: { children: React.ReactNode }) =>
    createElement(QueryClientProvider, { client: queryClient }, children);
}

describe('useClientes', () => {
  it('uses query key ["clientes"]', async () => {
    const { result } = renderHook(() => useClientes(), {
      wrapper: createWrapper(),
    });

    await waitFor(() => expect(result.current.isSuccess).toBe(true));
    expect(result.current.data).toEqual(mockClientes);
  });

  it('exposes data, isLoading, isError, refetch', async () => {
    const { result } = renderHook(() => useClientes(), {
      wrapper: createWrapper(),
    });

    expect(result.current.isLoading).toBe(true);
    await waitFor(() => expect(result.current.isSuccess).toBe(true));
    expect(result.current.data).toBeDefined();
    expect(typeof result.current.refetch).toBe('function');
    expect(result.current.isError).toBe(false);
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// EXPANDED COVERAGE — Edge cases NOT in ATDD tests
// Generated by TEA testarch-automate (BMad-Integrated mode)
// ─────────────────────────────────────────────────────────────────────────────

// [P1] Error state handling
describe('useClientes — error state', () => {
  it('[P1] should set isError=true when API returns 500', async () => {
    // GIVEN: API returns a 500 error
    server.use(
      http.get('*/api/v1/clientes', () =>
        HttpResponse.json({ error: 'Internal Server Error' }, { status: 500 })
      )
    );

    // WHEN: Hook is rendered with retry disabled
    const { result } = renderHook(() => useClientes(), {
      wrapper: createWrapper(),
    });

    // THEN: isError becomes true after fetch fails
    await waitFor(() => expect(result.current.isError).toBe(true));
    expect(result.current.data).toBeUndefined();
  });

  it('[P1] should set isLoading=false when API returns error', async () => {
    // GIVEN: API returns a 500 error
    server.use(
      http.get('*/api/v1/clientes', () =>
        HttpResponse.json({ error: 'Server error' }, { status: 500 })
      )
    );

    // WHEN: Hook is rendered
    const { result } = renderHook(() => useClientes(), {
      wrapper: createWrapper(),
    });

    // Wait for failure
    await waitFor(() => expect(result.current.isError).toBe(true));

    // THEN: isLoading is false after failure (not stuck loading)
    expect(result.current.isLoading).toBe(false);
  });

  it('[P1] should set isError=false on successful fetch after error (refetch)', async () => {
    // GIVEN: First call fails, second call succeeds
    let callCount = 0;
    server.use(
      http.get('*/api/v1/clientes', () => {
        callCount++;
        if (callCount === 1) {
          return HttpResponse.json({ error: 'Server error' }, { status: 500 });
        }
        return HttpResponse.json(mockClientes);
      })
    );

    const { result } = renderHook(() => useClientes(), {
      wrapper: createWrapper(),
    });

    // Wait for error state
    await waitFor(() => expect(result.current.isError).toBe(true));

    // WHEN: refetch is called
    result.current.refetch();

    // THEN: isError becomes false and data is returned
    await waitFor(() => expect(result.current.isSuccess).toBe(true));
    expect(result.current.isError).toBe(false);
    expect(result.current.data).toEqual(mockClientes);
  });
});

// [P1] Empty array response
describe('useClientes — empty response', () => {
  it('[P1] should return empty array when API returns []', async () => {
    // GIVEN: API returns empty array
    server.use(
      http.get('*/api/v1/clientes', () => HttpResponse.json([]))
    );

    // WHEN: Hook is rendered
    const { result } = renderHook(() => useClientes(), {
      wrapper: createWrapper(),
    });

    // THEN: data is an empty array (not undefined)
    await waitFor(() => expect(result.current.isSuccess).toBe(true));
    expect(result.current.data).toEqual([]);
    expect(Array.isArray(result.current.data)).toBe(true);
  });
});

// [P2] Initial loading state
describe('useClientes — initial loading state', () => {
  it('[P2] should have isLoading=true before data arrives', () => {
    // GIVEN: API has not responded yet
    server.use(
      http.get('*/api/v1/clientes', async () => {
        await new Promise(() => {}); // Never resolves
        return HttpResponse.json([]);
      })
    );

    // WHEN: Hook is first rendered
    const { result } = renderHook(() => useClientes(), {
      wrapper: createWrapper(),
    });

    // THEN: isLoading is true initially
    expect(result.current.isLoading).toBe(true);
    expect(result.current.data).toBeUndefined();
  });

  it('[P2] should have isSuccess=false before data arrives', () => {
    // GIVEN: API has not responded yet
    server.use(
      http.get('*/api/v1/clientes', async () => {
        await new Promise(() => {});
        return HttpResponse.json([]);
      })
    );

    // WHEN: Hook is first rendered
    const { result } = renderHook(() => useClientes(), {
      wrapper: createWrapper(),
    });

    // THEN: isSuccess is false initially
    expect(result.current.isSuccess).toBe(false);
  });
});

// [P2] Data shape validation
describe('useClientes — data shape', () => {
  it('[P2] should return an array of Cliente objects with all required fields', async () => {
    // GIVEN: API returns a cliente with all fields
    const fullCliente: Cliente = {
      id: 'full-id-001',
      nombre: 'Empresa Completa',
      nit: '900999999-9',
      telefono: '6019999999',
      ciudad: 'Cali',
      createdAt: '2026-06-01T12:00:00Z',
      updatedAt: '2026-06-01T12:00:00Z',
    };
    server.use(
      http.get('*/api/v1/clientes', () => HttpResponse.json([fullCliente]))
    );

    // WHEN: Hook fetches data
    const { result } = renderHook(() => useClientes(), {
      wrapper: createWrapper(),
    });

    await waitFor(() => expect(result.current.isSuccess).toBe(true));

    // THEN: All fields are present on the returned object
    const first = result.current.data![0];
    expect(first).toHaveProperty('id', 'full-id-001');
    expect(first).toHaveProperty('nombre', 'Empresa Completa');
    expect(first).toHaveProperty('nit', '900999999-9');
    expect(first).toHaveProperty('telefono', '6019999999');
    expect(first).toHaveProperty('ciudad', 'Cali');
    expect(first).toHaveProperty('createdAt', '2026-06-01T12:00:00Z');
    expect(first).toHaveProperty('updatedAt', '2026-06-01T12:00:00Z');
  });
});
