/**
 * Story 1.2: Frontend Navigation Shell
 * Epic 1: Project Foundation & Application Shell
 *
 * Component Tests — RED Phase (Vitest + React Testing Library)
 * These tests are intentionally FAILING until implementation is complete.
 *
 * Acceptance Criteria covered:
 *   AC6 — WCAG 2.1 AA: all interactive elements have proper ARIA labels in Spanish;
 *          navigation landmark is correctly identified by screen readers
 *
 * Testing framework: Vitest + React Testing Library
 * Accessibility: @axe-core/react or jest-axe (to be installed)
 *
 * Required data-testid attributes:
 *   - nav-rail            : <nav> element containing NavigationRail (desktop)
 *   - nav-bar             : <nav> element containing NavigationBar (mobile)
 *   - nav-rail-clientes   : NavigationRail link for Clientes
 *   - nav-rail-contactos  : NavigationRail link for Contactos
 *   - nav-bar-clientes    : NavigationBar link for Clientes
 *   - nav-bar-contactos   : NavigationBar link for Contactos
 *   - clientes-view       : rendered view for /clientes route
 *   - contactos-view      : rendered view for /contactos route
 *   - not-found-view      : rendered view for unknown routes (404)
 *   - not-found-message   : Spanish text in 404 view
 */

import React from 'react';
import { render, screen } from '@testing-library/react';
import { createMemoryHistory, RouterProvider, createRouter } from '@tanstack/react-router';
// routeTree.gen.ts is auto-generated by TanStack Router plugin — does not exist yet (RED phase)
import { routeTree } from '../../routeTree.gen';

// ─────────────────────────────────────────────────────────────────────────────
// Helper: create a router instance pointing at a given initial URL
// ─────────────────────────────────────────────────────────────────────────────

function createTestRouter(initialPath: string) {
  return createRouter({
    routeTree,
    history: createMemoryHistory({ initialEntries: [initialPath] }),
  });
}

// ─────────────────────────────────────────────────────────────────────────────
// AC6 — Navigation landmark and ARIA labels (WCAG 2.1 AA)
// ─────────────────────────────────────────────────────────────────────────────

describe('AC6 — Navigation landmark and ARIA labels (WCAG 2.1 AA)', () => {
  it('should render a navigation landmark with aria-label "Navegación principal"', () => {
    // GIVEN: The application shell is rendered
    const router = createTestRouter('/clientes');

    // WHEN: The navigation is rendered
    render(<RouterProvider router={router} />);

    // THEN: A <nav> with aria-label="Navegación principal" exists in the document
    const nav = screen.getByRole('navigation', { name: /navegación principal/i });
    expect(nav).toBeInTheDocument();
  });

  it('should have an accessible name for the Clientes navigation link', () => {
    // GIVEN: The navigation shell is rendered
    const router = createTestRouter('/clientes');
    render(<RouterProvider router={router} />);

    // WHEN: A screen reader traverses the navigation
    // THEN: The Clientes link is reachable via role and accessible name in Spanish
    const clientesLink = screen.getByRole('link', { name: /clientes/i });
    expect(clientesLink).toBeInTheDocument();
  });

  it('should have an accessible name for the Contactos navigation link', () => {
    // GIVEN: The navigation shell is rendered
    const router = createTestRouter('/clientes');
    render(<RouterProvider router={router} />);

    // WHEN: A screen reader traverses the navigation
    // THEN: The Contactos link is reachable via role and accessible name in Spanish
    const contactosLink = screen.getByRole('link', { name: /contactos/i });
    expect(contactosLink).toBeInTheDocument();
  });

  it('should have data-testid="nav-rail" on the desktop navigation container', () => {
    // GIVEN: The application shell is rendered at desktop viewport (jsdom default)
    const router = createTestRouter('/clientes');
    render(<RouterProvider router={router} />);

    // WHEN: The DOM is inspected
    // THEN: The nav-rail data-testid is present (used by E2E selectors)
    const navRail = screen.getByTestId('nav-rail');
    expect(navRail).toBeInTheDocument();
  });

  it('should have data-testid="nav-bar" on the mobile navigation container', () => {
    // GIVEN: The application shell is rendered
    const router = createTestRouter('/clientes');
    render(<RouterProvider router={router} />);

    // WHEN: The DOM is inspected
    // THEN: The nav-bar data-testid is present in the DOM (may be hidden via CSS)
    const navBar = screen.getByTestId('nav-bar');
    expect(navBar).toBeInTheDocument();
  });

  it('should NOT have any interactive navigation element without an aria-label or visible text', () => {
    // GIVEN: The application shell is rendered
    const router = createTestRouter('/clientes');
    render(<RouterProvider router={router} />);

    // WHEN: All navigation links are collected
    const navLinks = screen.getAllByRole('link');

    // THEN: Each link has either visible text OR an aria-label (not empty)
    navLinks.forEach((link) => {
      const hasVisibleText = link.textContent && link.textContent.trim().length > 0;
      const hasAriaLabel = link.getAttribute('aria-label') && link.getAttribute('aria-label')!.trim().length > 0;
      expect(hasVisibleText || hasAriaLabel).toBe(true);
    });
  });

  it('should mark navigation icons as aria-hidden when they are decorative', () => {
    // GIVEN: The navigation shell renders icons alongside text labels
    const router = createTestRouter('/clientes');
    render(<RouterProvider router={router} />);

    // WHEN: The DOM is inspected for SVG or img elements inside navigation
    const navRail = screen.getByTestId('nav-rail');
    const decorativeImages = navRail.querySelectorAll('svg, img');

    // THEN: Each decorative icon has aria-hidden="true"
    decorativeImages.forEach((icon) => {
      // Icons that are purely decorative must have aria-hidden
      // (icons with standalone meaning must have aria-label instead)
      const ariaHidden = icon.getAttribute('aria-hidden');
      const ariaLabel = icon.getAttribute('aria-label');
      // Either aria-hidden="true" OR has its own aria-label (standalone)
      expect(ariaHidden === 'true' || (ariaLabel && ariaLabel.trim().length > 0)).toBe(true);
    });
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// Navigation routing — component-level verification
// ─────────────────────────────────────────────────────────────────────────────

describe('Navigation routing — component rendering', () => {
  it('should render the Clientes view at /clientes', () => {
    // GIVEN: Router initialized with /clientes
    const router = createTestRouter('/clientes');
    render(<RouterProvider router={router} />);

    // WHEN: The route is resolved
    // THEN: The clientes-view is in the document
    const clientesView = screen.getByTestId('clientes-view');
    expect(clientesView).toBeInTheDocument();
  });

  it('should render the Contactos view at /contactos', () => {
    // GIVEN: Router initialized with /contactos
    const router = createTestRouter('/contactos');
    render(<RouterProvider router={router} />);

    // WHEN: The route is resolved
    // THEN: The contactos-view is in the document
    const contactosView = screen.getByTestId('contactos-view');
    expect(contactosView).toBeInTheDocument();
  });

  it('should render a 404 not-found view for an unknown route', () => {
    // GIVEN: Router initialized with an unknown path
    const router = createTestRouter('/ruta-desconocida');
    render(<RouterProvider router={router} />);

    // WHEN: The route is resolved (no match)
    // THEN: The not-found-view is in the document
    const notFoundView = screen.getByTestId('not-found-view');
    expect(notFoundView).toBeInTheDocument();
  });

  it('should show a Spanish message in the 404 not-found view', () => {
    // GIVEN: Router initialized with an unknown path
    const router = createTestRouter('/ruta-desconocida');
    render(<RouterProvider router={router} />);

    // WHEN: The 404 view is rendered
    // THEN: A Spanish message is visible
    const notFoundMessage = screen.getByTestId('not-found-message');
    expect(notFoundMessage.textContent).toMatch(/página|no encontrada|existe/i);
  });
});
