/**
 * Story 1.2: Frontend Navigation Shell
 * Component Tests — App Shell Layout (_app.tsx)
 *
 * ATDD Acceptance Tests — RED Phase
 * These tests are intentionally FAILING until implementation is complete.
 *
 * Acceptance Criteria covered:
 *   AC1 — Desktop NavigationRail visible on left with Clientes & Contactos entries (FR28)
 *   AC2 — Mobile NavigationBar visible at bottom with accessible nav items (FR29)
 *   AC3 — Deep linking to /clientes and /contactos with active state highlight (FR30)
 *   AC4 — 404 not-found view with Spanish message and return link to /clientes
 *   AC5 — Navigation landmark with Spanish aria-label (WCAG 2.1 AA)
 *
 * Test levels: Component (Vitest + React Testing Library)
 * Test file location: co-located with routes, per project convention
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { render, screen, fireEvent, act } from '@testing-library/react';
import {
  createMemoryHistory,
  createRouter,
  RouterProvider,
} from '@tanstack/react-router';

// ─────────────────────────────────────────────────────────────────────────────
// Test helpers
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Sets window.innerWidth to simulate a specific viewport width.
 * Required because jsdom does not resize on its own.
 */
function setViewportWidth(width: number): void {
  Object.defineProperty(window, 'innerWidth', {
    writable: true,
    configurable: true,
    value: width,
  });
  window.dispatchEvent(new Event('resize'));
}

/**
 * Renders the application shell at a given route using an in-memory router.
 * Import the routeTree once it is generated by TanStack Router plugin.
 *
 * NOTE: routeTree import will fail (RED) until the implementation files are created
 * and `pnpm run dev` regenerates routeTree.gen.ts.
 */
async function renderAppAtRoute(path: string) {
  // Dynamic import — will throw ModuleNotFoundError in RED phase
  // (routeTree.gen.ts does not exist until _app.tsx and its children are created)
  const { routeTree } = await import('../../routeTree.gen');

  const memoryHistory = createMemoryHistory({ initialEntries: [path] });
  const router = createRouter({ routeTree, history: memoryHistory });

  render(<RouterProvider router={router} />);

  // Wait for async router transitions to settle
  await router.load();
}

// ─────────────────────────────────────────────────────────────────────────────
// AC1 — Desktop NavigationRail (viewport >= 1024px)
// ─────────────────────────────────────────────────────────────────────────────

describe('AC1 — Desktop NavigationRail (viewport >= 1024px)', () => {
  beforeEach(() => {
    setViewportWidth(1280);
  });

  afterEach(() => {
    setViewportWidth(1024);
  });

  it('should render the NavigationRail on desktop viewport', async () => {
    // GIVEN: The application is loaded on a desktop browser (viewport >= 1024px)
    // WHEN: The component tree is rendered at /clientes
    await renderAppAtRoute('/clientes');

    // THEN: The NavigationRail component is present in the DOM
    expect(screen.getByTestId('navigation-rail')).toBeDefined();
  });

  it('should show a "Clientes" entry inside the NavigationRail on desktop', async () => {
    // GIVEN: The application shell is rendered on desktop
    // WHEN: The layout renders at /clientes
    await renderAppAtRoute('/clientes');

    // THEN: A "Clientes" nav item is visible
    expect(screen.getByTestId('nav-item-clientes')).toBeDefined();
    expect(screen.getByTestId('nav-item-clientes')).toHaveTextContent('Clientes');
  });

  it('should show a "Contactos" entry inside the NavigationRail on desktop', async () => {
    // GIVEN: The application shell is rendered on desktop
    // WHEN: The layout renders at /clientes
    await renderAppAtRoute('/clientes');

    // THEN: A "Contactos" nav item is visible
    expect(screen.getByTestId('nav-item-contactos')).toBeDefined();
    expect(screen.getByTestId('nav-item-contactos')).toHaveTextContent('Contactos');
  });

  it('should NOT render the NavigationBar on desktop viewport', async () => {
    // GIVEN: The application is loaded on desktop (viewport >= 1024px)
    // WHEN: The layout renders
    await renderAppAtRoute('/clientes');

    // THEN: The NavigationBar is not visible (hidden via TailwindCSS responsive class)
    const navBar = screen.queryByTestId('navigation-bar');
    // Either not in the DOM or hidden — the element may exist but must not be displayed
    if (navBar) {
      expect(navBar).not.toBeVisible();
    } else {
      expect(navBar).toBeNull();
    }
  });

  it('should navigate to /contactos without full page reload when clicking Contactos', async () => {
    // GIVEN: The application is on /clientes on desktop
    // WHEN: The user clicks the "Contactos" nav item
    await renderAppAtRoute('/clientes');

    await act(async () => {
      fireEvent.click(screen.getByTestId('nav-item-contactos'));
    });

    // THEN: The Contactos view is rendered (SPA navigation — no full reload)
    expect(screen.getByTestId('contactos-view')).toBeDefined();
  });

  it('should navigate to /clientes without full page reload when clicking Clientes', async () => {
    // GIVEN: The application is on /contactos on desktop
    // WHEN: The user clicks the "Clientes" nav item
    await renderAppAtRoute('/contactos');

    await act(async () => {
      fireEvent.click(screen.getByTestId('nav-item-clientes'));
    });

    // THEN: The Clientes view is rendered (SPA navigation — no full reload)
    expect(screen.getByTestId('clientes-view')).toBeDefined();
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// AC2 — Mobile NavigationBar (viewport < 1024px)
// ─────────────────────────────────────────────────────────────────────────────

describe('AC2 — Mobile NavigationBar (viewport < 1024px)', () => {
  beforeEach(() => {
    setViewportWidth(390);
  });

  afterEach(() => {
    setViewportWidth(1024);
  });

  it('should render the NavigationBar at the bottom on mobile viewport', async () => {
    // GIVEN: The application is loaded on a mobile browser (viewport < 1024px)
    // WHEN: The layout renders at /clientes
    await renderAppAtRoute('/clientes');

    // THEN: The NavigationBar component is present in the DOM
    expect(screen.getByTestId('navigation-bar')).toBeDefined();
    expect(screen.getByTestId('navigation-bar')).toBeVisible();
  });

  it('should have the "Clientes" nav item accessible and tappable on mobile', async () => {
    // GIVEN: The application is loaded on mobile
    // WHEN: The layout renders at /clientes
    await renderAppAtRoute('/clientes');

    // THEN: The Clientes item is accessible (not disabled, visible)
    const clientesItem = screen.getByTestId('nav-item-clientes');
    expect(clientesItem).toBeDefined();
    expect(clientesItem).toBeVisible();
  });

  it('should have the "Contactos" nav item accessible and tappable on mobile', async () => {
    // GIVEN: The application is loaded on mobile
    // WHEN: The layout renders at /clientes
    await renderAppAtRoute('/clientes');

    // THEN: The Contactos item is accessible (not disabled, visible)
    const contactosItem = screen.getByTestId('nav-item-contactos');
    expect(contactosItem).toBeDefined();
    expect(contactosItem).toBeVisible();
  });

  it('should NOT render the NavigationRail on mobile viewport', async () => {
    // GIVEN: The application is loaded on mobile (viewport < 1024px)
    // WHEN: The layout renders
    await renderAppAtRoute('/clientes');

    // THEN: The NavigationRail is not visible on mobile
    const navRail = screen.queryByTestId('navigation-rail');
    if (navRail) {
      expect(navRail).not.toBeVisible();
    } else {
      expect(navRail).toBeNull();
    }
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// AC3 — Deep linking with active state (FR30)
// ─────────────────────────────────────────────────────────────────────────────

describe('AC3 — Deep linking to /clientes and /contactos (FR30)', () => {
  beforeEach(() => {
    setViewportWidth(1280);
  });

  afterEach(() => {
    setViewportWidth(1024);
  });

  it('should render ClientesView when navigating directly to /clientes', async () => {
    // GIVEN: The user types /clientes directly in the browser URL bar
    // WHEN: The route loads
    await renderAppAtRoute('/clientes');

    // THEN: The Clientes view is rendered without any redirect
    expect(screen.getByTestId('clientes-view')).toBeDefined();
  });

  it('should render ContactosView when navigating directly to /contactos', async () => {
    // GIVEN: The user types /contactos directly in the browser URL bar
    // WHEN: The route loads
    await renderAppAtRoute('/contactos');

    // THEN: The Contactos view is rendered without any redirect
    expect(screen.getByTestId('contactos-view')).toBeDefined();
  });

  it('should highlight the Clientes nav item as active when at /clientes', async () => {
    // GIVEN: The user navigates directly to /clientes
    // WHEN: The page renders
    await renderAppAtRoute('/clientes');

    // THEN: The Clientes nav item has the active state attribute
    const clientesItem = screen.getByTestId('nav-item-clientes');
    expect(clientesItem.getAttribute('data-active')).toBe('true');
  });

  it('should highlight the Contactos nav item as active when at /contactos', async () => {
    // GIVEN: The user navigates directly to /contactos
    // WHEN: The page renders
    await renderAppAtRoute('/contactos');

    // THEN: The Contactos nav item has the active state attribute
    const contactosItem = screen.getByTestId('nav-item-contactos');
    expect(contactosItem.getAttribute('data-active')).toBe('true');
  });

  it('should redirect root path / to /clientes', async () => {
    // GIVEN: The user navigates to the root path /
    // WHEN: The route resolves
    const { routeTree } = await import('../../routeTree.gen');
    const memoryHistory = createMemoryHistory({ initialEntries: ['/'] });
    const router = createRouter({ routeTree, history: memoryHistory });

    render(<RouterProvider router={router} />);
    await router.load();

    // THEN: The URL resolves to /clientes and the Clientes view is shown
    expect(router.state.location.pathname).toBe('/clientes');
    expect(screen.getByTestId('clientes-view')).toBeDefined();
  });

  it('should not redirect away from /clientes when loading it directly', async () => {
    // GIVEN: The user navigates directly to /clientes
    // WHEN: The router resolves the route
    const { routeTree } = await import('../../routeTree.gen');
    const memoryHistory = createMemoryHistory({ initialEntries: ['/clientes'] });
    const router = createRouter({ routeTree, history: memoryHistory });

    render(<RouterProvider router={router} />);
    await router.load();

    // THEN: The URL remains /clientes — no unexpected redirect
    expect(router.state.location.pathname).toBe('/clientes');
  });

  it('should not redirect away from /contactos when loading it directly', async () => {
    // GIVEN: The user navigates directly to /contactos
    // WHEN: The router resolves the route
    const { routeTree } = await import('../../routeTree.gen');
    const memoryHistory = createMemoryHistory({ initialEntries: ['/contactos'] });
    const router = createRouter({ routeTree, history: memoryHistory });

    render(<RouterProvider router={router} />);
    await router.load();

    // THEN: The URL remains /contactos — no unexpected redirect
    expect(router.state.location.pathname).toBe('/contactos');
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// AC4 — 404 not-found view
// ─────────────────────────────────────────────────────────────────────────────

describe('AC4 — 404 not-found view for unknown routes', () => {
  beforeEach(() => {
    setViewportWidth(1280);
  });

  afterEach(() => {
    setViewportWidth(1024);
  });

  it('should render the not-found view when navigating to an unknown route', async () => {
    // GIVEN: The user navigates to an unknown route (e.g., /unknown-path)
    // WHEN: The page loads
    await renderAppAtRoute('/unknown-path');

    // THEN: The not-found view is displayed
    expect(screen.getByTestId('not-found-view')).toBeDefined();
    expect(screen.getByTestId('not-found-view')).toBeVisible();
  });

  it('should display a Spanish message on the 404 view', async () => {
    // GIVEN: The user navigates to an unknown route
    // WHEN: The not-found component renders
    await renderAppAtRoute('/unknown-path');

    // THEN: A message containing "no encontrada" (Spanish) is displayed
    const message = screen.getByTestId('not-found-message');
    expect(message).toBeDefined();
    expect(message).toHaveTextContent('no encontrada');
  });

  it('should display a "Volver a Clientes" link pointing to /clientes on the 404 view', async () => {
    // GIVEN: The user navigates to an unknown route
    // WHEN: The not-found component renders
    await renderAppAtRoute('/unknown-path');

    // THEN: A link back to /clientes is visible with the correct href
    const backLink = screen.getByTestId('not-found-back-link');
    expect(backLink).toBeDefined();
    expect(backLink).toHaveAttribute('href', '/clientes');
  });

  it('should navigate to /clientes when clicking the return link on 404 view', async () => {
    // GIVEN: The user is on the not-found view
    const { routeTree } = await import('../../routeTree.gen');
    const memoryHistory = createMemoryHistory({ initialEntries: ['/unknown-path'] });
    const router = createRouter({ routeTree, history: memoryHistory });

    render(<RouterProvider router={router} />);
    await router.load();

    // WHEN: The user clicks the "Volver a Clientes" link
    await act(async () => {
      fireEvent.click(screen.getByTestId('not-found-back-link'));
      await router.load();
    });

    // THEN: The user is navigated to /clientes
    expect(router.state.location.pathname).toBe('/clientes');
    expect(screen.getByTestId('clientes-view')).toBeDefined();
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// AC5 — Accessibility: navigation landmark (WCAG 2.1 AA)
// ─────────────────────────────────────────────────────────────────────────────

describe('AC5 — Navigation landmark accessibility (WCAG 2.1 AA)', () => {
  beforeEach(() => {
    setViewportWidth(1280);
  });

  afterEach(() => {
    setViewportWidth(1024);
  });

  it('should have a <nav> element with aria-label="Navegación principal"', async () => {
    // GIVEN: The application shell is rendered
    // WHEN: A screen reader user navigates the page
    await renderAppAtRoute('/clientes');

    // THEN: The nav element has the correct Spanish aria-label
    const navLandmark = screen.getByRole('navigation', { name: 'Navegación principal' });
    expect(navLandmark).toBeDefined();
    expect(navLandmark.tagName.toLowerCase()).toBe('nav');
  });

  it('should have the navigation landmark testid present', async () => {
    // GIVEN: The application shell is rendered
    // WHEN: The page loads
    await renderAppAtRoute('/clientes');

    // THEN: The semantic navigation landmark element exists in the DOM
    expect(screen.getByTestId('navigation-landmark')).toBeDefined();
    expect(screen.getByTestId('navigation-landmark')).toBeVisible();
  });

  it('should have aria-label in Spanish (not English) on the navigation element', async () => {
    // GIVEN: The application shell is rendered
    // WHEN: The nav element is inspected for accessible label
    await renderAppAtRoute('/clientes');

    // THEN: The aria-label is in Spanish ("Navegación principal"), not English
    const navLandmark = screen.getByTestId('navigation-landmark');
    expect(navLandmark.getAttribute('aria-label')).toBe('Navegación principal');
  });

  it('should render navigation items with Spanish text labels', async () => {
    // GIVEN: The application shell is rendered
    // WHEN: The navigation items are inspected for text content
    await renderAppAtRoute('/clientes');

    // THEN: Both items have Spanish text ("Clientes", "Contactos") — no English
    expect(screen.getByTestId('nav-item-clientes')).toHaveTextContent('Clientes');
    expect(screen.getByTestId('nav-item-contactos')).toHaveTextContent('Contactos');
  });
});
