/**
 * Story 1.2: Frontend Navigation Shell
 * Component Tests — RED Phase (Vitest + React Testing Library)
 *
 * These tests are intentionally FAILING until implementation is complete.
 * They define the expected component behavior for the navigation shell.
 *
 * Acceptance Criteria covered:
 *   AC1 — NavigationRail visible on desktop (>= 1024px) with Clientes/Contactos
 *   AC2 — NavigationBar visible on mobile (< 1024px) with Clientes/Contactos
 *   AC3 — Deep linking: active nav state reflects current route
 *   AC4 — Client-side navigation updates active state without page reload
 *   AC5 — Unknown route renders 404 "Página no encontrada"
 *   AC6 — Root / redirects to /clientes
 *   AC7 — ARIA labels in Spanish, nav landmark present
 */

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'
import { render, screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'

// NOTE: These imports will fail (RED phase) until the route files are created.
// Implementation requires:
//   - frontend/src/routes/_app.tsx
//   - frontend/src/routes/_app/clientes.tsx
//   - frontend/src/routes/_app/contactos.tsx
//   - frontend/src/routes/$.tsx  (catch-all 404)
//   - frontend/src/routes/index.tsx  (redirect to /clientes)

// Helper to mock window.innerWidth for responsive breakpoint testing
function setViewport(width: number): void {
  Object.defineProperty(window, 'innerWidth', {
    writable: true,
    configurable: true,
    value: width,
  })
  window.dispatchEvent(new Event('resize'))
}

// TanStack Router test helper — creates a router with MemoryHistory for testing
// Implementation note: use createMemoryHistory + createRouter from @tanstack/react-router
async function renderWithRouter(initialPath: string) {
  const { createMemoryHistory, createRouter, RouterProvider } = await import('@tanstack/react-router')
  // routeTree is auto-generated by @tanstack/router-plugin/vite — must include all routes
  const { routeTree } = await import('../../routeTree.gen')

  const memoryHistory = createMemoryHistory({ initialEntries: [initialPath] })
  const router = createRouter({ routeTree, history: memoryHistory })

  return render(<RouterProvider router={router} />)
}

// ─────────────────────────────────────────────────────────────────────────────
// AC1 — Desktop NavigationRail (>= 1024px)
// ─────────────────────────────────────────────────────────────────────────────

describe('AC1 — NavigationRail on desktop viewport (>= 1024px)', () => {
  beforeEach(() => {
    setViewport(1280)
  })

  afterEach(() => {
    setViewport(1024)
  })

  it('should render the app-shell wrapper', async () => {
    // GIVEN: Desktop viewport is active
    // WHEN: App is rendered at /clientes
    await renderWithRouter('/clientes')

    // THEN: The app-shell data-testid is present
    expect(document.querySelector('[data-testid="app-shell"]')).toBeTruthy()
  })

  it('should render the NavigationRail on desktop viewport', async () => {
    // GIVEN: Desktop viewport (>= 1024px)
    // WHEN: The app shell renders
    await renderWithRouter('/clientes')

    // THEN: NavigationRail with data-testid="navigation-rail" is in the document
    const rail = document.querySelector('[data-testid="navigation-rail"]')
    expect(rail).toBeTruthy()
  })

  it('should render Clientes link in NavigationRail', async () => {
    // GIVEN: Desktop viewport with NavigationRail visible
    // WHEN: The app shell renders
    await renderWithRouter('/clientes')

    // THEN: An element with aria-label="Clientes" is inside the NavigationRail
    const rail = document.querySelector('[data-testid="navigation-rail"]')
    expect(rail?.querySelector('[aria-label="Clientes"]')).toBeTruthy()
  })

  it('should render Contactos link in NavigationRail', async () => {
    // GIVEN: Desktop viewport with NavigationRail visible
    // WHEN: The app shell renders
    await renderWithRouter('/clientes')

    // THEN: An element with aria-label="Contactos" is inside the NavigationRail
    const rail = document.querySelector('[data-testid="navigation-rail"]')
    expect(rail?.querySelector('[aria-label="Contactos"]')).toBeTruthy()
  })
})

// ─────────────────────────────────────────────────────────────────────────────
// AC2 — Mobile NavigationBar (< 1024px)
// ─────────────────────────────────────────────────────────────────────────────

describe('AC2 — NavigationBar on mobile viewport (< 1024px)', () => {
  beforeEach(() => {
    setViewport(390)
  })

  afterEach(() => {
    setViewport(1280)
  })

  it('should render the NavigationBar on mobile viewport', async () => {
    // GIVEN: Mobile viewport (< 1024px)
    // WHEN: The app shell renders
    await renderWithRouter('/clientes')

    // THEN: NavigationBar with data-testid="navigation-bar" is in the document
    const bar = document.querySelector('[data-testid="navigation-bar"]')
    expect(bar).toBeTruthy()
  })

  it('should render Clientes entry in NavigationBar on mobile', async () => {
    // GIVEN: Mobile viewport with NavigationBar visible
    // WHEN: The app shell renders
    await renderWithRouter('/clientes')

    // THEN: An element with aria-label="Clientes" is inside the NavigationBar
    const bar = document.querySelector('[data-testid="navigation-bar"]')
    expect(bar?.querySelector('[aria-label="Clientes"]')).toBeTruthy()
  })

  it('should render Contactos entry in NavigationBar on mobile', async () => {
    // GIVEN: Mobile viewport with NavigationBar visible
    // WHEN: The app shell renders
    await renderWithRouter('/clientes')

    // THEN: An element with aria-label="Contactos" is inside the NavigationBar
    const bar = document.querySelector('[data-testid="navigation-bar"]')
    expect(bar?.querySelector('[aria-label="Contactos"]')).toBeTruthy()
  })
})

// ─────────────────────────────────────────────────────────────────────────────
// AC3 — Active navigation state on direct URL access (deep linking)
// ─────────────────────────────────────────────────────────────────────────────

describe('AC3 — Active nav state reflects current route (deep linking)', () => {
  beforeEach(() => {
    setViewport(1280)
  })

  it('should render the clientes-view when /clientes is accessed', async () => {
    // GIVEN: The user navigates directly to /clientes
    // WHEN: The router resolves the route
    await renderWithRouter('/clientes')

    // THEN: clientes-view is rendered
    expect(document.querySelector('[data-testid="clientes-view"]')).toBeTruthy()
  })

  it('should render the contactos-view when /contactos is accessed', async () => {
    // GIVEN: The user navigates directly to /contactos
    // WHEN: The router resolves the route
    await renderWithRouter('/contactos')

    // THEN: contactos-view is rendered
    expect(document.querySelector('[data-testid="contactos-view"]')).toBeTruthy()
  })

  it('should mark Clientes nav item as aria-current="page" on /clientes route', async () => {
    // GIVEN: The user is on /clientes
    // WHEN: The navigation renders
    await renderWithRouter('/clientes')

    // THEN: Clientes nav item has aria-current="page"
    const rail = document.querySelector('[data-testid="navigation-rail"]')
    const clientesItem = rail?.querySelector('[aria-label="Clientes"]')
    expect(clientesItem?.getAttribute('aria-current')).toBe('page')
  })

  it('should mark Contactos nav item as aria-current="page" on /contactos route', async () => {
    // GIVEN: The user is on /contactos
    // WHEN: The navigation renders
    await renderWithRouter('/contactos')

    // THEN: Contactos nav item has aria-current="page"
    const rail = document.querySelector('[data-testid="navigation-rail"]')
    const contactosItem = rail?.querySelector('[aria-label="Contactos"]')
    expect(contactosItem?.getAttribute('aria-current')).toBe('page')
  })
})

// ─────────────────────────────────────────────────────────────────────────────
// AC4 — Navigation between routes updates active state
// ─────────────────────────────────────────────────────────────────────────────

describe('AC4 — Active state updates when navigating between routes', () => {
  beforeEach(() => {
    setViewport(1280)
  })

  it('should update active state to Contactos after clicking Contactos link', async () => {
    const user = userEvent.setup()

    // GIVEN: The user is on /clientes
    await renderWithRouter('/clientes')

    // WHEN: The user clicks the Contactos navigation item
    const rail = document.querySelector('[data-testid="navigation-rail"]')
    const contactosLink = rail?.querySelector('[aria-label="Contactos"]') as HTMLElement
    expect(contactosLink).toBeTruthy()
    await user.click(contactosLink)

    // THEN: Contactos is now marked as active (aria-current="page")
    expect(contactosLink.getAttribute('aria-current')).toBe('page')
  })

  it('should remove active state from Clientes after navigating to Contactos', async () => {
    const user = userEvent.setup()

    // GIVEN: The user is on /clientes (Clientes active)
    await renderWithRouter('/clientes')

    // WHEN: The user clicks the Contactos navigation item
    const rail = document.querySelector('[data-testid="navigation-rail"]')
    const contactosLink = rail?.querySelector('[aria-label="Contactos"]') as HTMLElement
    await user.click(contactosLink)

    // THEN: Clientes is NO longer marked as active
    const clientesLink = rail?.querySelector('[aria-label="Clientes"]')
    expect(clientesLink?.getAttribute('aria-current')).not.toBe('page')
  })
})

// ─────────────────────────────────────────────────────────────────────────────
// AC5 — 404 not-found view for unknown routes
// ─────────────────────────────────────────────────────────────────────────────

describe('AC5 — 404 not-found view for unknown routes', () => {
  it('should render the not-found-view for an unknown route', async () => {
    // GIVEN: The user navigates to a non-existent route
    // WHEN: The router attempts to resolve it
    await renderWithRouter('/ruta-inexistente')

    // THEN: The not-found-view is rendered
    expect(document.querySelector('[data-testid="not-found-view"]')).toBeTruthy()
  })

  it('should display "Página no encontrada" message on 404 page', async () => {
    // GIVEN: The user is on an unknown route
    // WHEN: The 404 view renders
    await renderWithRouter('/ruta-inexistente')

    // THEN: The Spanish message "Página no encontrada" is visible
    expect(screen.getByText(/Página no encontrada/i)).toBeTruthy()
  })

  it('should show a link back to /clientes on the 404 page', async () => {
    // GIVEN: The user is on the 404 page
    // WHEN: The not-found view renders
    await renderWithRouter('/ruta-inexistente')

    // THEN: A link to /clientes is present (with text "Ir a Clientes")
    const backLink = document.querySelector('[data-testid="not-found-view"] a[href="/clientes"]')
    expect(backLink).toBeTruthy()
  })
})

// ─────────────────────────────────────────────────────────────────────────────
// AC6 — Root path / redirects to /clientes
// ─────────────────────────────────────────────────────────────────────────────

describe('AC6 — Root / redirects to /clientes', () => {
  beforeEach(() => {
    setViewport(1280)
  })

  it('should redirect / and render the clientes-view', async () => {
    // GIVEN: The root path / is accessed
    // WHEN: The router processes the redirect
    await renderWithRouter('/')

    // THEN: The clientes-view is rendered (redirect resolved to /clientes)
    expect(document.querySelector('[data-testid="clientes-view"]')).toBeTruthy()
  })
})

// ─────────────────────────────────────────────────────────────────────────────
// AC7 — Accessibility: ARIA labels in Spanish and nav landmark
// ─────────────────────────────────────────────────────────────────────────────

describe('AC7 — Accessibility: ARIA labels in Spanish and nav landmark', () => {
  beforeEach(() => {
    setViewport(1280)
  })

  it('should have a <nav> landmark with aria-label="Navegación principal"', async () => {
    // GIVEN: The application shell is rendered
    // WHEN: The navigation component renders
    await renderWithRouter('/clientes')

    // THEN: A <nav> element with aria-label="Navegación principal" exists
    const navLandmark = document.querySelector('nav[aria-label="Navegación principal"]')
    expect(navLandmark).toBeTruthy()
  })

  it('should have aria-label="Clientes" on the Clientes navigation item (desktop)', async () => {
    // GIVEN: Desktop viewport
    // WHEN: The NavigationRail renders
    await renderWithRouter('/clientes')

    // THEN: An element with aria-label="Clientes" exists in the nav
    const navLandmark = document.querySelector('nav[aria-label="Navegación principal"]')
    expect(navLandmark?.querySelector('[aria-label="Clientes"]')).toBeTruthy()
  })

  it('should have aria-label="Contactos" on the Contactos navigation item (desktop)', async () => {
    // GIVEN: Desktop viewport
    // WHEN: The NavigationRail renders
    await renderWithRouter('/clientes')

    // THEN: An element with aria-label="Contactos" exists in the nav
    const navLandmark = document.querySelector('nav[aria-label="Navegación principal"]')
    expect(navLandmark?.querySelector('[aria-label="Contactos"]')).toBeTruthy()
  })

  it('should have aria-label="Clientes" on NavigationBar item (mobile)', async () => {
    // GIVEN: Mobile viewport
    setViewport(390)
    // WHEN: The NavigationBar renders
    await renderWithRouter('/clientes')

    // THEN: NavigationBar has aria-label="Clientes" on Clientes item
    const bar = document.querySelector('[data-testid="navigation-bar"]')
    expect(bar?.querySelector('[aria-label="Clientes"]')).toBeTruthy()
  })

  it('should have aria-label="Contactos" on NavigationBar item (mobile)', async () => {
    // GIVEN: Mobile viewport
    setViewport(390)
    // WHEN: The NavigationBar renders
    await renderWithRouter('/clientes')

    // THEN: NavigationBar has aria-label="Contactos" on Contactos item
    const bar = document.querySelector('[data-testid="navigation-bar"]')
    expect(bar?.querySelector('[aria-label="Contactos"]')).toBeTruthy()
  })
})
