/**
 * Story 1.2: Frontend Navigation Shell — Component Tests
 * ATDD - RED Phase (Tests intentionally failing — implementation not yet complete)
 *
 * Framework: Vitest + React Testing Library + @tanstack/react-router
 *
 * Acceptance Criteria covered:
 * - AC1: Desktop (>=1024px) shows NavigationRail with Clientes/Contactos (FR28)
 * - AC2: Mobile (<1024px) shows NavigationBar; items accessible and tappable (FR29)
 * - AC3: Direct /clientes and /contactos navigation renders correct views (FR30)
 * - AC4: Unknown route shows 404 not-found view with Spanish message
 * - AC5: All nav links have aria-label in Spanish; reachable via Tab (WCAG 2.1 AA)
 * - AC6: Active route link is visually highlighted (aria-current="page")
 */

import { describe, it, expect, vi, afterEach } from 'vitest';
import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import '@testing-library/jest-dom';
import { createMemoryHistory, createRouter, RouterProvider } from '@tanstack/react-router';

// NOTE: routeTree.gen.ts is auto-generated by @tanstack/router-plugin/vite.
// At RED phase, _app.tsx and its children do not exist yet — this import will
// cause a build/runtime failure, which is the expected RED condition.
import { routeTree } from '../../routeTree.gen';

// ─── Test Helpers ─────────────────────────────────────────────────────────────

function createTestRouter(initialPath: string) {
  const history = createMemoryHistory({ initialEntries: [initialPath] });
  return createRouter({ routeTree, history });
}

function renderAtPath(path: string) {
  const router = createTestRouter(path);
  return render(<RouterProvider router={router} />);
}

// Viewport mock helpers
function mockDesktopViewport() {
  Object.defineProperty(window, 'innerWidth', { value: 1280, writable: true, configurable: true });
  window.dispatchEvent(new Event('resize'));
}

function mockMobileViewport() {
  Object.defineProperty(window, 'innerWidth', { value: 375, writable: true, configurable: true });
  window.dispatchEvent(new Event('resize'));
}

afterEach(() => {
  vi.restoreAllMocks();
});

// ─── AC1: Desktop NavigationRail ─────────────────────────────────────────────

describe('AC1 - Desktop NavigationRail (viewport >=1024px)', () => {
  it('should render NavigationRail on desktop viewport', () => {
    // GIVEN: Desktop viewport (1280px)
    mockDesktopViewport();

    // WHEN: Application renders at /clientes
    renderAtPath('/clientes');

    // THEN: NavigationRail is visible
    expect(screen.getByTestId('navigation-rail')).toBeVisible();
  });

  it('should show Clientes entry in NavigationRail on desktop', () => {
    // GIVEN: Desktop viewport
    mockDesktopViewport();

    // WHEN: Application renders at /clientes
    renderAtPath('/clientes');

    // THEN: Clientes nav item is visible
    expect(screen.getByTestId('nav-item-clientes')).toBeVisible();
  });

  it('should show Contactos entry in NavigationRail on desktop', () => {
    // GIVEN: Desktop viewport
    mockDesktopViewport();

    // WHEN: Application renders at /clientes
    renderAtPath('/clientes');

    // THEN: Contactos nav item is visible
    expect(screen.getByTestId('nav-item-contactos')).toBeVisible();
  });

  it('should NOT render NavigationBar on desktop viewport', () => {
    // GIVEN: Desktop viewport (1280px)
    mockDesktopViewport();

    // WHEN: Application renders at /clientes
    renderAtPath('/clientes');

    // THEN: NavigationBar (mobile) is NOT visible
    const navBar = screen.queryByTestId('navigation-bar');
    expect(navBar).not.toBeVisible();
  });
});

// ─── AC2: Mobile NavigationBar ────────────────────────────────────────────────

describe('AC2 - Mobile NavigationBar (viewport <1024px)', () => {
  it('should render NavigationBar on mobile viewport', () => {
    // GIVEN: Mobile viewport (375px)
    mockMobileViewport();

    // WHEN: Application renders at /clientes
    renderAtPath('/clientes');

    // THEN: NavigationBar is visible
    expect(screen.getByTestId('navigation-bar')).toBeVisible();
  });

  it('should show Clientes item in NavigationBar on mobile', () => {
    // GIVEN: Mobile viewport
    mockMobileViewport();

    // WHEN: Application renders at /clientes
    renderAtPath('/clientes');

    // THEN: Clientes nav item is visible and tappable
    expect(screen.getByTestId('nav-item-clientes')).toBeVisible();
  });

  it('should show Contactos item in NavigationBar on mobile', () => {
    // GIVEN: Mobile viewport
    mockMobileViewport();

    // WHEN: Application renders at /clientes
    renderAtPath('/clientes');

    // THEN: Contactos nav item is visible and tappable
    expect(screen.getByTestId('nav-item-contactos')).toBeVisible();
  });

  it('should NOT render NavigationRail on mobile viewport', () => {
    // GIVEN: Mobile viewport (375px)
    mockMobileViewport();

    // WHEN: Application renders at /clientes
    renderAtPath('/clientes');

    // THEN: NavigationRail is NOT visible
    const navRail = screen.queryByTestId('navigation-rail');
    expect(navRail).not.toBeVisible();
  });
});

// ─── AC3: Deep Linking ────────────────────────────────────────────────────────

describe('AC3 - Deep Linking to /clientes and /contactos (FR30)', () => {
  it('should render ClientesPlaceholder when navigating directly to /clientes', () => {
    // GIVEN: User navigates directly to /clientes
    // WHEN: The page renders
    renderAtPath('/clientes');

    // THEN: ClientesPlaceholder is displayed (heading "Clientes")
    expect(screen.getByTestId('clientes-placeholder')).toBeInTheDocument();
  });

  it('should render ContactosPlaceholder when navigating directly to /contactos', () => {
    // GIVEN: User navigates directly to /contactos
    // WHEN: The page renders
    renderAtPath('/contactos');

    // THEN: ContactosPlaceholder is displayed (heading "Contactos")
    expect(screen.getByTestId('contactos-placeholder')).toBeInTheDocument();
  });

  it('should display Spanish heading "Clientes" in the Clientes view', () => {
    // GIVEN: User is on /clientes
    renderAtPath('/clientes');

    // THEN: Spanish heading is rendered
    expect(screen.getByRole('heading', { name: /clientes/i })).toBeInTheDocument();
  });

  it('should display Spanish heading "Contactos" in the Contactos view', () => {
    // GIVEN: User is on /contactos
    renderAtPath('/contactos');

    // THEN: Spanish heading is rendered
    expect(screen.getByRole('heading', { name: /contactos/i })).toBeInTheDocument();
  });
});

// ─── AC4: Unknown Route — 404 Not Found ───────────────────────────────────────

describe('AC4 - Unknown Route shows 404 Not Found view', () => {
  it('should render not-found view when navigating to an unknown route', () => {
    // GIVEN: User navigates to /unknown
    // WHEN: The page renders
    renderAtPath('/unknown-route');

    // THEN: Not-found view is rendered
    expect(screen.getByTestId('not-found-view')).toBeInTheDocument();
  });

  it('should display "Pagina no encontrada" message in Spanish', () => {
    // GIVEN: User navigates to an unknown route
    renderAtPath('/this-does-not-exist');

    // THEN: Spanish not-found message is shown
    expect(screen.getByTestId('not-found-message')).toHaveTextContent('Página no encontrada');
  });

  it('should display a link back to Clientes on the not-found view', () => {
    // GIVEN: User is on the 404 page
    renderAtPath('/nonexistent');

    // THEN: A back link to Clientes is available
    expect(screen.getByTestId('not-found-back-link')).toBeInTheDocument();
  });
});

// ─── AC5: Accessibility — WCAG 2.1 AA ────────────────────────────────────────

describe('AC5 - Accessibility: aria-labels in Spanish and keyboard navigation', () => {
  it('navigation landmark should have aria-label "Navegacion principal"', () => {
    // GIVEN: Navigation is rendered
    renderAtPath('/clientes');

    // THEN: nav element has correct accessible label in Spanish
    expect(screen.getByRole('navigation', { name: 'Navegación principal' })).toBeInTheDocument();
  });

  it('Clientes nav link should have aria-label "Ir a Clientes"', () => {
    // GIVEN: Navigation is rendered
    renderAtPath('/clientes');

    // THEN: Clientes link has correct Spanish aria-label
    expect(screen.getByTestId('nav-item-clientes')).toHaveAttribute('aria-label', 'Ir a Clientes');
  });

  it('Contactos nav link should have aria-label "Ir a Contactos"', () => {
    // GIVEN: Navigation is rendered
    renderAtPath('/clientes');

    // THEN: Contactos link has correct Spanish aria-label
    expect(screen.getByTestId('nav-item-contactos')).toHaveAttribute(
      'aria-label',
      'Ir a Contactos',
    );
  });

  it('Clientes nav link should be reachable via Tab key', async () => {
    // GIVEN: Navigation is rendered
    renderAtPath('/clientes');
    const user = userEvent.setup();

    // WHEN: User navigates via Tab
    await user.tab();

    // THEN: A nav item receives focus (keyboard accessible)
    const clientesItem = screen.getByTestId('nav-item-clientes');
    const contactosItem = screen.getByTestId('nav-item-contactos');
    const focused = document.activeElement;

    const navItemFocused =
      focused === clientesItem ||
      focused === contactosItem ||
      clientesItem.contains(focused) ||
      contactosItem.contains(focused);

    expect(navItemFocused).toBe(true);
  });
});

// ─── AC6: Active Route Highlighting ──────────────────────────────────────────

describe('AC6 - Active route link is highlighted', () => {
  it('Clientes link should have aria-current="page" when on /clientes', () => {
    // GIVEN: User is on /clientes
    renderAtPath('/clientes');

    // THEN: Clientes nav item is marked as current page
    expect(screen.getByTestId('nav-item-clientes')).toHaveAttribute('aria-current', 'page');
  });

  it('Contactos link should have aria-current="page" when on /contactos', () => {
    // GIVEN: User is on /contactos
    renderAtPath('/contactos');

    // THEN: Contactos nav item is marked as current page
    expect(screen.getByTestId('nav-item-contactos')).toHaveAttribute('aria-current', 'page');
  });

  it('Clientes link should NOT have aria-current="page" when on /contactos', () => {
    // GIVEN: User is on /contactos
    renderAtPath('/contactos');

    // THEN: Clientes nav item is NOT marked as current
    expect(screen.getByTestId('nav-item-clientes')).not.toHaveAttribute('aria-current', 'page');
  });

  it('Contactos link should NOT have aria-current="page" when on /clientes', () => {
    // GIVEN: User is on /clientes
    renderAtPath('/clientes');

    // THEN: Contactos nav item is NOT marked as current
    expect(screen.getByTestId('nav-item-contactos')).not.toHaveAttribute('aria-current', 'page');
  });

  it('Clientes link should have nav-active class when on /clientes', () => {
    // GIVEN: User is on /clientes
    renderAtPath('/clientes');

    // THEN: Active class is applied for visual highlighting
    expect(screen.getByTestId('nav-item-clientes')).toHaveClass('nav-active');
  });

  it('Contactos link should have nav-active class when on /contactos', () => {
    // GIVEN: User is on /contactos
    renderAtPath('/contactos');

    // THEN: Active class is applied for visual highlighting
    expect(screen.getByTestId('nav-item-contactos')).toHaveClass('nav-active');
  });
});

// ─── Root Redirect ────────────────────────────────────────────────────────────

describe('Root redirect to /clientes', () => {
  it('should redirect from / to /clientes', async () => {
    // GIVEN: User navigates to the root URL
    const router = createTestRouter('/');
    render(<RouterProvider router={router} />);

    // THEN: Router redirects to /clientes and renders the Clientes view
    expect(await screen.findByTestId('clientes-placeholder')).toBeInTheDocument();
  });
});
