import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'
import { render, screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'

/**
 * Component Tests (Vitest + RTL): Story 1.2 — Frontend Navigation Shell
 *
 * RED PHASE: These tests are written BEFORE the navigation shell exists.
 * They will FAIL until __root.tsx, _app.tsx, and route stubs are implemented.
 *
 * Covers:
 *   AC1 — NavigationRail (desktop) visible on left with "Clientes" + "Contactos" entries
 *   AC2 — NavigationBar (mobile) visible at bottom on viewports < 1024px
 *   AC3 — Deep linking: /clientes and /contactos render directly without redirection
 *   AC4 — Unknown route renders graceful 404 view (no crash, no blank screen)
 *   AC5 — nav landmark has aria-label="Navegación principal"; Spanish labels visible
 *   AC6 — Active/selected state on nav item reflects current route
 *
 * Test strategy:
 *   - TanStack Router createMemoryHistory / createRouter for isolated route tests
 *   - Object.defineProperty(window, 'innerWidth') to simulate mobile/desktop breakpoint
 *   - data-testid selectors only — no fragile CSS class selectors
 *   - No hard waits — RTL's queries are synchronous or use findBy* for async
 */

// ---------------------------------------------------------------------------
// Helpers — TanStack Router in-memory setup
// ---------------------------------------------------------------------------

/**
 * Creates an in-memory TanStack Router pointing at the given initial URL.
 * Uses dynamic imports so the module can be mocked without circular refs.
 *
 * NOTE: In RED phase these imports will fail because the route files do not
 * exist yet.  The failure proves the test is correctly RED.
 */
async function createTestRouter(initialPath: string = '/') {
  const { createMemoryHistory, createRouter } = await import('@tanstack/react-router')
  // routeTree is generated by the Vite plugin — import it dynamically
  const { routeTree } = await import('../../routeTree.gen')

  const history = createMemoryHistory({ initialEntries: [initialPath] })
  const router = createRouter({ routeTree, history })
  return router
}

/**
 * Renders the RouterProvider with the given router.
 * Wraps with QueryProvider to support TanStack Query hooks used in route components.
 * Returns RTL utilities.
 */
async function renderWithRouter(initialPath: string = '/') {
  const { RouterProvider } = await import('@tanstack/react-router')
  const { QueryProvider } = await import('../../app/providers/QueryProvider')
  const router = await createTestRouter(initialPath)
  await router.load()
  return render(
    <QueryProvider>
      <RouterProvider router={router} />
    </QueryProvider>
  )
}

// ---------------------------------------------------------------------------
// Viewport helpers
// ---------------------------------------------------------------------------

function setDesktopViewport() {
  Object.defineProperty(window, 'innerWidth', {
    writable: true,
    configurable: true,
    value: 1280,
  })
  window.dispatchEvent(new Event('resize'))
}

function setMobileViewport() {
  Object.defineProperty(window, 'innerWidth', {
    writable: true,
    configurable: true,
    value: 390,
  })
  window.dispatchEvent(new Event('resize'))
}

// ---------------------------------------------------------------------------
// AC1 — NavigationRail (desktop)
// ---------------------------------------------------------------------------

describe('AC1 — NavigationRail renders on desktop viewport', () => {

  beforeEach(() => setDesktopViewport())
  afterEach(() => setDesktopViewport()) // restore

  it('[P0] NavigationRail wrapper is present in the DOM on desktop', async () => {
    // GIVEN: Application is loaded on a desktop browser (>= 1024px)
    // WHEN: The root shell renders
    await renderWithRouter('/')

    // THEN: The NavigationRail wrapper exists with the correct data-testid
    expect(screen.getByTestId('nav-rail')).toBeDefined()
  })

  it('[P0] NavigationRail contains "Clientes" label in Spanish', async () => {
    // GIVEN: Desktop viewport is active and the app is loaded
    // WHEN: The navigation shell renders
    await renderWithRouter('/')

    // THEN: A nav item with label "Clientes" is visible
    const clientesItem = screen.getByTestId('nav-item-clientes')
    expect(clientesItem).toBeDefined()
    expect(clientesItem.textContent).toContain('Clientes')
  })

  it('[P0] NavigationRail contains "Contactos" label in Spanish', async () => {
    // GIVEN: Desktop viewport is active and the app is loaded
    // WHEN: The navigation shell renders
    await renderWithRouter('/')

    // THEN: A nav item with label "Contactos" is visible
    const contactosItem = screen.getByTestId('nav-item-contactos')
    expect(contactosItem).toBeDefined()
    expect(contactosItem.textContent).toContain('Contactos')
  })

  it('[P1] Clicking "Clientes" nav item changes route to /clientes', async () => {
    // GIVEN: Desktop viewport; user is on /
    const user = userEvent.setup()
    const { RouterProvider } = await import('@tanstack/react-router')
    const router = await createTestRouter('/')
    await router.load()
    render(<RouterProvider router={router} />)

    // WHEN: User clicks the "Clientes" nav item
    const clientesItem = screen.getByTestId('nav-item-clientes')
    await user.click(clientesItem)

    // THEN: Router location changes to /clientes (no full page reload in SPA)
    expect(router.state.location.pathname).toBe('/clientes')
  })

  it('[P1] Clicking "Contactos" nav item changes route to /contactos', async () => {
    // GIVEN: Desktop viewport; user is on /
    const user = userEvent.setup()
    const { RouterProvider } = await import('@tanstack/react-router')
    const router = await createTestRouter('/')
    await router.load()
    render(<RouterProvider router={router} />)

    // WHEN: User clicks the "Contactos" nav item
    const contactosItem = screen.getByTestId('nav-item-contactos')
    await user.click(contactosItem)

    // THEN: Router location changes to /contactos
    expect(router.state.location.pathname).toBe('/contactos')
  })
})

// ---------------------------------------------------------------------------
// AC2 — NavigationBar (mobile, < 1024px)
// ---------------------------------------------------------------------------

describe('AC2 — NavigationBar renders on mobile viewport (< 1024px)', () => {

  beforeEach(() => setMobileViewport())
  afterEach(() => setDesktopViewport())

  it('[P0] NavigationBar wrapper is present in the DOM on mobile', async () => {
    // GIVEN: Application is loaded on a mobile browser viewport (< 1024px)
    // WHEN: The root shell renders
    await renderWithRouter('/')

    // THEN: The NavigationBar wrapper exists with the correct data-testid
    expect(screen.getByTestId('nav-bar')).toBeDefined()
  })

  it('[P1] NavigationBar contains "Clientes" item on mobile', async () => {
    // GIVEN: Mobile viewport (< 1024px)
    // WHEN: The navigation shell renders
    await renderWithRouter('/')

    // THEN: A nav item with label "Clientes" is visible in the bottom bar
    expect(screen.getByTestId('nav-item-clientes')).toBeDefined()
  })

  it('[P1] NavigationBar contains "Contactos" item on mobile', async () => {
    // GIVEN: Mobile viewport (< 1024px)
    // WHEN: The navigation shell renders
    await renderWithRouter('/')

    // THEN: A nav item with label "Contactos" is visible in the bottom bar
    expect(screen.getByTestId('nav-item-contactos')).toBeDefined()
  })
})

// ---------------------------------------------------------------------------
// AC3 — Deep Linking
// ---------------------------------------------------------------------------

describe('AC3 — Deep linking: /clientes and /contactos render directly', () => {

  beforeEach(() => setDesktopViewport())

  it('[P0] Navigating directly to /clientes renders Clientes view without redirect', async () => {
    // GIVEN: The user types /clientes directly in the URL bar
    // WHEN: Router initializes at /clientes
    const { RouterProvider } = await import('@tanstack/react-router')
    const router = await createTestRouter('/clientes')
    await router.load()
    render(<RouterProvider router={router} />)

    // THEN: The URL remains /clientes (no redirect to home)
    expect(router.state.location.pathname).toBe('/clientes')
    // AND: The Clientes view content is rendered
    expect(screen.getByTestId('clientes-view')).toBeDefined()
  })

  it('[P0] Navigating directly to /contactos renders Contactos view without redirect', async () => {
    // GIVEN: The user types /contactos directly in the URL bar
    // WHEN: Router initializes at /contactos
    const { RouterProvider } = await import('@tanstack/react-router')
    const { QueryProvider } = await import('../../app/providers/QueryProvider')
    const router = await createTestRouter('/contactos')
    await router.load()
    render(
      <QueryProvider>
        <RouterProvider router={router} />
      </QueryProvider>
    )

    // THEN: The URL remains /contactos (no redirect)
    expect(router.state.location.pathname).toBe('/contactos')
    // AND: The Contactos view content is rendered
    expect(screen.getByTestId('contactos-view')).toBeDefined()
  })

  it('[P1] Index route / redirects to /clientes automatically', async () => {
    // GIVEN: The root URL is visited
    // WHEN: Router initializes at /
    const { RouterProvider } = await import('@tanstack/react-router')
    const router = await createTestRouter('/')
    await router.load()
    render(<RouterProvider router={router} />)

    // THEN: The router redirects to /clientes
    expect(router.state.location.pathname).toBe('/clientes')
  })
})

// ---------------------------------------------------------------------------
// AC4 — 404 Not-Found Route
// ---------------------------------------------------------------------------

describe('AC4 — Unknown route renders graceful 404 view', () => {

  beforeEach(() => setDesktopViewport())

  it('[P0] Navigating to /unknown renders a not-found view (no crash, no blank screen)', async () => {
    // GIVEN: A user navigates to a route that does not exist
    // WHEN: Router initializes at /unknown
    const { RouterProvider } = await import('@tanstack/react-router')
    const router = await createTestRouter('/unknown')
    await router.load()
    const { container } = render(<RouterProvider router={router} />)

    // THEN: A 404 view is displayed
    expect(screen.getByTestId('not-found-view')).toBeDefined()
    // AND: The container has meaningful content (not blank)
    expect(container.textContent?.trim().length).toBeGreaterThan(0)
  })

  it('[P1] 404 view contains a back link that navigates to /clientes', async () => {
    // GIVEN: User lands on a 404 page
    const user = userEvent.setup()
    const { RouterProvider } = await import('@tanstack/react-router')
    const router = await createTestRouter('/unknown')
    await router.load()
    render(<RouterProvider router={router} />)

    // WHEN: The user clicks the back link
    const backLink = screen.getByTestId('not-found-back-link')
    expect(backLink).toBeDefined()
    await user.click(backLink)

    // THEN: The router navigates to /clientes
    expect(router.state.location.pathname).toBe('/clientes')
  })

  it('[P2] 404 view displays "Página no encontrada" message in Spanish', async () => {
    // GIVEN: User navigates to a non-existent route
    // WHEN: Router initializes at /ruta-inexistente
    const { RouterProvider } = await import('@tanstack/react-router')
    const router = await createTestRouter('/ruta-inexistente')
    await router.load()
    render(<RouterProvider router={router} />)

    // THEN: The page shows the Spanish not-found message
    expect(screen.getByTestId('not-found-view').textContent).toContain('Página no encontrada')
  })
})

// ---------------------------------------------------------------------------
// AC5 — Accessibility (WCAG 2.1 AA)
// ---------------------------------------------------------------------------

describe('AC5 — Accessibility: nav landmark and Spanish labels', () => {

  beforeEach(() => setDesktopViewport())

  it('[P0] nav element has aria-label="Navegación principal"', async () => {
    // GIVEN: The navigation is rendered on desktop
    // WHEN: The page loads
    await renderWithRouter('/')

    // THEN: At least one <nav> with aria-label="Navegación principal" is in the DOM
    const navLandmark = document.querySelector('nav[aria-label="Navegación principal"]')
    expect(navLandmark).not.toBeNull()
  })

  it('[P1] "Clientes" nav item displays visible Spanish text label', async () => {
    // GIVEN: The navigation is rendered
    // WHEN: The app loads on desktop
    await renderWithRouter('/')

    // THEN: The Clientes item has the Spanish label "Clientes" (not "Clients")
    const clientesItem = screen.getByTestId('nav-item-clientes')
    expect(clientesItem.textContent).toContain('Clientes')
    expect(clientesItem.textContent).not.toContain('Clients')
  })

  it('[P1] "Contactos" nav item displays visible Spanish text label', async () => {
    // GIVEN: The navigation is rendered
    // WHEN: The app loads on desktop
    await renderWithRouter('/')

    // THEN: The Contactos item has the Spanish label "Contactos" (not "Contacts")
    const contactosItem = screen.getByTestId('nav-item-contactos')
    expect(contactosItem.textContent).toContain('Contactos')
    expect(contactosItem.textContent).not.toContain('Contacts')
  })
})

// ---------------------------------------------------------------------------
// AC6 — Active/Selected State
// ---------------------------------------------------------------------------

describe('AC6 — Active nav item reflects current route', () => {

  beforeEach(() => setDesktopViewport())

  it('[P0] "Clientes" item has data-active="true" when on /clientes', async () => {
    // GIVEN: The user is on /clientes
    // WHEN: Navigation renders
    await renderWithRouter('/clientes')

    // THEN: The "Clientes" nav item has the active state attribute
    const clientesItem = screen.getByTestId('nav-item-clientes')
    expect(clientesItem.getAttribute('data-active')).toBe('true')
  })

  it('[P0] "Contactos" item has data-active="true" when on /contactos', async () => {
    // GIVEN: The user is on /contactos
    // WHEN: Navigation renders
    await renderWithRouter('/contactos')

    // THEN: The "Contactos" nav item has the active state attribute
    const contactosItem = screen.getByTestId('nav-item-contactos')
    expect(contactosItem.getAttribute('data-active')).toBe('true')
  })

  it('[P1] "Contactos" item does NOT have data-active="true" when on /clientes', async () => {
    // GIVEN: The user is on /clientes
    // WHEN: Navigation renders
    await renderWithRouter('/clientes')

    // THEN: The "Contactos" item is NOT in active state
    const contactosItem = screen.getByTestId('nav-item-contactos')
    expect(contactosItem.getAttribute('data-active')).not.toBe('true')
  })

  it('[P1] "Clientes" item does NOT have data-active="true" when on /contactos', async () => {
    // GIVEN: The user is on /contactos
    // WHEN: Navigation renders
    await renderWithRouter('/contactos')

    // THEN: The "Clientes" item is NOT in active state
    const clientesItem = screen.getByTestId('nav-item-clientes')
    expect(clientesItem.getAttribute('data-active')).not.toBe('true')
  })
})
