/**
 * Story 1.2: Frontend Navigation Shell
 * Component Tests — __root.tsx
 *
 * RED Phase: These tests FAIL until implementation is complete.
 * The root layout must render LayoutBase shell with NavigationRail (desktop)
 * and NavigationBar (mobile), wired to TanStack Router.
 *
 * AC1, AC4 — Navigation shell renders with correct components per viewport
 */

import { describe, it, expect } from 'vitest'
import { render, screen } from '@testing-library/react'
import { createRouter, createMemoryHistory } from '@tanstack/react-router'

// NOTE: routeTree.gen.ts is auto-generated by TanStack Router plugin.
// This import will FAIL (RED) until the routes are created and the
// plugin regenerates the route tree.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-expect-error — routeTree.gen.ts does not exist yet (RED phase)
import { routeTree } from '../../routeTree.gen'

function createTestRouter(initialPath: string) {
  return createRouter({
    routeTree,
    history: createMemoryHistory({ initialEntries: [initialPath] }),
  })
}

describe('__root.tsx — Root layout shell', () => {
  it('should render the root layout without crashing on /clientes', () => {
    // GIVEN: A test router is initialized at /clientes
    const router = createTestRouter('/clientes')

    // WHEN: The root layout is rendered
    const { container } = render(
      // RouterProvider is the entry point for TanStack Router in tests
      // This will fail until RouterProvider and routeTree.gen.ts are in place
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      <(router as any).RouterProvider router={router} />,
    )

    // THEN: The container is mounted (not blank)
    expect(container.firstChild).not.toBeNull()
  })

  it('should render the NavigationRail data-testid element at desktop viewport', () => {
    // GIVEN: A test router at /clientes with a desktop viewport context
    const router = createTestRouter('/clientes')

    // WHEN: The root layout is rendered
    render(
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      <(router as any).RouterProvider router={router} />,
    )

    // THEN: The NavigationRail element with data-testid is present in the DOM
    // This FAILS until __root.tsx renders <LayoutBase> with NavigationRail
    const navRail = screen.queryByTestId('navigation-rail')
    expect(navRail).not.toBeNull()
  })

  it('should render the NavigationBar data-testid element (hidden at desktop, present in DOM)', () => {
    // GIVEN: A test router at /clientes
    const router = createTestRouter('/clientes')

    // WHEN: The root layout is rendered
    render(
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      <(router as any).RouterProvider router={router} />,
    )

    // THEN: The NavigationBar element with data-testid is present in the DOM
    // (visibility is controlled by CSS/Tailwind responsive classes, not DOM presence)
    // This FAILS until __root.tsx renders <LayoutBase> with NavigationBar
    const navBar = screen.queryByTestId('navigation-bar')
    expect(navBar).not.toBeNull()
  })

  it('should render the Navbar with product name "Siesa Agents"', () => {
    // GIVEN: A test router at /clientes
    const router = createTestRouter('/clientes')

    // WHEN: The root layout renders
    render(
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      <(router as any).RouterProvider router={router} />,
    )

    // THEN: The product name "Siesa Agents" is visible in the Navbar
    // This FAILS until __root.tsx sets productName="Siesa Agents" on <Navbar>
    expect(screen.getByText('Siesa Agents')).toBeInTheDocument()
  })
})
