/**
 * Story 1.2: Frontend Navigation Shell — Expanded Automation Coverage
 * Epic 1: Project Foundation & Application Shell
 *
 * Generated by TEA testarch-automate (BMad-Integrated mode)
 * Expands beyond ATDD with: dynamic resize, browser history, trailing slash,
 * rapid navigation, ARIA attributes, and error boundary edge cases.
 */

import { test, expect } from '@playwright/test';

// ─────────────────────────────────────────────────────────────────────────────
// Dynamic viewport resize: desktop ↔ mobile transition
// ─────────────────────────────────────────────────────────────────────────────

test.describe('Dynamic viewport resize transitions', () => {
  test('should switch from NavigationRail to NavigationBar when viewport shrinks below 1024px', async ({
    page,
  }) => {
    // GIVEN: The app is loaded at desktop size
    await page.setViewportSize({ width: 1280, height: 720 });
    await page.goto('/clientes');
    await expect(page.locator('[data-testid="navigation-rail"]')).toBeVisible();

    // WHEN: The viewport is resized to mobile width
    await page.setViewportSize({ width: 375, height: 812 });

    // THEN: NavigationBar appears and NavigationRail is gone
    await expect(page.locator('[data-testid="navigation-bar"]')).toBeVisible();
    await expect(page.locator('[data-testid="navigation-rail"]')).toBeHidden();
  });

  test('should switch from NavigationBar to NavigationRail when viewport grows above 1024px', async ({
    page,
  }) => {
    // GIVEN: The app is loaded at mobile size
    await page.setViewportSize({ width: 375, height: 812 });
    await page.goto('/clientes');
    await expect(page.locator('[data-testid="navigation-bar"]')).toBeVisible();

    // WHEN: The viewport is resized to desktop width
    await page.setViewportSize({ width: 1280, height: 720 });

    // THEN: NavigationRail appears and NavigationBar is gone
    await expect(page.locator('[data-testid="navigation-rail"]')).toBeVisible();
    await expect(page.locator('[data-testid="navigation-bar"]')).toBeHidden();
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// Browser history navigation (back / forward buttons)
// ─────────────────────────────────────────────────────────────────────────────

test.describe('Browser history navigation', () => {
  test.use({ viewport: { width: 1280, height: 720 } });

  test('should navigate back to /clientes after going forward to /contactos via browser back button', async ({
    page,
  }) => {
    // GIVEN: The user visits /clientes then navigates to /contactos
    await page.goto('/clientes');
    await page.locator('[data-testid="nav-item-contactos"]').click();
    await expect(page).toHaveURL('/contactos');

    // WHEN: The user presses the browser back button
    await page.goBack();

    // THEN: The URL is /clientes and the Clientes view is rendered
    await expect(page).toHaveURL('/clientes');
    await expect(page.locator('[data-testid="clientes-view"]')).toBeVisible();
  });

  test('should restore /contactos after pressing browser forward button', async ({ page }) => {
    // GIVEN: The user visited /clientes then /contactos, then went back
    await page.goto('/clientes');
    await page.locator('[data-testid="nav-item-contactos"]').click();
    await expect(page).toHaveURL('/contactos');
    await page.goBack();
    await expect(page).toHaveURL('/clientes');

    // WHEN: The user presses the browser forward button
    await page.goForward();

    // THEN: The URL is /contactos and the active nav item is updated
    await expect(page).toHaveURL('/contactos');
    await expect(page.locator('[data-testid="nav-item-contactos"]')).toHaveAttribute(
      'data-active',
      'true',
    );
  });

  test('should restore correct active nav state after browser back navigation', async ({ page }) => {
    // GIVEN: The user is on /contactos (arrived via nav click from /clientes)
    await page.goto('/clientes');
    await page.locator('[data-testid="nav-item-contactos"]').click();
    await expect(page).toHaveURL('/contactos');

    // WHEN: The user goes back to /clientes
    await page.goBack();
    await expect(page).toHaveURL('/clientes');

    // THEN: Clientes is active and Contactos is inactive
    await expect(page.locator('[data-testid="nav-item-clientes"]')).toHaveAttribute(
      'data-active',
      'true',
    );
    await expect(page.locator('[data-testid="nav-item-contactos"]')).toHaveAttribute(
      'data-active',
      'false',
    );
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// Trailing slash handling
// ─────────────────────────────────────────────────────────────────────────────

test.describe('Trailing slash URL handling', () => {
  test('should handle /clientes/ with trailing slash gracefully', async ({ page }) => {
    // GIVEN: The user navigates to /clientes/ with a trailing slash
    // WHEN: The page loads
    await page.goto('/clientes/');

    // THEN: The URL contains /clientes (redirect or direct render — either is acceptable)
    await expect(page).toHaveURL(/\/clientes/);
    // AND: The 404 view is NOT shown
    await expect(page.locator('[data-testid="not-found-view"]')).toBeHidden();
  });

  test('should handle /contactos/ with trailing slash gracefully', async ({ page }) => {
    // GIVEN: The user navigates to /contactos/ with a trailing slash
    await page.goto('/contactos/');

    // THEN: The URL contains /contactos (redirect or direct render — either is acceptable)
    await expect(page).toHaveURL(/\/contactos/);
    // AND: The 404 view is NOT shown
    await expect(page.locator('[data-testid="not-found-view"]')).toBeHidden();
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// Rapid sequential navigation (stress test)
// ─────────────────────────────────────────────────────────────────────────────

test.describe('Rapid sequential navigation', () => {
  test.use({ viewport: { width: 1280, height: 720 } });

  test('should correctly update URL and active state after rapid consecutive clicks', async ({
    page,
  }) => {
    // GIVEN: The app is loaded
    await page.goto('/clientes');

    // WHEN: The user clicks Contactos, then Clientes, then Contactos rapidly
    await page.locator('[data-testid="nav-item-contactos"]').click();
    await page.locator('[data-testid="nav-item-clientes"]').click();
    await page.locator('[data-testid="nav-item-contactos"]').click();

    // THEN: The final URL and active state reflect the last click (/contactos)
    await expect(page).toHaveURL('/contactos');
    await expect(page.locator('[data-testid="nav-item-contactos"]')).toHaveAttribute(
      'data-active',
      'true',
    );
    await expect(page.locator('[data-testid="nav-item-clientes"]')).toHaveAttribute(
      'data-active',
      'false',
    );
  });

  test('should render correct view content after rapid navigation', async ({ page }) => {
    // GIVEN: The user starts at /clientes and rapidly navigates
    await page.goto('/clientes');
    await page.locator('[data-testid="nav-item-contactos"]').click();
    await page.locator('[data-testid="nav-item-clientes"]').click();

    // THEN: The final view is Clientes
    await expect(page.locator('[data-testid="clientes-view"]')).toBeVisible();
    await expect(page.locator('[data-testid="contactos-view"]')).not.toBeVisible();
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// ARIA attributes and accessibility attributes edge cases
// ─────────────────────────────────────────────────────────────────────────────

test.describe('ARIA attribute edge cases', () => {
  test.use({ viewport: { width: 1280, height: 720 } });

  test('should have aria-current="page" on active Clientes nav item', async ({ page }) => {
    // GIVEN: The user is on /clientes
    await page.goto('/clientes');

    // THEN: The active nav item has aria-current="page" for screen readers
    await expect(page.locator('[data-testid="nav-item-clientes"]')).toHaveAttribute(
      'aria-current',
      'page',
    );
  });

  test('should NOT have aria-current on inactive Contactos nav item', async ({ page }) => {
    // GIVEN: The user is on /clientes
    await page.goto('/clientes');

    // THEN: The inactive Contactos item does NOT have aria-current
    const contactosItem = page.locator('[data-testid="nav-item-contactos"]');
    const ariaCurrent = await contactosItem.getAttribute('aria-current');
    // aria-current should be absent or not "page" when the item is not active
    expect(ariaCurrent).not.toBe('page');
  });

  test('should have aria-current="page" on active Contactos nav item', async ({ page }) => {
    // GIVEN: The user is on /contactos
    await page.goto('/contactos');

    // THEN: Contactos nav item has aria-current="page"
    await expect(page.locator('[data-testid="nav-item-contactos"]')).toHaveAttribute(
      'aria-current',
      'page',
    );
  });

  test('should have aria-label on the NavigationRail container', async ({ page }) => {
    // GIVEN: The app is loaded on desktop
    await page.goto('/clientes');

    // THEN: The nav container has an accessible aria-label
    const navRail = page.locator('[data-testid="navigation-rail"]');
    const ariaLabel = await navRail.getAttribute('aria-label');
    expect(ariaLabel).toBeTruthy();
    expect(ariaLabel!.length).toBeGreaterThan(0);
  });

  test('should have aria-label on the NavigationBar container (mobile)', async ({ page }) => {
    // GIVEN: The app is loaded on mobile
    await page.setViewportSize({ width: 375, height: 812 });
    await page.goto('/clientes');

    // THEN: The navigation bar has an accessible aria-label
    const navBar = page.locator('[data-testid="navigation-bar"]');
    const ariaLabel = await navBar.getAttribute('aria-label');
    expect(ariaLabel).toBeTruthy();
    expect(ariaLabel!.length).toBeGreaterThan(0);
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// 404 page edge cases
// ─────────────────────────────────────────────────────────────────────────────

test.describe('404 not-found page edge cases', () => {
  test('should navigate back to /clientes when clicking the back link on the 404 page', async ({
    page,
  }) => {
    // GIVEN: The user lands on an unknown route
    await page.goto('/ruta-completamente-desconocida');
    await expect(page.locator('[data-testid="not-found-view"]')).toBeVisible();

    // WHEN: The user clicks the "back to clientes" link
    await page.locator('[data-testid="not-found-back-link"]').click();

    // THEN: The user is navigated to /clientes
    await expect(page).toHaveURL('/clientes');
    await expect(page.locator('[data-testid="clientes-view"]')).toBeVisible();
  });

  test('should show 404 for deep unknown paths', async ({ page }) => {
    // GIVEN: The user navigates to a deeply nested unknown path
    await page.goto('/a/b/c/d/e');

    // THEN: The 404 view is still shown gracefully
    await expect(page.locator('[data-testid="not-found-view"]')).toBeVisible();
    await expect(page.locator('[data-testid="not-found-message"]')).toContainText(
      'Página no encontrada',
    );
  });

  test('should show 404 for path with special characters', async ({ page }) => {
    // GIVEN: The user navigates to a path with special characters
    await page.goto('/ruta-especial-123');

    // THEN: The 404 view is shown (not an application crash)
    await expect(page.locator('[data-testid="not-found-view"]')).toBeVisible();
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// Navigation shell persistence and layout integrity
// ─────────────────────────────────────────────────────────────────────────────

test.describe('Navigation shell layout integrity', () => {
  test.use({ viewport: { width: 1280, height: 720 } });

  test('should display the main content area alongside the NavigationRail at all times', async ({
    page,
  }) => {
    // GIVEN: The user is on /clientes
    await page.goto('/clientes');

    // THEN: Both the NavigationRail and main-content area are visible simultaneously
    await expect(page.locator('[data-testid="navigation-rail"]')).toBeVisible();
    await expect(page.locator('[data-testid="main-content"]')).toBeVisible();
  });

  test('should show Clientes content in main-content area not inside NavigationRail', async ({
    page,
  }) => {
    // GIVEN: The user navigates to /clientes
    await page.goto('/clientes');

    // THEN: The clientes-view is inside main-content, not inside navigation-rail
    const mainContent = page.locator('[data-testid="main-content"]');
    await expect(mainContent.locator('[data-testid="clientes-view"]')).toBeVisible();

    // AND: The navigation-rail does NOT contain the clientes-view
    const navRail = page.locator('[data-testid="navigation-rail"]');
    await expect(navRail.locator('[data-testid="clientes-view"]')).toHaveCount(0);
  });

  test('should keep NavigationRail visible when content changes after navigation', async ({
    page,
  }) => {
    // GIVEN: The user starts at /clientes and the rail is visible
    await page.goto('/clientes');
    await expect(page.locator('[data-testid="navigation-rail"]')).toBeVisible();

    // WHEN: The user navigates to /contactos
    await page.locator('[data-testid="nav-item-contactos"]').click();
    await expect(page).toHaveURL('/contactos');

    // THEN: The NavigationRail persists and the Contactos view is now in the main area
    await expect(page.locator('[data-testid="navigation-rail"]')).toBeVisible();
    await expect(page.locator('[data-testid="contactos-view"]')).toBeVisible();
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// Mobile navigation tap interactions
// ─────────────────────────────────────────────────────────────────────────────

test.describe('Mobile NavigationBar tap interactions', () => {
  test.use({ viewport: { width: 375, height: 812 } });

  test('should navigate to /contactos when tapping Contactos in the NavigationBar', async ({
    page,
  }) => {
    // GIVEN: The user is on /clientes on mobile
    await page.goto('/clientes');
    await expect(page.locator('[data-testid="navigation-bar"]')).toBeVisible();

    // WHEN: The user taps the Contactos nav item
    await page.locator('[data-testid="nav-item-contactos"]').tap();

    // THEN: The URL changes to /contactos without a full reload
    await expect(page).toHaveURL('/contactos');
    await expect(page.locator('[data-testid="contactos-view"]')).toBeVisible();
  });

  test('should update active state in NavigationBar after tap navigation', async ({ page }) => {
    // GIVEN: The user starts on /clientes on mobile
    await page.goto('/clientes');

    // WHEN: The user taps Contactos
    await page.locator('[data-testid="nav-item-contactos"]').tap();
    await expect(page).toHaveURL('/contactos');

    // THEN: Contactos is marked active, Clientes is not
    await expect(page.locator('[data-testid="nav-item-contactos"]')).toHaveAttribute(
      'data-active',
      'true',
    );
    await expect(page.locator('[data-testid="nav-item-clientes"]')).toHaveAttribute(
      'data-active',
      'false',
    );
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// 404 page architectural boundary: navigation shell is absent on unknown routes
// ─────────────────────────────────────────────────────────────────────────────

test.describe('404 page has no navigation shell (root-level not-found)', () => {
  test('should NOT render the NavigationRail on a 404 page', async ({ page }) => {
    // GIVEN: The notFoundComponent is registered on __root.tsx (outside _app layout)
    // WHEN: The user navigates to an unknown route
    await page.goto('/ruta-inexistente-xyz');

    // THEN: The 404 view is shown but the NavigationRail is absent
    await expect(page.locator('[data-testid="not-found-view"]')).toBeVisible();
    await expect(page.locator('[data-testid="navigation-rail"]')).toHaveCount(0);
  });

  test('should NOT render the NavigationBar on a 404 page (mobile)', async ({ page }) => {
    // GIVEN: Mobile viewport on an unknown route
    await page.setViewportSize({ width: 375, height: 812 });
    await page.goto('/ruta-inexistente-xyz');

    // THEN: The 404 view is shown but the NavigationBar is absent
    await expect(page.locator('[data-testid="not-found-view"]')).toBeVisible();
    await expect(page.locator('[data-testid="navigation-bar"]')).toHaveCount(0);
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// startsWith active state: sub-path highlighting (implementation uses startsWith)
// ─────────────────────────────────────────────────────────────────────────────

test.describe('Active state with sub-path routes (startsWith detection)', () => {
  test.use({ viewport: { width: 1280, height: 720 } });

  test('should highlight Clientes as active when URL begins with /clientes', async ({ page }) => {
    // GIVEN: The implementation uses currentPath.startsWith(item.to) for active detection
    // AND: The user is on /clientes
    await page.goto('/clientes');

    // THEN: The Clientes nav item is active
    await expect(page.locator('[data-testid="nav-item-clientes"]')).toHaveAttribute(
      'data-active',
      'true',
    );
    // AND: Contactos is inactive
    await expect(page.locator('[data-testid="nav-item-contactos"]')).toHaveAttribute(
      'data-active',
      'false',
    );
  });

  test('should have exactly one active nav item at a time on /contactos', async ({ page }) => {
    // GIVEN: The user navigates to /contactos
    await page.goto('/contactos');

    // THEN: Exactly one nav item is marked active
    const activeItems = page.locator('[data-testid^="nav-item-"][data-active="true"]');
    await expect(activeItems).toHaveCount(1);

    // AND: It is the Contactos item
    await expect(page.locator('[data-testid="nav-item-contactos"]')).toHaveAttribute(
      'data-active',
      'true',
    );
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// NavigationBar bottom positioning (mobile layout integrity)
// ─────────────────────────────────────────────────────────────────────────────

test.describe('NavigationBar pinned to bottom on mobile', () => {
  test.use({ viewport: { width: 375, height: 812 } });

  test('should position the NavigationBar at the bottom of the viewport', async ({ page }) => {
    // GIVEN: The app is loaded on mobile
    await page.goto('/clientes');
    const navBar = page.locator('[data-testid="navigation-bar"]');
    await expect(navBar).toBeVisible();

    // WHEN: We check the bounding box of the NavigationBar
    const box = await navBar.boundingBox();
    const viewportSize = page.viewportSize();

    // THEN: The bottom of the NavigationBar touches the bottom of the viewport
    expect(box).not.toBeNull();
    expect(viewportSize).not.toBeNull();
    // Assert unconditionally — if box or viewportSize is null the test should fail explicitly
    const navBarBottom = Math.round(box!.y + box!.height);
    // Allow a small tolerance (1px) for sub-pixel rendering
    expect(navBarBottom).toBeGreaterThanOrEqual(viewportSize!.height - 1);
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// Page title / head metadata consistency (no crash on route change)
// ─────────────────────────────────────────────────────────────────────────────

test.describe('Application does not crash on repeated route changes', () => {
  test.use({ viewport: { width: 1280, height: 720 } });

  test('should remain functional after 5 consecutive route changes', async ({ page }) => {
    // GIVEN: The app is loaded
    await page.goto('/clientes');

    // WHEN: The user navigates back and forth 5 times
    const routes = ['/contactos', '/clientes', '/contactos', '/clientes', '/contactos'];
    for (const route of routes) {
      const itemId = route.replace('/', '');
      await page.locator(`[data-testid="nav-item-${itemId}"]`).click();
      await expect(page).toHaveURL(route);
    }

    // THEN: The app is still functional — both nav items are present and the final
    // route is correctly reflected
    await expect(page.locator('[data-testid="navigation-rail"]')).toBeVisible();
    await expect(page.locator('[data-testid="nav-item-contactos"]')).toHaveAttribute(
      'data-active',
      'true',
    );
    await expect(page.locator('[data-testid="contactos-view"]')).toBeVisible();
  });
});
