using System;
using SiesaAgents.Domain.Clientes.Entities;
using Xunit;

namespace SiesaAgents.UnitTests.Domain;

/// <summary>
/// Story 2.1 — Client List & Search (Epic 2)
/// ATDD Unit Tests — RED phase. Generated by testarch-atdd.
///
/// Failing until DEV creates the domain entity per AC-2.1.f (Task 1):
///   - <c>SiesaAgents.Domain.Clientes.Entities.ClienteEntity</c>
///   - private parameterless ctor for EF Core
///   - public static factory <c>Create(string nombre, string nit, string telefono, string ciudad)</c>
///   - <c>Guid Id</c> (UUID, NEVER int), <c>DateTimeOffset CreatedAt/UpdatedAt</c>
///   - private setters on every property
///
/// Expected RED failure: "The type or namespace name 'ClienteEntity' could not be found".
/// </summary>
public class ClienteEntityTests
{
    [Fact]
    public void Create_AssignsNonEmptyGuidId()
    {
        // GIVEN: a valid factory call
        // WHEN: the static factory builds a new entity
        var entity = ClienteEntity.Create("Acme", "900-1", "+57 1 222", "Bogotá");

        // THEN: a fresh UUID is assigned (never Guid.Empty)
        Assert.NotEqual(Guid.Empty, entity.Id);
    }

    [Fact]
    public void Create_AssignsNombre()
    {
        // GIVEN/WHEN
        var entity = ClienteEntity.Create("Acme", "900-1", "+57 1 222", "Bogotá");

        // THEN
        Assert.Equal("Acme", entity.Nombre);
    }

    [Fact]
    public void Create_AssignsNit()
    {
        // GIVEN/WHEN
        var entity = ClienteEntity.Create("Acme", "900-1", "+57 1 222", "Bogotá");

        // THEN
        Assert.Equal("900-1", entity.Nit);
    }

    [Fact]
    public void Create_AssignsTelefono()
    {
        // GIVEN/WHEN
        var entity = ClienteEntity.Create("Acme", "900-1", "+57 1 222", "Bogotá");

        // THEN
        Assert.Equal("+57 1 222", entity.Telefono);
    }

    [Fact]
    public void Create_AssignsCiudad()
    {
        // GIVEN/WHEN
        var entity = ClienteEntity.Create("Acme", "900-1", "+57 1 222", "Bogotá");

        // THEN
        Assert.Equal("Bogotá", entity.Ciudad);
    }

    [Fact]
    public void Create_SetsCreatedAtCloseToUtcNow()
    {
        // GIVEN: a baseline timestamp just before the entity is created
        var before = DateTimeOffset.UtcNow;

        // WHEN
        var entity = ClienteEntity.Create("Acme", "900-1", "+57 1 222", "Bogotá");

        // THEN: CreatedAt sits within a 5-second window straddling "now".
        //       DateTimeOffset is mandatory (NEVER use DateTime — company standard).
        var after = DateTimeOffset.UtcNow;
        Assert.InRange(entity.CreatedAt, before.AddSeconds(-1), after.AddSeconds(5));
    }

    [Fact]
    public void Create_SetsUpdatedAtCloseToUtcNow()
    {
        // GIVEN/WHEN
        var before = DateTimeOffset.UtcNow;
        var entity = ClienteEntity.Create("Acme", "900-1", "+57 1 222", "Bogotá");
        var after = DateTimeOffset.UtcNow;

        // THEN
        Assert.InRange(entity.UpdatedAt, before.AddSeconds(-1), after.AddSeconds(5));
    }

    [Fact]
    public void Properties_HavePrivateSetters_FromExternalAssembly()
    {
        // GIVEN: an entity instance built via the factory
        var entity = ClienteEntity.Create("Acme", "900-1", "+57 1 222", "Bogotá");

        // THEN: each public property must NOT have a public setter — encapsulation
        //       is enforced via factory + private setters (company standards).
        var nombre = typeof(ClienteEntity).GetProperty(nameof(ClienteEntity.Nombre));
        Assert.NotNull(nombre);
        var setter = nombre!.GetSetMethod(nonPublic: false);
        Assert.Null(setter); // public setter MUST be absent

        // Sanity: entity still exposes the value via the getter.
        Assert.Equal("Acme", entity.Nombre);
    }
}
