// ─────────────────────────────────────────────────────────────────────────────
// Edge Cases — Story 2.1: Client List & Search
// Test Level: Unit (xUnit)
// Mode: BMad-Integrated (expands ATDD coverage with edge cases NOT in
//       GetClientesQueryHandlerTests.cs)
//
// Coverage added here:
//   - ClienteEntity.Create throws ArgumentException for null nombre
//   - ClienteEntity.Create throws ArgumentException for whitespace-only nombre
//   - ClienteEntity.Create throws ArgumentException for null nit
//   - ClienteEntity.Create throws ArgumentException for whitespace-only nit
//   - Handler preserves insertion order (no reordering by handler)
//   - Handler propagates CancellationToken to repository (cancelled token)
//   - ClienteDto is a record (value equality — two DTOs with same fields are Equal)
//   - Handler returns IEnumerable<ClienteDto> (lazy — can be enumerated twice)
//   - UpdatedAt on ClienteDto is a non-default DateTimeOffset
//   - ClienteDto.Id matches ClienteEntity.Id (not a new Guid generated by handler)
// ─────────────────────────────────────────────────────────────────────────────

using SiesaAgents.Application.Clientes.DTOs;
using SiesaAgents.Application.Clientes.Queries;
using SiesaAgents.Domain.Clientes.Interfaces;
using Xunit;

namespace SiesaAgents.UnitTests.Application.Clientes;

/// <summary>
/// Edge-case and boundary-condition tests for GetClientesQueryHandler and
/// ClienteEntity.Create — covering error paths and structural guarantees NOT
/// exercised in the primary ATDD test suite.
/// </summary>
public class GetClientesQueryHandlerEdgeCaseTests
{
    // ──────────────────────────────────────────────────────────────────────────
    // Stub repository — tracks whether CancellationToken was passed through
    // ──────────────────────────────────────────────────────────────────────────

    private sealed class StubClienteRepository : IClienteRepository
    {
        private readonly IEnumerable<SiesaAgents.Domain.Clientes.Entities.ClienteEntity> _data;
        public CancellationToken LastReceivedToken { get; private set; }

        public StubClienteRepository(
            IEnumerable<SiesaAgents.Domain.Clientes.Entities.ClienteEntity> data)
            => _data = data;

        public Task<IEnumerable<SiesaAgents.Domain.Clientes.Entities.ClienteEntity>> GetAllAsync(
            CancellationToken ct = default)
        {
            LastReceivedToken = ct;
            ct.ThrowIfCancellationRequested();
            return Task.FromResult(_data);
        }

        public Task<SiesaAgents.Domain.Clientes.Entities.ClienteEntity?> GetByIdAsync(
            Guid id, CancellationToken ct = default)
            => Task.FromResult<SiesaAgents.Domain.Clientes.Entities.ClienteEntity?>(null);

        public Task AddAsync(
            SiesaAgents.Domain.Clientes.Entities.ClienteEntity entity,
            CancellationToken ct = default) => Task.CompletedTask;

        public Task UpdateAsync(
            SiesaAgents.Domain.Clientes.Entities.ClienteEntity entity,
            CancellationToken ct = default) => Task.CompletedTask;

        public Task DeleteAsync(
            SiesaAgents.Domain.Clientes.Entities.ClienteEntity entity,
            CancellationToken ct = default) => Task.CompletedTask;
    }

    // ──────────────────────────────────────────────────────────────────────────
    // Helper factory
    // ──────────────────────────────────────────────────────────────────────────

    private static SiesaAgents.Domain.Clientes.Entities.ClienteEntity MakeCliente(
        string nombre = "Test Corp",
        string nit = "111111111-1",
        string telefono = "+57 300 000 0001",
        string ciudad = "Bogotá")
        => SiesaAgents.Domain.Clientes.Entities.ClienteEntity.Create(nombre, nit, telefono, ciudad);

    // ──────────────────────────────────────────────────────────────────────────
    // ClienteEntity.Create — input validation (error paths)
    // ──────────────────────────────────────────────────────────────────────────

    [Fact(DisplayName = "ClienteEntity.Create throws ArgumentException when nombre is null")]
    public void Create_NullNombre_Throws()
    {
        // ARRANGE + ACT + ASSERT
        Assert.Throws<ArgumentException>(
            () => SiesaAgents.Domain.Clientes.Entities.ClienteEntity.Create(
                null!, "111111111-1", "+57 300 000 0001", "Bogotá"));
    }

    [Fact(DisplayName = "ClienteEntity.Create throws ArgumentException when nombre is whitespace-only")]
    public void Create_WhitespaceNombre_Throws()
    {
        Assert.Throws<ArgumentException>(
            () => SiesaAgents.Domain.Clientes.Entities.ClienteEntity.Create(
                "   ", "111111111-1", "+57 300 000 0001", "Bogotá"));
    }

    [Fact(DisplayName = "ClienteEntity.Create throws ArgumentException when nit is null")]
    public void Create_NullNit_Throws()
    {
        Assert.Throws<ArgumentException>(
            () => SiesaAgents.Domain.Clientes.Entities.ClienteEntity.Create(
                "Test Corp", null!, "+57 300 000 0001", "Bogotá"));
    }

    [Fact(DisplayName = "ClienteEntity.Create throws ArgumentException when nit is whitespace-only")]
    public void Create_WhitespaceNit_Throws()
    {
        Assert.Throws<ArgumentException>(
            () => SiesaAgents.Domain.Clientes.Entities.ClienteEntity.Create(
                "Test Corp", "   ", "+57 300 000 0001", "Bogotá"));
    }

    [Fact(DisplayName = "ClienteEntity.Create succeeds with empty telefono (optional field)")]
    public void Create_EmptyTelefono_DoesNotThrow()
    {
        // ARRANGE + ACT + ASSERT: telefono is optional — empty string is valid
        var exception = Record.Exception(
            () => SiesaAgents.Domain.Clientes.Entities.ClienteEntity.Create(
                "Test Corp", "111111111-1", string.Empty, "Bogotá"));
        Assert.Null(exception);
    }

    [Fact(DisplayName = "ClienteEntity.Create succeeds with empty ciudad (optional field)")]
    public void Create_EmptyCiudad_DoesNotThrow()
    {
        var exception = Record.Exception(
            () => SiesaAgents.Domain.Clientes.Entities.ClienteEntity.Create(
                "Test Corp", "111111111-1", "+57 300 000 0001", string.Empty));
        Assert.Null(exception);
    }

    // ──────────────────────────────────────────────────────────────────────────
    // Handler — CancellationToken propagation (error path)
    // ──────────────────────────────────────────────────────────────────────────

    [Fact(DisplayName = "Handler propagates CancellationToken — cancelled token causes OperationCanceledException")]
    public async Task Handle_CancelledToken_ThrowsOperationCanceledException()
    {
        // ARRANGE: Pre-cancelled token
        var repository = new StubClienteRepository(new[] { MakeCliente() });
        var handler = new GetClientesQueryHandler(repository);
        using var cts = new CancellationTokenSource();
        await cts.CancelAsync();

        // ACT + ASSERT: Handler (or repository stub) throws on cancelled token
        await Assert.ThrowsAnyAsync<OperationCanceledException>(
            () => handler.Handle(new GetClientesQuery(), cts.Token));
    }

    [Fact(DisplayName = "Handler passes the caller's CancellationToken to repository.GetAllAsync")]
    public async Task Handle_PassesTokenToRepository()
    {
        // ARRANGE
        var repository = new StubClienteRepository(new[] { MakeCliente() });
        var handler = new GetClientesQueryHandler(repository);
        using var cts = new CancellationTokenSource();

        // ACT
        await handler.Handle(new GetClientesQuery(), cts.Token);

        // ASSERT: The stub recorded the token we passed
        Assert.Equal(cts.Token, repository.LastReceivedToken);
    }

    // ──────────────────────────────────────────────────────────────────────────
    // Handler — ordering
    // ──────────────────────────────────────────────────────────────────────────

    [Fact(DisplayName = "Handler preserves the order of entities returned by the repository")]
    public async Task Handle_PreservesRepositoryOrder()
    {
        // ARRANGE: Three entities in a specific order
        var a = MakeCliente("Alpha", "111111111-1");
        var b = MakeCliente("Beta", "222222222-2");
        var c = MakeCliente("Gamma", "333333333-3");
        var repository = new StubClienteRepository(new[] { a, b, c });
        var handler = new GetClientesQueryHandler(repository);

        // ACT
        var result = (await handler.Handle(new GetClientesQuery(), CancellationToken.None)).ToList();

        // ASSERT: Order matches repository order (no sorting by handler)
        Assert.Equal("Alpha", result[0].Nombre);
        Assert.Equal("Beta", result[1].Nombre);
        Assert.Equal("Gamma", result[2].Nombre);
    }

    // ──────────────────────────────────────────────────────────────────────────
    // Handler — DTO identity / field guarantees
    // ──────────────────────────────────────────────────────────────────────────

    [Fact(DisplayName = "ClienteDto.Id matches the original ClienteEntity.Id (no new Guid generated by handler)")]
    public async Task Handle_DtoIdMatchesEntityId()
    {
        // ARRANGE
        var entity = MakeCliente();
        var entityId = entity.Id;
        var repository = new StubClienteRepository(new[] { entity });
        var handler = new GetClientesQueryHandler(repository);

        // ACT
        var result = await handler.Handle(new GetClientesQuery(), CancellationToken.None);
        var dto = result.Single();

        // ASSERT: Handler maps entity.Id → DTO.Id without generating a new one
        Assert.Equal(entityId, dto.Id);
    }

    [Fact(DisplayName = "ClienteDto.UpdatedAt is not the default DateTimeOffset")]
    public async Task Handle_DtoUpdatedAtIsNotDefault()
    {
        // ARRANGE
        var entity = MakeCliente();
        var repository = new StubClienteRepository(new[] { entity });
        var handler = new GetClientesQueryHandler(repository);

        // ACT
        var result = await handler.Handle(new GetClientesQuery(), CancellationToken.None);
        var dto = result.Single();

        // ASSERT: UpdatedAt is initialized (entity sets it to UtcNow at create time)
        Assert.NotEqual(default(DateTimeOffset), dto.UpdatedAt);
    }

    [Fact(DisplayName = "ClienteDto is a record — two instances with same fields are value-equal")]
    public async Task Handle_ClienteDto_IsRecord_ValueEquality()
    {
        // ARRANGE: Two identical DTOs constructed directly
        var id = Guid.NewGuid();
        var now = DateTimeOffset.UtcNow;
        var dto1 = new ClienteDto(id, "Test Corp", "111111111-1", "+57 300", "Bogotá", now, now);
        var dto2 = new ClienteDto(id, "Test Corp", "111111111-1", "+57 300", "Bogotá", now, now);

        // ASSERT: Records use structural equality by default in C#
        Assert.Equal(dto1, dto2);
    }

    [Fact(DisplayName = "Handler result can be enumerated twice without errors (not a one-time stream)")]
    public async Task Handle_ResultIsReEnumerable()
    {
        // ARRANGE
        var entity = MakeCliente();
        var repository = new StubClienteRepository(new[] { entity });
        var handler = new GetClientesQueryHandler(repository);

        // ACT
        var result = await handler.Handle(new GetClientesQuery(), CancellationToken.None);

        // ASSERT: Enumerable can be iterated twice (LINQ Select materializes as needed)
        var first = result.ToList();
        var second = result.ToList();
        Assert.Equal(first.Count, second.Count);
    }

    // ──────────────────────────────────────────────────────────────────────────
    // ClienteDto — field type guarantees (boundary conditions)
    // ──────────────────────────────────────────────────────────────────────────

    [Fact(DisplayName = "ClienteDto.CreatedAt and UpdatedAt are DateTimeOffset (not DateTime) — type boundary")]
    public async Task Handle_DtoTimestampsAreDateTimeOffset()
    {
        // ARRANGE
        var entity = MakeCliente();
        var repository = new StubClienteRepository(new[] { entity });
        var handler = new GetClientesQueryHandler(repository);

        // ACT
        var result = await handler.Handle(new GetClientesQuery(), CancellationToken.None);
        var dto = result.Single();

        // ASSERT: Both timestamps are DateTimeOffset — assignment from entity proves the type
        DateTimeOffset createdAt = dto.CreatedAt;
        DateTimeOffset updatedAt = dto.UpdatedAt;
        Assert.IsType<DateTimeOffset>(createdAt);
        Assert.IsType<DateTimeOffset>(updatedAt);
    }
}
