/**
 * Story 1.2 — Frontend Navigation Shell
 * Epic 1: Project Foundation & Application Shell
 *
 * Component tests for ContactosPlaceholderView.
 *
 * Generated by testarch-automate (BMad-Integrated Mode) — expands ATDD coverage
 * with isolated tests for the Spanish placeholder shipped in Story 1.2.
 *
 * Covers AC #4 (placeholder view rendered for /contactos deep link) at the
 * component level — the routing integration is already exercised by the E2E
 * suite (TC-E1-P1-03).
 *
 * Scope mirrors ClientesPlaceholderView.test.tsx so any future divergence in
 * the two placeholders surfaces as a test failure, not a silent regression.
 */

import { describe, it, expect, afterEach } from 'vitest'
import { cleanup, render, screen } from '@testing-library/react'

import { ContactosPlaceholderView } from './ContactosPlaceholderView'

describe('ContactosPlaceholderView — Spanish placeholder (Story 1.2, AC #4)', () => {
  afterEach(() => {
    cleanup()
  })

  it('[P1] renders the Spanish heading "Contactos" at level 1', () => {
    // GIVEN/WHEN: the placeholder view is rendered standalone
    render(<ContactosPlaceholderView />)

    // THEN: the Spanish heading is exposed at level 1
    expect(
      screen.getByRole('heading', { level: 1, name: /^contactos$/i }),
    ).toBeInTheDocument()
  })

  it('[P1] renders the Spanish placeholder copy "Sección en construcción."', () => {
    // GIVEN/WHEN: the placeholder view is rendered
    render(<ContactosPlaceholderView />)

    // THEN: the placeholder copy is present
    expect(screen.getByText(/sección en construcción\./i)).toBeInTheDocument()
  })

  it('[P1] exposes data-testid="contactos-placeholder" for SPA navigation assertions', () => {
    // GIVEN/WHEN: the placeholder view is rendered
    render(<ContactosPlaceholderView />)

    // THEN: the agreed test id is wired (also used by E2E TC-E1-P1-03)
    expect(screen.getByTestId('contactos-placeholder')).toBeInTheDocument()
  })

  it('[P2] renders 3 Skeleton placeholders (visual stand-in for the future list)', () => {
    // GIVEN/WHEN: the placeholder view is rendered
    const { container } = render(<ContactosPlaceholderView />)

    // THEN: exactly 3 skeleton placeholders are emitted (Skeleton count={3})
    const skeletons = container.querySelectorAll('.react-loading-skeleton')
    expect(skeletons).toHaveLength(3)
  })

  it('[P2] is SSR-safe — does not throw on render (no `window` access in the body)', () => {
    // GIVEN: a render context
    // WHEN: the placeholder renders
    // THEN: it must not throw — proves no top-level `window`/`document` access in the module body
    expect(() => render(<ContactosPlaceholderView />)).not.toThrow()
  })
})
