/**
 * Story 1.1: Project Initialization & Repository Structure
 * Epic 1: Project Foundation & Application Shell
 *
 * Automation Expansion — Edge Cases & Boundary Conditions (API level)
 * Generated by *automate after ATDD (backend-initialization.api.spec.ts) went GREEN.
 * Focus: negative CORS paths, HTTP method boundaries, and error-format
 * consistency NOT covered by the original ATDD suite.
 *
 * Acceptance Criteria covered:
 *   AC2 — Backend on port 5000, Scalar at /scalar, Swagger forbidden
 *   AC3 — CORS allows ONLY http://localhost:5173 (negative path added here)
 */

import { test, expect } from '@playwright/test';

const API_BASE_URL = process.env.API_BASE_URL ?? 'http://localhost:5000';

// ─────────────────────────────────────────────────────────────────────────────
// AC3 negative path: disallowed origins must NOT receive a matching CORS header
// ─────────────────────────────────────────────────────────────────────────────

test.describe('AC3 — CORS rejects disallowed origins (negative path)', () => {
  test('[P1] should NOT echo back an untrusted origin in Access-Control-Allow-Origin', async ({ request }) => {
    // GIVEN: CORS policy "DevCors" only allows http://localhost:5173
    // WHEN: A request is made with an untrusted Origin header
    const response = await request.get(`${API_BASE_URL}/scalar`, {
      headers: { Origin: 'http://evil-attacker.example' },
    });

    // THEN: The disallowed origin is never reflected back
    const allowOriginHeader = response.headers()['access-control-allow-origin'] ?? '';
    expect(allowOriginHeader).not.toBe('http://evil-attacker.example');
  });

  test('[P2] should reject a cross-origin preflight from an untrusted origin', async ({ request }) => {
    // GIVEN: An OPTIONS preflight simulating a browser from an untrusted origin
    // WHEN: The preflight requests permission to call the API
    const response = await request.fetch(`${API_BASE_URL}/scalar`, {
      method: 'OPTIONS',
      headers: {
        Origin: 'http://evil-attacker.example',
        'Access-Control-Request-Method': 'GET',
      },
    });

    // THEN: The response does not grant the untrusted origin access
    const allowOriginHeader = response.headers()['access-control-allow-origin'] ?? '';
    expect(allowOriginHeader).not.toBe('http://evil-attacker.example');
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// AC2 boundary: unsupported HTTP methods and forbidden documentation routes
// ─────────────────────────────────────────────────────────────────────────────

test.describe('AC2 — HTTP method and route boundaries', () => {
  test('[P2] should reject POST to the Scalar documentation route', async ({ request }) => {
    // GIVEN: /scalar is a documentation-only GET route
    // WHEN: A POST is sent instead
    const response = await request.post(`${API_BASE_URL}/scalar`);

    // THEN: The server does not treat it as a valid documented action (not 200)
    expect(response.status()).not.toBe(200);
  });

  test('[P2] should NOT expose the raw OpenAPI/Swagger JSON document at the legacy swagger.json path', async ({
    request,
  }) => {
    // GIVEN: Swashbuckle is explicitly forbidden by the architecture
    // WHEN: The legacy swagger.json path is requested
    const response = await request.get(`${API_BASE_URL}/swagger/v1/swagger.json`);

    // THEN: The legacy Swashbuckle route does not resolve
    expect(response.status()).not.toBe(200);
  });

  test('[P3] should return a case-insensitive-safe 404 for a random unknown path', async ({ request }) => {
    // GIVEN: No routes exist beyond /scalar and OpenAPI metadata in this story
    // WHEN: A random, unmapped path is requested
    const response = await request.get(`${API_BASE_URL}/totally-unknown-route-xyz`);

    // THEN: The server responds gracefully (never a 5xx crash)
    expect(response.status()).toBeLessThan(500);
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// Error-format consistency: every not-found/error response stays JSON, never HTML
// ─────────────────────────────────────────────────────────────────────────────

test.describe('Error responses stay machine-readable (boundary condition)', () => {
  test('[P2] should never return an HTML error page for unmapped API-style routes', async ({ request }) => {
    // GIVEN: ExceptionHandlingMiddleware + UseStatusCodePages are registered before routing
    // WHEN: An unmapped /api/* route is requested
    const response = await request.get(`${API_BASE_URL}/api/v1/does-not-exist`);
    const contentType = response.headers()['content-type'] ?? '';

    // THEN: The response is JSON-shaped, never an HTML dev-exception page
    expect(contentType).not.toContain('text/html');
  });
});
