/**
 * Story 1.3: Backend Database Foundation
 * Epic 1: Project Foundation & Application Shell
 *
 * Edge Case Tests — EF Core / PostgreSQL Infrastructure
 * Expands ATDD coverage in backend-database-foundation.api.spec.ts with
 * boundary conditions, error paths, and structural invariants NOT covered
 * by the primary ATDD spec.
 *
 * Coverage areas:
 *   AC1 edge cases:
 *     - InitialCreate migration body contains NO SQL table statements (empty baseline)
 *     - Migration file has valid 14-digit timestamp prefix
 *     - InitialCreate.cs declares both Up() and Down() methods
 *     - AppDbContextModelSnapshot.cs references AppDbContext class name
 *     - Migration namespace is SiesaAgents.Infrastructure.Data.Migrations
 *
 *   AC2 edge cases:
 *     - ConnectionString has required PostgreSQL keywords (Host, Database, Username, Password)
 *     - ConnectionString points to localhost (not a production host)
 *     - appsettings.Development.json does not contain production hostnames
 *     - Program.cs registers DbContext using builder.Services (not app.Services)
 *     - AddDbContext call passes options lambda with UseNpgsql on a single coherent line
 *
 *   AC3 edge cases:
 *     - ExceptionHandlingMiddleware uses async Task InvokeAsync (not Invoke)
 *     - Middleware catches generic Exception (not specific typed exceptions only)
 *     - ProblemDetails Status and HTTP StatusCode are both 500 (consistent)
 *     - Middleware does NOT reference ex.ToString() or exception.InnerException in response
 *     - ExceptionHandlingMiddleware class uses primary constructor (RequestDelegate next)
 *
 *   AC4 edge cases:
 *     - AppDbContext calls base.OnModelCreating before ApplyConfigurationsFromAssembly
 *     - AppDbContext does NOT define any DbSet<> properties (empty baseline)
 *     - AppDbContext file is in namespace SiesaAgents.Infrastructure.Data
 *     - AppDbContext does NOT import any domain entity namespace directly
 *
 *   AC5 edge cases:
 *     - Infrastructure.csproj TargetFramework is net10.0
 *     - API.csproj TargetFramework is net10.0
 *     - UnitTests.csproj references Microsoft.EntityFrameworkCore.InMemory (for unit tests)
 *     - EFCore.NamingConventions version targets wildcard (latest for EF Core 10 compat)
 *     - Program.cs does NOT reference UseSwagger (Scalar-only rule)
 *
 *   Migration content boundary:
 *     - InitialCreate.cs Up() body contains no CREATE TABLE or ALTER TABLE statements
 *     - InitialCreate.cs Down() body contains no DROP TABLE statements
 *
 * Status: GREEN — tests validate the implemented Story 1.3 structure
 */

import { test, expect } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';

const PROJECT_ROOT = path.resolve(__dirname, '../../..');
const BACKEND_ROOT = path.join(PROJECT_ROOT, 'backend');
const API_SRC = path.join(BACKEND_ROOT, 'src/SiesaAgents.API');
const INFRASTRUCTURE_SRC = path.join(BACKEND_ROOT, 'src/SiesaAgents.Infrastructure');
const MIGRATIONS_DIR = path.join(INFRASTRUCTURE_SRC, 'Data/Migrations');

// ─────────────────────────────────────────────────────────────────────────────
// AC1 edge cases — InitialCreate migration content is empty baseline
// ─────────────────────────────────────────────────────────────────────────────

test.describe('AC1 edge cases — InitialCreate migration is an empty baseline', () => {
  test('should have a migration file with valid 14-digit timestamp prefix', () => {
    /**
     * Given the InitialCreate migration was generated by dotnet ef
     * When the Migrations directory is inspected
     * Then the migration filename starts with a 14-digit numeric timestamp (YYYYMMDDHHmmss)
     */
    expect(
      fs.existsSync(MIGRATIONS_DIR),
      `Migrations directory must exist at ${MIGRATIONS_DIR}`
    ).toBe(true);

    const files = fs.readdirSync(MIGRATIONS_DIR);
    const migrationFile = files.find(
      (f) => f.endsWith('_InitialCreate.cs') && !f.includes('Designer')
    );

    expect(migrationFile, 'InitialCreate.cs migration file must exist').toBeDefined();

    // Timestamp prefix must be exactly 14 digits (YYYYMMDDHHmmss)
    const timestampPrefix = migrationFile!.split('_')[0];
    expect(
      /^\d{14}$/.test(timestampPrefix),
      `Migration filename prefix "${timestampPrefix}" must be a valid 14-digit timestamp (YYYYMMDDHHmmss)`
    ).toBe(true);
  });

  test('InitialCreate migration file should declare an Up() method', () => {
    /**
     * Given the InitialCreate migration file exists
     * When the file content is inspected
     * Then an Up(MigrationBuilder) method is declared (required by EF Core)
     */
    expect(fs.existsSync(MIGRATIONS_DIR)).toBe(true);
    const files = fs.readdirSync(MIGRATIONS_DIR);
    const migrationFile = files.find(
      (f) => f.endsWith('_InitialCreate.cs') && !f.includes('Designer')
    );
    expect(migrationFile, 'InitialCreate.cs must exist').toBeDefined();

    const content = fs.readFileSync(path.join(MIGRATIONS_DIR, migrationFile!), 'utf-8');

    expect(
      content,
      'InitialCreate.cs must declare an Up method for EF Core tooling'
    ).toContain('Up');
  });

  test('InitialCreate migration file should declare a Down() method', () => {
    /**
     * Given the InitialCreate migration file exists
     * When the file content is inspected
     * Then a Down(MigrationBuilder) method is declared (required for rollback)
     */
    const files = fs.readdirSync(MIGRATIONS_DIR);
    const migrationFile = files.find(
      (f) => f.endsWith('_InitialCreate.cs') && !f.includes('Designer')
    );
    const content = fs.readFileSync(path.join(MIGRATIONS_DIR, migrationFile!), 'utf-8');

    expect(
      content,
      'InitialCreate.cs must declare a Down method for migration rollback'
    ).toContain('Down');
  });

  test('InitialCreate migration Up() should NOT contain SQL CREATE TABLE statements', () => {
    /**
     * Given this is the empty baseline migration (no domain tables)
     * When the Up() method body is inspected
     * Then no CREATE TABLE or CreateTable calls exist
     * (tables are added in Epic 2 Story 2.1 and Epic 3 Story 3.1)
     */
    const files = fs.readdirSync(MIGRATIONS_DIR);
    const migrationFile = files.find(
      (f) => f.endsWith('_InitialCreate.cs') && !f.includes('Designer')
    );
    const content = fs.readFileSync(path.join(MIGRATIONS_DIR, migrationFile!), 'utf-8');

    expect(
      content,
      'InitialCreate Up() must NOT contain CreateTable calls — this is an empty baseline migration'
    ).not.toContain('CreateTable');

    expect(
      content,
      'InitialCreate Up() must NOT contain raw CREATE TABLE SQL — this is an empty baseline migration'
    ).not.toMatch(/CREATE\s+TABLE/i);
  });

  test('InitialCreate migration Down() should NOT contain SQL DROP TABLE statements', () => {
    /**
     * Given the empty baseline migration has no tables to drop
     * When the Down() method body is inspected
     * Then no DropTable calls exist
     */
    const files = fs.readdirSync(MIGRATIONS_DIR);
    const migrationFile = files.find(
      (f) => f.endsWith('_InitialCreate.cs') && !f.includes('Designer')
    );
    const content = fs.readFileSync(path.join(MIGRATIONS_DIR, migrationFile!), 'utf-8');

    expect(
      content,
      'InitialCreate Down() must NOT contain DropTable calls — no tables were created in this migration'
    ).not.toContain('DropTable');

    expect(
      content,
      'InitialCreate Down() must NOT contain DROP TABLE SQL'
    ).not.toMatch(/DROP\s+TABLE/i);
  });

  test('InitialCreate migration should be in SiesaAgents.Infrastructure.Data.Migrations namespace', () => {
    /**
     * Given the migration is generated by EF Core for the Infrastructure project
     * When the migration file namespace is inspected
     * Then it matches SiesaAgents.Infrastructure.Data.Migrations
     */
    const files = fs.readdirSync(MIGRATIONS_DIR);
    const migrationFile = files.find(
      (f) => f.endsWith('_InitialCreate.cs') && !f.includes('Designer')
    );
    const content = fs.readFileSync(path.join(MIGRATIONS_DIR, migrationFile!), 'utf-8');

    expect(
      content,
      'Migration must be in the SiesaAgents.Infrastructure.Data.Migrations namespace'
    ).toContain('SiesaAgents.Infrastructure.Data.Migrations');
  });

  test('AppDbContextModelSnapshot should reference AppDbContext', () => {
    /**
     * Given the model snapshot is the EF Core baseline model
     * When AppDbContextModelSnapshot.cs is inspected
     * Then it references AppDbContext by name (it is a snapshot of the context model)
     */
    const snapshotPath = path.join(MIGRATIONS_DIR, 'AppDbContextModelSnapshot.cs');
    expect(
      fs.existsSync(snapshotPath),
      `AppDbContextModelSnapshot.cs must exist at ${snapshotPath}`
    ).toBe(true);

    const content = fs.readFileSync(snapshotPath, 'utf-8');

    expect(
      content,
      'AppDbContextModelSnapshot.cs must reference AppDbContext'
    ).toContain('AppDbContext');
  });

  test('AppDbContextModelSnapshot should be in SiesaAgents.Infrastructure.Data.Migrations namespace', () => {
    /**
     * Given the snapshot is part of the Infrastructure project
     * When the namespace is inspected
     * Then it matches SiesaAgents.Infrastructure.Data.Migrations
     */
    const snapshotPath = path.join(MIGRATIONS_DIR, 'AppDbContextModelSnapshot.cs');
    const content = fs.readFileSync(snapshotPath, 'utf-8');

    expect(
      content,
      'AppDbContextModelSnapshot.cs must be in the SiesaAgents.Infrastructure.Data.Migrations namespace'
    ).toContain('SiesaAgents.Infrastructure.Data.Migrations');
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// AC2 edge cases — ConnectionString structure and safety boundaries
// ─────────────────────────────────────────────────────────────────────────────

test.describe('AC2 edge cases — ConnectionString structure and safety', () => {
  test('DefaultConnection should contain required PostgreSQL connection keywords', () => {
    /**
     * Given the DefaultConnection is a Npgsql connection string
     * When the string is parsed
     * Then it contains all required PostgreSQL keywords: Host, Database, Username, Password
     */
    const settingsPath = path.join(API_SRC, 'appsettings.Development.json');
    const raw = fs.readFileSync(settingsPath, 'utf-8');
    const settings = JSON.parse(raw);
    const connStr: string = settings.ConnectionStrings?.DefaultConnection ?? '';

    expect(connStr, 'ConnectionString must specify Host').toContain('Host=');
    expect(connStr, 'ConnectionString must specify Database').toContain('Database=');
    expect(connStr, 'ConnectionString must specify Username').toContain('Username=');
    expect(connStr, 'ConnectionString must specify Password').toContain('Password=');
  });

  test('DefaultConnection should point to localhost (not a production host)', () => {
    /**
     * Given this is appsettings.Development.json (local dev config)
     * When the connection string host is inspected
     * Then it references localhost only (never a production or staging hostname)
     */
    const settingsPath = path.join(API_SRC, 'appsettings.Development.json');
    const raw = fs.readFileSync(settingsPath, 'utf-8');
    const settings = JSON.parse(raw);
    const connStr: string = settings.ConnectionStrings?.DefaultConnection ?? '';

    expect(
      connStr,
      'Development ConnectionString must use Host=localhost (not a production server)'
    ).toContain('Host=localhost');

    expect(
      connStr,
      'Development ConnectionString must NOT reference a production hostname'
    ).not.toMatch(/Host=[a-zA-Z0-9.-]+\.siesa\.com/);
  });

  test('Program.cs AddDbContext registration should use builder.Services (not app.Services)', () => {
    /**
     * Given AddDbContext must be registered before app.Build() is called
     * When Program.cs is read
     * Then builder.Services.AddDbContext is used (not app.Services which is read-only)
     */
    const programPath = path.join(API_SRC, 'Program.cs');
    const content = fs.readFileSync(programPath, 'utf-8');

    expect(
      content,
      'AppDbContext must be registered using builder.Services.AddDbContext (not app.Services)'
    ).toContain('builder.Services.AddDbContext');
  });

  test('Program.cs AddDbContext call should come before var app = builder.Build()', () => {
    /**
     * Given services must be registered before building the app
     * When the ordering of calls in Program.cs is inspected
     * Then AddDbContext appears before builder.Build()
     */
    const programPath = path.join(API_SRC, 'Program.cs');
    const content = fs.readFileSync(programPath, 'utf-8');

    const addDbContextIndex = content.indexOf('AddDbContext');
    const buildIndex = content.indexOf('builder.Build()');

    expect(addDbContextIndex, 'AddDbContext must be present in Program.cs').toBeGreaterThan(-1);
    expect(buildIndex, 'builder.Build() must be present in Program.cs').toBeGreaterThan(-1);

    expect(
      addDbContextIndex,
      'AddDbContext<AppDbContext> must be called BEFORE builder.Build() in Program.cs'
    ).toBeLessThan(buildIndex);
  });

  test('appsettings.Development.json should NOT contain any production hostname', () => {
    /**
     * Given the development config is committed to source control
     * When appsettings.Development.json is parsed
     * Then no production hostname (.siesa.com or similar) appears in any value
     */
    const settingsPath = path.join(API_SRC, 'appsettings.Development.json');
    const raw = fs.readFileSync(settingsPath, 'utf-8');

    expect(
      raw,
      'appsettings.Development.json must NOT contain production hostnames'
    ).not.toMatch(/\.siesa\.com/);

    expect(
      raw,
      'appsettings.Development.json must NOT reference production database servers'
    ).not.toMatch(/Host=(?!localhost)/);
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// AC3 edge cases — ExceptionHandlingMiddleware implementation correctness
// ─────────────────────────────────────────────────────────────────────────────

test.describe('AC3 edge cases — ExceptionHandlingMiddleware implementation correctness', () => {
  test('should use async Task InvokeAsync (not synchronous Invoke)', () => {
    /**
     * Given ASP.NET Core middleware must be asynchronous
     * When ExceptionHandlingMiddleware.cs is inspected
     * Then the method is declared as async Task InvokeAsync
     */
    const middlewarePath = path.join(API_SRC, 'Middleware/ExceptionHandlingMiddleware.cs');
    const content = fs.readFileSync(middlewarePath, 'utf-8');

    expect(
      content,
      'Middleware must use async Task InvokeAsync for ASP.NET Core middleware contract'
    ).toContain('async Task InvokeAsync');
  });

  test('should catch generic Exception (not specific typed exceptions only)', () => {
    /**
     * Given the middleware must handle ALL unhandled exceptions
     * When ExceptionHandlingMiddleware.cs is inspected
     * Then the catch block catches Exception (not only ArgumentException or similar)
     */
    const middlewarePath = path.join(API_SRC, 'Middleware/ExceptionHandlingMiddleware.cs');
    const content = fs.readFileSync(middlewarePath, 'utf-8');

    // Must have catch (Exception ...) — catches everything
    expect(
      content,
      'Middleware must catch generic Exception to handle all unhandled exceptions'
    ).toMatch(/catch\s*\(\s*Exception/);
  });

  test('should NOT reference ex.ToString() in the response body', () => {
    /**
     * Given ex.ToString() exposes the full stack trace and exception chain (NFR6)
     * When ExceptionHandlingMiddleware.cs is inspected
     * Then ex.ToString() is not used in building the response
     */
    const middlewarePath = path.join(API_SRC, 'Middleware/ExceptionHandlingMiddleware.cs');
    const content = fs.readFileSync(middlewarePath, 'utf-8');

    expect(
      content,
      'Middleware must NOT use ex.ToString() — it exposes stack traces (NFR6)'
    ).not.toContain('ex.ToString()');
  });

  test('should NOT reference InnerException in the response body', () => {
    /**
     * Given exposing InnerException leaks internal implementation details (NFR6)
     * When ExceptionHandlingMiddleware.cs is inspected
     * Then InnerException is not referenced in the response construction
     */
    const middlewarePath = path.join(API_SRC, 'Middleware/ExceptionHandlingMiddleware.cs');
    const content = fs.readFileSync(middlewarePath, 'utf-8');

    expect(
      content,
      'Middleware must NOT expose InnerException in the response — internal details must stay hidden (NFR6)'
    ).not.toContain('InnerException');
  });

  test('should use primary constructor injecting RequestDelegate (not field assignment)', () => {
    /**
     * Given .NET 10 uses primary constructor syntax for DI
     * When ExceptionHandlingMiddleware.cs is inspected
     * Then the RequestDelegate is injected via primary constructor parameter
     */
    const middlewarePath = path.join(API_SRC, 'Middleware/ExceptionHandlingMiddleware.cs');
    const content = fs.readFileSync(middlewarePath, 'utf-8');

    // Primary constructor: ExceptionHandlingMiddleware(RequestDelegate next)
    expect(
      content,
      'Middleware must inject RequestDelegate via primary constructor'
    ).toMatch(/ExceptionHandlingMiddleware\s*\(\s*RequestDelegate\s+next\s*\)/);
  });

  test('should write response using WriteAsJsonAsync (not WriteAsync with manual serialization)', () => {
    /**
     * Given ASP.NET Core provides WriteAsJsonAsync for typed JSON responses
     * When ExceptionHandlingMiddleware.cs is inspected
     * Then WriteAsJsonAsync is used (not manual JSON.Serialize + WriteAsync)
     */
    const middlewarePath = path.join(API_SRC, 'Middleware/ExceptionHandlingMiddleware.cs');
    const content = fs.readFileSync(middlewarePath, 'utf-8');

    expect(
      content,
      'Middleware must use WriteAsJsonAsync for consistent JSON serialization of ProblemDetails'
    ).toContain('WriteAsJsonAsync');
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// AC4 edge cases — AppDbContext model configuration ordering
// ─────────────────────────────────────────────────────────────────────────────

test.describe('AC4 edge cases — AppDbContext OnModelCreating call ordering', () => {
  test('should call base.OnModelCreating before ApplyConfigurationsFromAssembly', () => {
    /**
     * Given base.OnModelCreating must be called first (EF Core contract)
     * When AppDbContext.cs is inspected
     * Then base.OnModelCreating appears before ApplyConfigurationsFromAssembly
     */
    const dbContextPath = path.join(INFRASTRUCTURE_SRC, 'Data/AppDbContext.cs');
    const content = fs.readFileSync(dbContextPath, 'utf-8');

    const baseCallIndex = content.indexOf('base.OnModelCreating');
    const applyConfigsIndex = content.indexOf('ApplyConfigurationsFromAssembly');

    expect(baseCallIndex, 'base.OnModelCreating must be called in OnModelCreating').toBeGreaterThan(-1);
    expect(applyConfigsIndex, 'ApplyConfigurationsFromAssembly must be called in OnModelCreating').toBeGreaterThan(-1);

    expect(
      baseCallIndex,
      'base.OnModelCreating() must be called BEFORE ApplyConfigurationsFromAssembly()'
    ).toBeLessThan(applyConfigsIndex);
  });

  test('should NOT have any DbSet<> properties defined (empty baseline — no entities yet)', () => {
    /**
     * Given Story 1.3 creates an empty baseline (no domain tables)
     * When AppDbContext.cs is inspected
     * Then no DbSet<> properties are declared
     * (ClienteEntity: Epic 2 Story 2.1; ContactoEntity: Epic 3 Story 3.1)
     */
    const dbContextPath = path.join(INFRASTRUCTURE_SRC, 'Data/AppDbContext.cs');
    const content = fs.readFileSync(dbContextPath, 'utf-8');

    expect(
      content,
      'AppDbContext must NOT declare any DbSet<> properties in Story 1.3 — this is an empty baseline'
    ).not.toMatch(/public\s+DbSet</);
  });

  test('AppDbContext.cs should be in SiesaAgents.Infrastructure.Data namespace', () => {
    /**
     * Given AppDbContext lives in the Infrastructure layer under Data/
     * When the namespace declaration is inspected
     * Then it is SiesaAgents.Infrastructure.Data
     */
    const dbContextPath = path.join(INFRASTRUCTURE_SRC, 'Data/AppDbContext.cs');
    const content = fs.readFileSync(dbContextPath, 'utf-8');

    expect(
      content,
      'AppDbContext.cs must declare namespace SiesaAgents.Infrastructure.Data'
    ).toContain('namespace SiesaAgents.Infrastructure.Data');
  });

  test('AppDbContext.cs should use primary constructor pattern (options via constructor parameter)', () => {
    /**
     * Given .NET 10 favors primary constructors for DbContext
     * When AppDbContext.cs is inspected
     * Then the primary constructor passes options to the base DbContext
     */
    const dbContextPath = path.join(INFRASTRUCTURE_SRC, 'Data/AppDbContext.cs');
    const content = fs.readFileSync(dbContextPath, 'utf-8');

    // Primary constructor pattern: AppDbContext(DbContextOptions<AppDbContext> options) : DbContext(options)
    expect(
      content,
      'AppDbContext must use primary constructor passing DbContextOptions to base DbContext'
    ).toMatch(/AppDbContext\s*\(\s*DbContextOptions<AppDbContext>\s+options\s*\)\s*:\s*DbContext\s*\(\s*options\s*\)/);
  });

  test('UseSnakeCaseNamingConvention should be the LAST modelBuilder call in OnModelCreating', () => {
    /**
     * Given snake_case convention must override all other naming (including entity configurations)
     * When AppDbContext.cs is inspected
     * Then UseSnakeCaseNamingConvention() appears after all other modelBuilder calls
     */
    const dbContextPath = path.join(INFRASTRUCTURE_SRC, 'Data/AppDbContext.cs');
    const content = fs.readFileSync(dbContextPath, 'utf-8');

    const snakeCaseIndex = content.indexOf('UseSnakeCaseNamingConvention');
    const applyConfigsIndex = content.indexOf('ApplyConfigurationsFromAssembly');
    const baseCallIndex = content.indexOf('base.OnModelCreating');

    // snake_case must come after BOTH base.OnModelCreating and ApplyConfigurationsFromAssembly
    expect(snakeCaseIndex).toBeGreaterThan(baseCallIndex);
    expect(snakeCaseIndex).toBeGreaterThan(applyConfigsIndex);
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// AC5 edge cases — Project files: target framework and package configuration
// ─────────────────────────────────────────────────────────────────────────────

test.describe('AC5 edge cases — Target frameworks and package version boundaries', () => {
  test('Infrastructure.csproj should target net10.0', () => {
    /**
     * Given the project uses .NET 10 per company standards
     * When SiesaAgents.Infrastructure.csproj is inspected
     * Then TargetFramework is net10.0
     */
    const csprojPath = path.join(INFRASTRUCTURE_SRC, 'SiesaAgents.Infrastructure.csproj');
    const content = fs.readFileSync(csprojPath, 'utf-8');

    expect(
      content,
      'Infrastructure.csproj must target net10.0 per company .NET 10 standard'
    ).toContain('<TargetFramework>net10.0</TargetFramework>');
  });

  test('API.csproj should target net10.0', () => {
    /**
     * Given the project uses .NET 10 per company standards
     * When SiesaAgents.API.csproj is inspected
     * Then TargetFramework is net10.0
     */
    const csprojPath = path.join(API_SRC, 'SiesaAgents.API.csproj');
    const content = fs.readFileSync(csprojPath, 'utf-8');

    expect(
      content,
      'API.csproj must target net10.0 per company .NET 10 standard'
    ).toContain('<TargetFramework>net10.0</TargetFramework>');
  });

  test('Infrastructure.csproj Npgsql package should target version 10.*', () => {
    /**
     * Given EF Core 10 requires Npgsql.EntityFrameworkCore.PostgreSQL 10.x
     * When the Infrastructure.csproj is inspected
     * Then Npgsql package version is 10.* (aligned with EF Core 10)
     */
    const csprojPath = path.join(INFRASTRUCTURE_SRC, 'SiesaAgents.Infrastructure.csproj');
    const content = fs.readFileSync(csprojPath, 'utf-8');

    // Version must be 10.* for EF Core 10 compatibility
    expect(
      content,
      'Npgsql.EntityFrameworkCore.PostgreSQL must target version 10.* for EF Core 10 compatibility'
    ).toMatch(/Npgsql\.EntityFrameworkCore\.PostgreSQL"[^/]*Version="10\.\*/);
  });

  test('API.csproj EFCore.Design should have PrivateAssets=all (no runtime leakage)', () => {
    /**
     * Given EF Core Design is only needed for CLI tooling (not runtime)
     * When the API.csproj is inspected
     * Then Microsoft.EntityFrameworkCore.Design has PrivateAssets="all"
     * to prevent it from being included in published output
     */
    const csprojPath = path.join(API_SRC, 'SiesaAgents.API.csproj');
    const content = fs.readFileSync(csprojPath, 'utf-8');

    // The PrivateAssets must appear in the Design package entry (not just anywhere)
    expect(
      content,
      'Microsoft.EntityFrameworkCore.Design must specify PrivateAssets to exclude from runtime output'
    ).toMatch(/Microsoft\.EntityFrameworkCore\.Design[\s\S]*?PrivateAssets/);
  });

  test('UnitTests.csproj should reference Microsoft.EntityFrameworkCore.InMemory', () => {
    /**
     * Given unit tests use InMemory provider to test AppDbContext without PostgreSQL
     * When SiesaAgents.UnitTests.csproj is inspected
     * Then Microsoft.EntityFrameworkCore.InMemory is referenced
     */
    const csprojPath = path.join(BACKEND_ROOT, 'tests/SiesaAgents.UnitTests/SiesaAgents.UnitTests.csproj');
    expect(
      fs.existsSync(csprojPath),
      `SiesaAgents.UnitTests.csproj not found at ${csprojPath}`
    ).toBe(true);

    const content = fs.readFileSync(csprojPath, 'utf-8');

    expect(
      content,
      'UnitTests.csproj must reference Microsoft.EntityFrameworkCore.InMemory for AppDbContext unit tests'
    ).toContain('Microsoft.EntityFrameworkCore.InMemory');
  });

  test('UnitTests.csproj should reference Infrastructure project (for AppDbContext tests)', () => {
    /**
     * Given AppDbContextTests.cs imports SiesaAgents.Infrastructure.Data
     * When SiesaAgents.UnitTests.csproj is inspected
     * Then it contains a ProjectReference to SiesaAgents.Infrastructure
     */
    const csprojPath = path.join(BACKEND_ROOT, 'tests/SiesaAgents.UnitTests/SiesaAgents.UnitTests.csproj');
    const content = fs.readFileSync(csprojPath, 'utf-8');

    expect(
      content,
      'UnitTests.csproj must reference SiesaAgents.Infrastructure to access AppDbContext'
    ).toContain('SiesaAgents.Infrastructure');
  });

  test('Program.cs should NOT use app.UseSwagger() (Scalar-only rule)', () => {
    /**
     * Given the architecture mandates Scalar only (never Swagger UI)
     * When Program.cs is inspected
     * Then app.UseSwagger is absent
     */
    const programPath = path.join(API_SRC, 'Program.cs');
    const content = fs.readFileSync(programPath, 'utf-8');

    expect(
      content,
      'Program.cs must NOT call app.UseSwagger() — only Scalar is allowed (app.MapScalarApiReference)'
    ).not.toContain('UseSwagger');
  });

  test('Program.cs should use app.MapScalarApiReference() (not Swagger UI)', () => {
    /**
     * Given the architecture mandates Scalar as the only API docs UI
     * When Program.cs is inspected
     * Then MapScalarApiReference is registered
     */
    const programPath = path.join(API_SRC, 'Program.cs');
    const content = fs.readFileSync(programPath, 'utf-8');

    expect(
      content,
      'Program.cs must call app.MapScalarApiReference() as the sole API documentation endpoint'
    ).toContain('MapScalarApiReference');
  });

  test('Infrastructure.csproj should NOT reference SiesaAgents.API project (no upward dependency)', () => {
    /**
     * Given Clean Architecture prohibits Infrastructure from depending on API
     * When Infrastructure.csproj is inspected
     * Then no ProjectReference to SiesaAgents.API exists
     */
    const csprojPath = path.join(INFRASTRUCTURE_SRC, 'SiesaAgents.Infrastructure.csproj');
    const content = fs.readFileSync(csprojPath, 'utf-8');

    expect(
      content,
      'Infrastructure.csproj must NOT reference SiesaAgents.API (Clean Architecture violation)'
    ).not.toContain('SiesaAgents.API');
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// AC3+AC4 combined — middleware and context integration boundary
// ─────────────────────────────────────────────────────────────────────────────

test.describe('Integration boundary — middleware and context wiring in Program.cs', () => {
  test('Program.cs should have exactly one ExceptionHandlingMiddleware registration', () => {
    /**
     * Given registering the middleware twice would cause duplicate error handling
     * When Program.cs is inspected
     * Then UseMiddleware<ExceptionHandlingMiddleware> appears exactly once
     */
    const programPath = path.join(API_SRC, 'Program.cs');
    const content = fs.readFileSync(programPath, 'utf-8');

    const count = (content.match(/UseMiddleware<ExceptionHandlingMiddleware>/g) ?? []).length;

    expect(
      count,
      'UseMiddleware<ExceptionHandlingMiddleware>() must appear exactly once in Program.cs'
    ).toBe(1);
  });

  test('Program.cs should have exactly one AddDbContext<AppDbContext> registration', () => {
    /**
     * Given registering AppDbContext twice would cause ambiguous DI resolution
     * When Program.cs is inspected
     * Then AddDbContext<AppDbContext> appears exactly once
     */
    const programPath = path.join(API_SRC, 'Program.cs');
    const content = fs.readFileSync(programPath, 'utf-8');

    const count = (content.match(/AddDbContext<AppDbContext>/g) ?? []).length;

    expect(
      count,
      'AddDbContext<AppDbContext> must be registered exactly once in Program.cs'
    ).toBe(1);
  });

  test('Program.cs should call app.Run() at the end (not return early)', () => {
    /**
     * Given app.Run() is required to start the Kestrel HTTP server
     * When Program.cs is inspected
     * Then app.Run() is present
     */
    const programPath = path.join(API_SRC, 'Program.cs');
    const content = fs.readFileSync(programPath, 'utf-8');

    expect(
      content,
      'Program.cs must call app.Run() to start the server'
    ).toContain('app.Run()');
  });

  test('ExceptionHandlingMiddleware registration should come before app.UseCors in Program.cs', () => {
    /**
     * Given ExceptionHandlingMiddleware must handle CORS-related errors too
     * When the middleware pipeline order is inspected in Program.cs
     * Then ExceptionHandlingMiddleware is registered before UseCors
     */
    const programPath = path.join(API_SRC, 'Program.cs');
    const content = fs.readFileSync(programPath, 'utf-8');

    const exceptionIndex = content.indexOf('UseMiddleware<ExceptionHandlingMiddleware>');
    const corsIndex = content.indexOf('UseCors');

    expect(exceptionIndex).toBeGreaterThan(-1);
    expect(corsIndex).toBeGreaterThan(-1);
    expect(
      exceptionIndex,
      'ExceptionHandlingMiddleware must be first in the pipeline (before UseCors)'
    ).toBeLessThan(corsIndex);
  });
});
