// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SiesaAgents.Infrastructure.Data;

#nullable disable

namespace SiesaAgents.Infrastructure.Data.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260524100000_AddClientesTable")]
partial class AddClientesTable
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("SiesaAgents.Domain.Clientes.Entities.ClienteEntity", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<string>("Ciudad")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("ciudad");

            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at");

            b.Property<string>("NIT")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("nit");

            b.Property<string>("Nombre")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("nombre");

            b.Property<string>("Telefono")
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("telefono");

            b.Property<DateTimeOffset>("UpdatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("updated_at");

            b.HasKey("Id").HasName("pk_clientes");

            b.HasIndex("NIT")
                .IsUnique()
                .HasDatabaseName("uk_clientes_nit");

            b.ToTable("clientes");
        });
#pragma warning restore 612, 618
    }
}
