// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SiesaAgents.Infrastructure.Data;

#nullable disable

namespace SiesaAgents.Infrastructure.Data.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        // NOTE: UseIdentityByDefaultColumns removed — project uses UUID PKs exclusively (Guid.NewGuid()).
        // Integer identity sequences are not used per company standards.
        // Re-run `dotnet ef migrations add InitialCreate` after .NET 10 SDK is available to regenerate this snapshot.
#pragma warning restore 612, 618
    }
}
