import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { RouterProvider, createRouter } from '@tanstack/react-router'
// TODO: Import siesa-ui-kit styles once installed: import 'siesa-ui-kit/dist/styles.css'
import './index.css'

// Auto-generated by TanStackRouterVite plugin — run `pnpm dev` after installing @tanstack/router-plugin
import { routeTree } from './routeTree.gen'

const router = createRouter({ routeTree })

// Register router for type-safety
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}

const rootElement = document.getElementById('root')
if (!rootElement) throw new Error('Root element not found')

createRoot(rootElement).render(
  <StrictMode>
    <RouterProvider router={router} />
  </StrictMode>,
)
