/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Route Tree

import { createRouter as createTanStackRouter } from '@tanstack/react-router'

export const routeTree = rootRoute
