/**
 * Story 1.2 — Frontend Navigation Shell
 * Epic 1: Project Foundation & Application Shell
 *
 * Expanded E2E coverage — edge cases, error paths, boundary conditions.
 * Complements the happy-path ATDD suite (navigation-shell.spec.ts).
 *
 * Generated by testarch-automate (BMad-Integrated Mode).
 *
 * Coverage focus:
 *   - Rapid SPA navigation (Clientes ↔ Contactos multiple times) — no full reload
 *   - Browser back / forward across SPA navigations (HTML5 history)
 *   - Deep link to a NESTED unknown route (e.g. /clientes/non-existent) — root
 *     notFoundComponent fires consistently
 *   - URL fragment / querystring tolerance (/clientes?filter=foo, /clientes#anchor)
 *   - Index redirect does not introduce intermediate visible flash content
 *   - Keyboard navigation: Tab reaches nav entries, Enter activates them (WCAG 2.1 AA)
 *   - Touch target ≥ 44×44px on mobile NavigationBar (AC #2 / FR29)
 *   - Console hygiene: no React warnings or errors on a clean SPA round-trip
 *   - Bundle availability: hashed main asset is fetched without 4xx/5xx
 *
 * Test rules (per project standards):
 *   - data-testid selectors first (no fragile CSS).
 *   - Network-first: intercepts/listeners registered BEFORE page.goto.
 *   - No hard waits; only explicit Playwright locator assertions.
 *   - Given-When-Then commentary on every test.
 *   - Priority tag `[Pn]` embedded in test name for selective CI execution.
 */

import { test, expect } from '@playwright/test'

test.describe('[E2E] Story 1.2 — Navigation shell SPA stability (edge cases)', () => {
  test('[P0] should perform 4 round-trip SPA navigations without a full document reload', async ({
    page,
  }) => {
    // GIVEN: a clean session at /clientes, with a load counter listening for hard reloads
    let loadCount = 0
    page.on('load', () => {
      loadCount += 1
    })

    await page.goto('/clientes')
    await expect(page.getByTestId('app-root')).toBeVisible()
    const initialLoadCount = loadCount

    // WHEN: we round-trip Clientes ↔ Contactos four times via the rail / bar
    for (let i = 0; i < 4; i += 1) {
      await page.getByRole('button', { name: /ir a contactos/i }).first().click()
      await expect(page).toHaveURL(/\/contactos$/)
      await page.getByRole('button', { name: /ir a clientes/i }).first().click()
      await expect(page).toHaveURL(/\/clientes$/)
    }

    // THEN: no additional `load` events fired (SPA navigation never re-downloads the document)
    expect(loadCount).toBe(initialLoadCount)
  })

  test('[P1] should restore the previous route on browser Back via HTML5 history', async ({
    page,
  }) => {
    // GIVEN: the user navigates from /clientes to /contactos via the SPA
    await page.goto('/clientes')
    await page.getByRole('button', { name: /ir a contactos/i }).first().click()
    await expect(page).toHaveURL(/\/contactos$/)

    // WHEN: the user presses the browser Back button
    await page.goBack()

    // THEN: pathname returns to /clientes and the placeholder view re-renders
    await expect(page).toHaveURL(/\/clientes$/)
    await expect(
      page.getByRole('heading', { level: 1, name: /^clientes$/i }),
    ).toBeVisible()
  })

  test('[P1] should restore the next route on browser Forward via HTML5 history', async ({
    page,
  }) => {
    // GIVEN: the user navigated /clientes → /contactos → Back to /clientes
    await page.goto('/clientes')
    await page.getByRole('button', { name: /ir a contactos/i }).first().click()
    await expect(page).toHaveURL(/\/contactos$/)
    await page.goBack()
    await expect(page).toHaveURL(/\/clientes$/)

    // WHEN: the user presses the browser Forward button
    await page.goForward()

    // THEN: pathname advances back to /contactos and the placeholder view renders
    await expect(page).toHaveURL(/\/contactos$/)
    await expect(
      page.getByRole('heading', { level: 1, name: /^contactos$/i }),
    ).toBeVisible()
  })
})

test.describe('[E2E] Story 1.2 — Unknown route variations (AC #5)', () => {
  test('[P1] should render NotFoundView for a NESTED unknown path under /clientes', async ({
    page,
  }) => {
    // GIVEN: a clean session
    // WHEN: the user deep-links to an unknown nested clientes route (Epic 2 detail does not exist yet)
    await page.goto('/clientes/some-id-that-does-not-exist')

    // THEN: NotFoundView (Spanish) renders inside the shell — root notFoundComponent fires
    await expect(page.getByTestId('app-root')).toBeVisible()
    await expect(page.getByText(/página no encontrada/i)).toBeVisible()
  })

  test('[P1] should render NotFoundView for a NESTED unknown path under /contactos', async ({
    page,
  }) => {
    // GIVEN: a clean session
    // WHEN: the user deep-links to an unknown nested contactos route
    await page.goto('/contactos/no-existe')

    // THEN: NotFoundView renders with the shell still visible
    await expect(page.getByTestId('app-root')).toBeVisible()
    await expect(page.getByText(/página no encontrada/i)).toBeVisible()
  })

  test('[P2] should render NotFoundView for a multi-segment unknown root path', async ({
    page,
  }) => {
    // GIVEN: a clean session
    // WHEN: the user deep-links to a deep unknown route
    await page.goto('/foo/bar/baz/qux')

    // THEN: NotFoundView is rendered and the shell is still mounted
    await expect(page.getByTestId('app-root')).toBeVisible()
    await expect(page.getByText(/página no encontrada/i)).toBeVisible()
    await expect(page.getByRole('link', { name: /ir a clientes/i })).toBeVisible()
  })
})

test.describe('[E2E] Story 1.2 — URL variations on known routes', () => {
  test('[P2] should tolerate a querystring on /clientes (filter / search params do not break the route)', async ({
    page,
  }) => {
    // GIVEN: a clean session
    // WHEN: the user opens /clientes with a querystring
    await page.goto('/clientes?filter=activos&page=2')

    // THEN: the Clientes placeholder still renders (querystring is preserved in URL but ignored by the route match)
    await expect(page).toHaveURL(/\/clientes\?filter=activos&page=2$/)
    await expect(
      page.getByRole('heading', { level: 1, name: /^clientes$/i }),
    ).toBeVisible()
  })

  test('[P2] should tolerate a hash fragment on /contactos (URL anchors do not break the route)', async ({
    page,
  }) => {
    // GIVEN: a clean session
    // WHEN: the user opens /contactos with a hash fragment
    await page.goto('/contactos#top')

    // THEN: the Contactos placeholder still renders
    await expect(page).toHaveURL(/\/contactos#top$/)
    await expect(
      page.getByRole('heading', { level: 1, name: /^contactos$/i }),
    ).toBeVisible()
  })
})

test.describe('[E2E] Story 1.2 — Index redirect quality (AC #6)', () => {
  test('[P1] should not display intermediate "landing" content during the / → /clientes redirect', async ({
    page,
  }) => {
    // GIVEN: a clean session
    // WHEN: the user opens "/" (which redirects via beforeLoad)
    await page.goto('/')

    // THEN: pathname is /clientes AND there is no leftover landing-page copy
    // The legacy temporary landing copy used the literal "Siesa Agents CRM" string in an <h1> —
    // verifying we do not see that proves no flash of the prior placeholder during the redirect.
    await expect(page).toHaveURL(/\/clientes$/)
    await expect(
      page.getByRole('heading', { level: 1, name: /^siesa agents crm$/i }),
    ).toHaveCount(0)
    await expect(
      page.getByRole('heading', { level: 1, name: /^clientes$/i }),
    ).toBeVisible()
  })

  test('[P2] should preserve trailing-slash deep link "/clientes/" without 404', async ({
    page,
  }) => {
    // GIVEN: a clean session
    // WHEN: the user types /clientes/ with a trailing slash
    await page.goto('/clientes/')

    // THEN: the Clientes placeholder still renders (TanStack Router normalizes trailing slashes by default)
    await expect(
      page.getByRole('heading', { level: 1, name: /^clientes$/i }),
    ).toBeVisible()
  })
})

test.describe('[E2E] Story 1.2 — Accessibility (AC #8, WCAG 2.1 AA)', () => {
  test('[P1] should expose a focusable button for each desktop nav entry (Tab order check)', async ({
    page,
  }) => {
    // GIVEN: a desktop viewport so the rail is the active surface
    await page.setViewportSize({ width: 1280, height: 800 })
    await page.goto('/clientes')

    // WHEN: the user tabs into the shell
    // We focus the first nav entry by accessible name (more deterministic than counting Tab presses
    // across the productName chrome which varies with siesa-ui-kit versions).
    const clientesNav = page.getByRole('button', { name: /ir a clientes/i }).first()
    await clientesNav.focus()

    // THEN: focus lands on the Clientes nav entry
    await expect(clientesNav).toBeFocused()
  })

  test('[P1] should activate navigation when Enter is pressed on a focused nav entry', async ({
    page,
  }) => {
    // GIVEN: the user is on /clientes with focus on the Contactos rail entry
    await page.setViewportSize({ width: 1280, height: 800 })
    await page.goto('/clientes')
    const contactosNav = page.getByRole('button', { name: /ir a contactos/i }).first()
    await contactosNav.focus()
    await expect(contactosNav).toBeFocused()

    // WHEN: the user presses Enter
    await page.keyboard.press('Enter')

    // THEN: the router navigates to /contactos via SPA navigation
    await expect(page).toHaveURL(/\/contactos$/)
  })

  test('[P2] should activate navigation when Space is pressed on a focused nav entry', async ({
    page,
  }) => {
    // GIVEN: the user is on /clientes with focus on Contactos
    await page.setViewportSize({ width: 1280, height: 800 })
    await page.goto('/clientes')
    const contactosNav = page.getByRole('button', { name: /ir a contactos/i }).first()
    await contactosNav.focus()

    // WHEN: the user presses Space
    await page.keyboard.press('Space')

    // THEN: navigation happens
    await expect(page).toHaveURL(/\/contactos$/)
  })

  test('[P2] should NOT remove the focus outline on nav entries (preserve siesa-ui-kit focus rings)', async ({
    page,
  }) => {
    // GIVEN: a desktop viewport
    await page.setViewportSize({ width: 1280, height: 800 })
    await page.goto('/clientes')

    // WHEN: a nav entry is focused
    const clientesNav = page.getByRole('button', { name: /ir a clientes/i }).first()
    await clientesNav.focus()

    // THEN: the outline shorthand is NOT "none" / "0" — i.e. some focus indicator is rendered.
    // (We do not assert an exact pixel — that varies per browser/theme — only that the indicator
    // has not been suppressed by a stray `outline: none` declaration, which is the most common
    // WCAG 2.1 AA regression.)
    const outlineStyle = await clientesNav.evaluate((el) => {
      const cs = window.getComputedStyle(el)
      return {
        outlineStyle: cs.outlineStyle,
        outlineWidth: cs.outlineWidth,
        boxShadow: cs.boxShadow,
      }
    })
    const hasFocusIndicator =
      outlineStyle.outlineStyle !== 'none' || outlineStyle.boxShadow !== 'none'
    expect(hasFocusIndicator).toBe(true)
  })
})

test.describe('[E2E] Story 1.2 — Responsive boundary (AC #1, #2)', () => {
  test('[P2] should activate the desktop rail at exactly the lg breakpoint (1024px)', async ({
    page,
  }) => {
    // GIVEN: the viewport is at the exact lg breakpoint (1024px)
    await page.setViewportSize({ width: 1024, height: 800 })

    // WHEN: the user opens /clientes
    await page.goto('/clientes')

    // THEN: the desktop rail container is visible at 1024px
    await expect(page.getByTestId('shell-rail-container')).toBeVisible()
  })

  test('[P2] should activate the mobile bar one pixel below the lg breakpoint (1023px)', async ({
    page,
  }) => {
    // GIVEN: the viewport is at 1023px (one pixel below `lg:`)
    await page.setViewportSize({ width: 1023, height: 800 })

    // WHEN: the user opens /clientes
    await page.goto('/clientes')

    // THEN: the mobile NavigationBar container is visible at 1023px
    await expect(page.getByTestId('shell-mobile-nav')).toBeVisible()
  })

  test('[P2] mobile NavigationBar items meet the ≥44×44px touch target requirement (AC #2 / FR29)', async ({
    page,
  }) => {
    // GIVEN: a mobile viewport
    await page.setViewportSize({ width: 375, height: 800 })

    // WHEN: the user opens /clientes
    await page.goto('/clientes')

    // THEN: each mobile nav touch target is at least 44×44 CSS px. WCAG 2.5.5 / Apple HIG measure the
    // *interactive target* — which on the siesa-ui-kit NavigationBar is the row item (the parent of
    // the icon-only button). The inner <button> bounding box may be smaller than 44px tall when the
    // tap area is extended via padding on the parent <li>/<a> row, so we walk up to the closest
    // interactive ancestor (or list item / link) and assert THAT box.
    const mobileNav = page.getByTestId('shell-mobile-nav')
    await expect(mobileNav).toBeVisible()

    const clientesMobile = mobileNav.getByRole('button', { name: /ir a clientes/i }).first()
    const contactosMobile = mobileNav.getByRole('button', { name: /ir a contactos/i }).first()

    // Compute the maximum tap-target box across the button itself and its ancestors up to the
    // NavigationBar root. The biggest box represents the actual hit area the user touches.
    const tapBox = async (locator: typeof clientesMobile) => {
      return locator.evaluate((el) => {
        const root = el.closest('[data-testid="shell-mobile-nav"]') ?? document.body
        let node: HTMLElement | null = el as HTMLElement
        let bestW = 0
        let bestH = 0
        while (node && node !== root) {
          const rect = node.getBoundingClientRect()
          if (rect.width > bestW) bestW = rect.width
          if (rect.height > bestH) bestH = rect.height
          node = node.parentElement
        }
        return { width: bestW, height: bestH }
      })
    }

    const clientesTap = await tapBox(clientesMobile)
    const contactosTap = await tapBox(contactosMobile)

    expect(clientesTap.width).toBeGreaterThanOrEqual(44)
    expect(clientesTap.height).toBeGreaterThanOrEqual(44)
    expect(contactosTap.width).toBeGreaterThanOrEqual(44)
    expect(contactosTap.height).toBeGreaterThanOrEqual(44)
  })
})

test.describe('[E2E] Story 1.2 — Runtime hygiene', () => {
  test('[P1] should not emit React warnings/errors during a clean SPA round-trip', async ({
    page,
  }) => {
    // GIVEN: a clean session with console listeners attached BEFORE any navigation
    const noisy: string[] = []
    page.on('console', (msg) => {
      const type = msg.type()
      if (type === 'error' || type === 'warning') {
        const text = msg.text()
        // Ignore the benign jsdom-style "scrollTo not implemented" warning if any browser echoes it,
        // and the React DevTools recommendation banner that Chromium can emit.
        if (text.includes('Download the React DevTools')) return
        noisy.push(`${type}: ${text}`)
      }
    })
    page.on('pageerror', (err) => {
      noisy.push(`pageerror: ${err.message}`)
    })

    // WHEN: the user does a representative SPA round trip
    await page.goto('/clientes')
    await page.getByRole('button', { name: /ir a contactos/i }).first().click()
    await expect(page).toHaveURL(/\/contactos$/)
    await page.getByRole('button', { name: /ir a clientes/i }).first().click()
    await expect(page).toHaveURL(/\/clientes$/)

    // THEN: no React warnings, errors, or uncaught page errors were emitted
    expect(noisy).toEqual([])
  })

  test('[P2] should fetch the hashed main JS bundle without a 4xx/5xx response', async ({
    page,
  }) => {
    // GIVEN: a clean session with a response listener registered BEFORE navigation (network-first)
    const badJsResponses: { url: string; status: number }[] = []
    page.on('response', (resp) => {
      const url = resp.url()
      const status = resp.status()
      if (url.endsWith('.js') && status >= 400) {
        badJsResponses.push({ url, status })
      }
    })

    // WHEN: the user opens /clientes (which causes Vite to serve the JS bundle in build mode or
    // the dev modules in dev mode — either way no JS asset should 4xx/5xx).
    await page.goto('/clientes')
    await expect(page.getByTestId('app-root')).toBeVisible()

    // THEN: no JS asset failed
    expect(badJsResponses).toEqual([])
  })
})
