/**
 * Story 1.1: Project Initialization & Repository Structure
 * Epic 1: Project Foundation & Application Shell
 *
 * AUTOMATION EXPANSION — Edge Cases & Boundary Conditions
 * Expands ATDD coverage with error paths, boundary conditions,
 * and negative cases not covered in the ATDD RED-phase tests.
 *
 * Focus areas:
 *   - Frontend content negotiation and resource loading edge cases
 *   - Vite dev server stability under repeated requests
 *   - Environment variable correctness
 *   - React render lifecycle (no double-mount, no orphan nodes)
 *   - Performance boundary: initial load within acceptable time
 */

import { test, expect } from '@playwright/test';

const FRONTEND_BASE_URL = 'http://localhost:5173';

// ─────────────────────────────────────────────────────────────────────────────
// Content negotiation and HTTP response headers
// ─────────────────────────────────────────────────────────────────────────────

test.describe('[P1] Frontend — HTTP response quality and content type', () => {
  test('[P1] should serve index.html with text/html content-type on root path', async ({
    request,
  }) => {
    // GIVEN: Vite dev server is running on port 5173
    // WHEN: A GET request is made to the root path
    const response = await request.get(FRONTEND_BASE_URL + '/');

    // THEN: Content-Type header indicates HTML document
    const contentType = response.headers()['content-type'] ?? '';
    expect(contentType).toContain('text/html');
  });

  test('[P1] should include a valid charset declaration in HTML content-type', async ({
    request,
  }) => {
    // GIVEN: Vite generates index.html with UTF-8 content
    // WHEN: The root path is requested
    const response = await request.get(FRONTEND_BASE_URL + '/');

    // THEN: Content-Type declares UTF-8 charset (required for i18n — Spanish UI)
    const contentType = response.headers()['content-type'] ?? '';
    expect(contentType.toLowerCase()).toContain('utf-8');
  });

  test('[P1] should return HTTP 200 for root path (not redirect to /index.html)', async ({
    request,
  }) => {
    // GIVEN: Vite serves a single-page application
    // WHEN: The root URL is accessed directly
    const response = await request.get(FRONTEND_BASE_URL + '/');

    // THEN: Response is 200, not a redirect — SPA root must be served directly
    expect(response.status()).toBe(200);
  });

  test('[P2] should return HTTP 200 for unknown SPA sub-routes (client-side routing)', async ({
    request,
  }) => {
    // GIVEN: TanStack Router handles routing client-side
    // WHEN: A request is made to an unknown route like /some-spa-route
    const response = await request.get(FRONTEND_BASE_URL + '/some-nonexistent-spa-route');

    // THEN: Vite dev server returns the index.html (200) — not 404 — to allow client routing
    // Note: Vite in dev mode serves index.html for non-asset paths (SPA fallback)
    expect(response.status()).toBe(200);
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// React DOM and application root edge cases
// ─────────────────────────────────────────────────────────────────────────────

test.describe('[P1] Frontend — React mount and DOM structure', () => {
  test('[P1] should have exactly one root mount point in the HTML document', async ({ page }) => {
    // GIVEN: main.tsx calls createRoot(document.getElementById("root")!)
    // WHEN: The page loads
    await page.goto('/');

    // THEN: There is exactly one #root element (no duplicate mount points)
    const rootCount = await page.locator('#root').count();
    expect(rootCount).toBe(1);
  });

  test('[P1] should not render an empty #root element after hydration', async ({ page }) => {
    // GIVEN: React renders the RouterProvider and QueryProvider inside #root
    // WHEN: The app is fully loaded
    await page.goto('/');
    await page.waitForLoadState('networkidle');

    // THEN: #root has inner content (React mounted successfully, not blank)
    const rootInnerHTML = await page.locator('#root').innerHTML();
    expect(rootInnerHTML.trim()).not.toBe('');
  });

  test('[P1] should have lang attribute on <html> element for accessibility', async ({ page }) => {
    // GIVEN: index.html is generated by Vite
    // WHEN: The page loads
    await page.goto('/');

    // THEN: The <html> element has a lang attribute (required by WCAG 3.1.1)
    // index.html has lang="en" — acceptable for initial scaffold
    const lang = await page.locator('html').getAttribute('lang');
    expect(lang).toBeTruthy();
  });

  test('[P2] should have a viewport meta tag for mobile responsiveness', async ({ page }) => {
    // GIVEN: The app will serve mobile users (Pixel 5 in test matrix)
    // WHEN: The page loads
    await page.goto('/');

    // THEN: A viewport meta tag is present (required for responsive layouts)
    const viewportMeta = page.locator('meta[name="viewport"]');
    await expect(viewportMeta).toHaveCount(1);
  });

  test('[P2] should include the main JavaScript bundle in the HTML document', async ({ page }) => {
    // GIVEN: Vite injects the <script type="module" src="/src/main.tsx"> tag
    // WHEN: The page loads
    await page.goto('/');

    // THEN: A module script tag is present pointing to the app entry point
    const scriptTag = page.locator('script[type="module"]');
    await expect(scriptTag).toHaveCount(1);
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// Performance boundary — initial load time
// ─────────────────────────────────────────────────────────────────────────────

test.describe('[P2] Frontend — Load performance boundaries', () => {
  test('[P2] should complete initial HTML load within 5 seconds', async ({ page }) => {
    // GIVEN: The Vite dev server is running (warm, not cold start)
    // WHEN: A navigation is initiated
    const startTime = Date.now();
    await page.goto('/');
    await page.waitForLoadState('domcontentloaded');
    const loadTime = Date.now() - startTime;

    // THEN: DOM content loads within 5 000 ms (dev server, not production)
    expect(loadTime).toBeLessThan(5000);
  });

  test('[P2] should complete full network idle within 15 seconds on initial load', async ({
    page,
  }) => {
    // GIVEN: Vite with HMR and module bundling may trigger multiple network requests
    // WHEN: The app loads all its assets
    const startTime = Date.now();
    await page.goto('/');
    await page.waitForLoadState('networkidle');
    const loadTime = Date.now() - startTime;

    // THEN: All network activity settles within 15 000 ms in dev mode
    expect(loadTime).toBeLessThan(15000);
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// Stability — server handles concurrent and repeated requests
// ─────────────────────────────────────────────────────────────────────────────

test.describe('[P2] Frontend — Server stability under repeated requests', () => {
  test('[P2] should serve identical HTTP 200 responses on three consecutive loads', async ({
    request,
  }) => {
    // GIVEN: The Vite dev server is stateless for GET / requests
    // WHEN: Three consecutive GET / requests are made
    const responses = await Promise.all([
      request.get(FRONTEND_BASE_URL + '/'),
      request.get(FRONTEND_BASE_URL + '/'),
      request.get(FRONTEND_BASE_URL + '/'),
    ]);

    // THEN: All three responses return HTTP 200 (no transient failures)
    for (const response of responses) {
      expect(response.status()).toBe(200);
    }
  });

  test('[P2] should not accumulate console errors across two navigations to the same page', async ({
    page,
  }) => {
    // GIVEN: React and TanStack Router are properly initialized
    // WHEN: The user navigates to the root route twice (simulates browser back/forward)
    const consoleErrors: string[] = [];
    page.on('console', (msg) => {
      if (msg.type() === 'error') consoleErrors.push(msg.text());
    });

    await page.goto('/');
    await page.waitForLoadState('networkidle');
    await page.reload();
    await page.waitForLoadState('networkidle');

    // THEN: No console errors accumulate from duplicate React mounts or router re-initialization
    expect(consoleErrors).toHaveLength(0);
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// Static asset accessibility
// ─────────────────────────────────────────────────────────────────────────────

test.describe('[P3] Frontend — Static asset availability', () => {
  test('[P3] should serve /vite.svg favicon referenced in index.html', async ({ request }) => {
    // GIVEN: index.html references /vite.svg as the favicon
    // WHEN: The favicon is requested by the browser
    const response = await request.get(FRONTEND_BASE_URL + '/vite.svg');

    // THEN: The favicon is served without 404
    expect(response.status()).toBe(200);
  });

  test('[P3] should respond to HEAD request on root path without body errors', async ({
    request,
  }) => {
    // GIVEN: Vite dev server handles standard HTTP methods
    // WHEN: A HEAD request is sent to the root path
    const response = await request.fetch(FRONTEND_BASE_URL + '/', { method: 'HEAD' });

    // THEN: HEAD responds with 200 and no body (not 405 Method Not Allowed)
    expect(response.status()).toBe(200);
  });
});
