/**
 * Story 1.1: Project Initialization & Repository Structure
 * Epic 1: Project Foundation & Application Shell
 *
 * Automation Expansion — Edge Cases & Boundary Conditions (E2E level)
 * Generated by *automate after ATDD (project-initialization.spec.ts) went GREEN.
 * Focus: scenarios NOT covered by the original ATDD suite — static asset
 * serving, mobile viewport rendering, and resiliency across reloads.
 *
 * Acceptance Criteria covered:
 *   AC1 — Frontend Vite server starts on port 5173 with no errors
 *   AC4 — TypeScript strict mode compiles with zero errors
 */

import { test, expect, devices } from '@playwright/test';

// ─────────────────────────────────────────────────────────────────────────────
// AC1 edge cases: static asset serving & mobile viewport
// ─────────────────────────────────────────────────────────────────────────────

test.describe('AC1 — Frontend static assets and mobile rendering (edge cases)', () => {
  test('[P2] should serve the favicon asset referenced in index.html with a successful status', async ({
    page,
  }) => {
    // GIVEN: index.html declares <link rel="icon" href="/favicon.svg">
    // WHEN: The browser requests the favicon asset directly
    const faviconResponse = await page.request.get('/favicon.svg');

    // THEN: The asset is served successfully (Vite public/ dir is wired)
    expect(faviconResponse.status()).toBe(200);
  });

  test('[P2] should declare a mobile viewport meta tag for responsive rendering', async ({ page }) => {
    // GIVEN: The frontend must support mobile browsers (epic AC-E1.1)
    // WHEN: The root document loads
    await page.goto('/');

    // THEN: A viewport meta tag with device-width is present in the DOM
    const viewportContent = await page
      .locator('meta[name="viewport"]')
      .getAttribute('content');
    expect(viewportContent).toContain('width=device-width');
  });

  test('[P1] should render the app root without errors on a mobile viewport', async ({ browser }) => {
    // GIVEN: A mobile browser context (Pixel 5 emulation)
    const context = await browser.newContext({ ...devices['Pixel 5'] });

    try {
      const page = await context.newPage();

      const runtimeErrors: string[] = [];
      page.on('pageerror', (err) => runtimeErrors.push(err.message));

      // WHEN: The app loads on the mobile viewport
      await page.goto('/');

      // THEN: The app root is visible and no runtime errors occurred
      await expect(page.locator('[data-testid="app-root"]')).toBeVisible();
      expect(runtimeErrors).toHaveLength(0);
    } finally {
      // Auto-cleanup: guarantee context teardown even if an assertion above throws,
      // preventing leaked browser contexts across the suite (isolation/perf risk).
      await context.close();
    }
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// AC1/AC4 edge case: repeated navigation stays deterministic (no dev-server flakiness)
// ─────────────────────────────────────────────────────────────────────────────

test.describe('AC1/AC4 — Repeated reloads remain stable (boundary condition)', () => {
  test('[P2] should reload the app twice in a row without runtime or console errors', async ({ page }) => {
    // GIVEN: The Vite dev server is running
    const errors: string[] = [];
    page.on('pageerror', (err) => errors.push(err.message));
    page.on('console', (msg) => {
      if (msg.type() === 'error') errors.push(msg.text());
    });

    // WHEN: The page is loaded and reloaded (simulates dev HMR / repeated visits)
    await page.goto('/');
    await expect(page.locator('[data-testid="app-root"]')).toBeVisible();
    await page.reload();
    await expect(page.locator('[data-testid="app-root"]')).toBeVisible();

    // THEN: No errors accumulated across either load
    expect(errors).toHaveLength(0);
  });
});
