/**
 * Story 1.1: Project Initialization & Repository Structure
 * Epic 1: Project Foundation & Application Shell
 *
 * Expanded E2E coverage — edge cases, error paths, boundary conditions.
 * Complements the happy-path ATDD suite (project-initialization.spec.ts).
 *
 * Generated by testarch-automate (BMad-Integrated Mode).
 *
 * Coverage focus:
 *   - React shell mount integrity beyond initial load
 *   - TailwindCSS v4 styles applied (visual sanity)
 *   - Console hygiene: no warnings about missing keys, deprecated APIs, hydration mismatches
 *   - QueryClient + Router providers wire correctly (no provider errors)
 *   - Behavior on unknown frontend routes (TanStack Router default)
 *   - Direct backend-from-browser fetch via Axios apiClient defaults
 */

import { test, expect } from '@playwright/test';

const API_BASE_URL = process.env.API_BASE_URL ?? 'http://localhost:5000';

// ─────────────────────────────────────────────────────────────────────────────
// [P0] Shell integrity — beyond the smoke load
// ─────────────────────────────────────────────────────────────────────────────

test.describe('[E2E] Frontend shell integrity — edge cases', () => {
  test('[P0] should mount the #root element with a non-empty React tree', async ({ page }) => {
    // GIVEN: main.tsx mounts the React tree into <div id="root">
    // WHEN: The page finishes loading
    await page.goto('/');

    // THEN: #root exists AND contains the app-root child (proves React mounted)
    const root = page.locator('#root');
    await expect(root).toBeAttached();
    const appRoot = root.locator('[data-testid="app-root"]');
    await expect(appRoot).toBeVisible();
  });

  test('[P1] should not emit any React hydration or key-warning messages on initial load', async ({ page }) => {
    // GIVEN: Strict mode is enabled — common dev warnings would be loud
    const warnings: string[] = [];
    page.on('console', (msg) => {
      if (msg.type() === 'warning') {
        warnings.push(msg.text());
      }
    });

    // WHEN: The page loads and idle settles
    await page.goto('/', { waitUntil: 'networkidle' });

    // THEN: No warnings about hydration mismatch or missing list keys
    const blockerPatterns = [/hydrat/i, /unique "key" prop/i, /each child in a list/i];
    const offenders = warnings.filter((w) => blockerPatterns.some((p) => p.test(w)));
    expect(offenders, `Unexpected React warnings:\n${offenders.join('\n')}`).toHaveLength(0);
  });

  test('[P1] should serve the Vite dev client (HMR runtime) without 404', async ({ page }) => {
    // GIVEN: Vite injects /@vite/client into the page in dev mode
    // WHEN: Inspecting requests on initial load
    const viteClientResponses: number[] = [];
    page.on('response', (response) => {
      if (response.url().includes('/@vite/client')) {
        viteClientResponses.push(response.status());
      }
    });

    await page.goto('/', { waitUntil: 'networkidle' });

    // THEN: The Vite HMR client loaded successfully (200) — or, in production-like
    // builds, it simply isn't requested (length === 0 is also acceptable)
    if (viteClientResponses.length > 0) {
      expect(viteClientResponses.every((s) => s === 200)).toBe(true);
    }
  });

  test('[P2] should have a non-empty <title> set in index.html', async ({ page }) => {
    // GIVEN: A production-quality Vite app sets a meaningful <title>
    // WHEN: The shell loads
    await page.goto('/');
    const title = await page.title();

    // THEN: The page title is set (not blank and not the literal default placeholder)
    expect(title).not.toBe('');
    expect(title.toLowerCase()).not.toContain('vite + react'); // default template removed
  });

  test('[P2] should expose a single React root mount point (#root) — no duplicates', async ({ page }) => {
    // GIVEN: index.html has exactly one #root container
    // WHEN: The DOM is inspected after mount
    await page.goto('/');

    // THEN: Exactly one element with id "root" — no SSR/CSR duplication
    const count = await page.locator('#root').count();
    expect(count).toBe(1);
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// [P1] TailwindCSS v4 — visual smoke test
// ─────────────────────────────────────────────────────────────────────────────

test.describe('[E2E] TailwindCSS v4 wiring', () => {
  test('[P1] should apply Tailwind utility classes (bg-white from app-root)', async ({ page }) => {
    // GIVEN: __root.tsx applies className="min-h-screen bg-white text-slate-900"
    // WHEN: The shell renders
    await page.goto('/');

    // THEN: computed background-color matches Tailwind's bg-white (white / rgb(255,255,255))
    const appRoot = page.locator('[data-testid="app-root"]');
    await expect(appRoot).toBeVisible();
    const bgColor = await appRoot.evaluate((el) => window.getComputedStyle(el).backgroundColor);
    // Tailwind's bg-white can render as either rgb(255, 255, 255) or rgba(255, 255, 255, 1)
    expect(bgColor).toMatch(/rgba?\(\s*255,\s*255,\s*255/);
  });

  test('[P1] should apply min-h-screen (height === viewport height)', async ({ page }) => {
    // GIVEN: app-root has Tailwind min-h-screen
    // WHEN: The shell renders
    await page.goto('/');
    const viewport = page.viewportSize();
    expect(viewport).toBeTruthy();

    const appRoot = page.locator('[data-testid="app-root"]');
    const height = await appRoot.evaluate((el) => el.getBoundingClientRect().height);

    // THEN: Element occupies at least the viewport height (Tailwind min-h-screen)
    expect(height).toBeGreaterThanOrEqual(viewport!.height - 1);
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// [P1] Console hygiene — strict mode dev quality
// ─────────────────────────────────────────────────────────────────────────────

test.describe('[E2E] Console hygiene', () => {
  test('[P1] should not emit any errors from QueryClientProvider or RouterProvider setup', async ({ page }) => {
    // GIVEN: main.tsx wraps RouterProvider inside QueryProvider — both must initialize cleanly
    const providerErrors: string[] = [];
    page.on('console', (msg) => {
      if (msg.type() === 'error') {
        const text = msg.text();
        if (/QueryClient|useQuery|Router|TanStack/i.test(text)) {
          providerErrors.push(text);
        }
      }
    });

    // WHEN: The page loads
    await page.goto('/', { waitUntil: 'networkidle' });

    // THEN: No provider-related errors
    expect(providerErrors, `Provider errors detected:\n${providerErrors.join('\n')}`).toHaveLength(0);
  });

  test('[P2] should not log any 404 / failed-resource errors on initial load', async ({ page }) => {
    // GIVEN: All static assets referenced from index.html must resolve
    const failedRequests: string[] = [];
    page.on('response', (response) => {
      if (response.status() >= 400 && response.status() < 500) {
        // Filter out the well-known cases not relevant to story 1.1 init
        const url = response.url();
        if (!url.includes('favicon')) {
          failedRequests.push(`${response.status()} ${url}`);
        }
      }
    });

    // WHEN: The page loads completely
    await page.goto('/', { waitUntil: 'networkidle' });

    // THEN: No 4xx failures on first-party assets
    expect(failedRequests, `Failed asset requests:\n${failedRequests.join('\n')}`).toHaveLength(0);
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// [P2] Cross-origin call from browser context — proves CORS works end-to-end
// ─────────────────────────────────────────────────────────────────────────────

test.describe('[E2E] Frontend → Backend cross-origin fetch', () => {
  test('[P0] should successfully fetch the OpenAPI document from the browser without CORS errors', async ({ page }) => {
    // GIVEN: Both servers up; CORS allows http://localhost:5173
    // WHEN: Browser executes fetch() against the backend
    await page.goto('/');

    const fetchResult = await page.evaluate(async (apiUrl) => {
      try {
        const res = await fetch(`${apiUrl}/openapi/v1.json`);
        return { ok: res.ok, status: res.status, type: res.type };
      } catch (err) {
        return { ok: false, status: 0, error: (err as Error).message };
      }
    }, API_BASE_URL);

    // THEN: fetch succeeded with status 200 (no CORS rejection — would surface as TypeError)
    expect(fetchResult.ok).toBe(true);
    expect(fetchResult.status).toBe(200);
  });

  test('[P1] should fetch the OpenAPI document as parseable JSON from the browser', async ({ page }) => {
    // GIVEN: The frontend may use this document for codegen / type tooling
    // WHEN: Browser fetches and parses the body
    await page.goto('/');

    const result = await page.evaluate(async (apiUrl) => {
      const res = await fetch(`${apiUrl}/openapi/v1.json`);
      const body = await res.json();
      return { hasOpenApi: typeof body.openapi === 'string', title: body?.info?.title ?? null };
    }, API_BASE_URL);

    // THEN: Body has the OpenAPI version + the expected API title
    expect(result.hasOpenApi).toBe(true);
    expect(result.title).toContain('SiesaAgents.API');
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// [P2] Unknown frontend routes — TanStack Router default behavior
// ─────────────────────────────────────────────────────────────────────────────

test.describe('[E2E] Unknown frontend routes', () => {
  test('[P2] should serve the SPA shell (HTTP 200) for any deep URL — SPA fallback contract', async ({ page }) => {
    // GIVEN: Vite dev server serves index.html for any unmatched path (SPA fallback)
    // WHEN: A deep, never-defined URL is visited
    const response = await page.goto('/some/deep/never-defined/path');

    // THEN: The shell still loads (200) — TanStack Router renders not-found UI client-side.
    //       Story 1.2 introduces an explicit 404 view; here we only verify the shell loads.
    expect(response?.status()).toBe(200);
    await expect(page.locator('[data-testid="app-root"]')).toBeVisible();
  });
});
