/**
 * Story 1.2: Frontend Navigation Shell
 * Epic 1: Project Foundation & Application Shell
 *
 * Automation Expansion — Edge Cases & Boundary Conditions (Component level)
 * Generated by *automate after the ATDD suite (AppNavigation.test.tsx) went GREEN.
 * Focus: scenarios NOT covered by the original ATDD suite — default active-item
 * state, mobile (NavigationBar) navigation, idempotent re-selection, and item-count
 * regression guarding.
 *
 * Acceptance Criteria covered:
 *   AC2 — NavigationBar item click triggers router navigation (ATDD only asserted this for the rail)
 *   AC6 — Active nav item reflects the current route (ATDD only asserted the /contactos case)
 */

import { describe, test, expect } from 'vitest'
import { render, screen, within, fireEvent, waitFor } from '@testing-library/react'
import {
  createRootRoute,
  createRoute,
  createRouter,
  createMemoryHistory,
  RouterProvider,
} from '@tanstack/react-router'
import { AppNavigation } from './AppNavigation'

function renderAppNavigationAt(initialPath: string) {
  const rootRoute = createRootRoute({
    component: () => <AppNavigation />,
  })
  const clientesRoute = createRoute({
    getParentRoute: () => rootRoute,
    path: '/clientes',
    component: () => <div>Clientes view</div>,
  })
  const contactosRoute = createRoute({
    getParentRoute: () => rootRoute,
    path: '/contactos',
    component: () => <div>Contactos view</div>,
  })
  const routeTree = rootRoute.addChildren([clientesRoute, contactosRoute])

  const router = createRouter({
    routeTree,
    history: createMemoryHistory({ initialEntries: [initialPath] }),
  })

  render(<RouterProvider router={router} />)
  return router
}

describe('AC6 — Default active item reflects the landing route (/clientes)', () => {
  test('[P1] marks the Clientes rail item as active and Contactos as inactive on initial load', async () => {
    // GIVEN: the app is rendered directly at /clientes (the default landing route)
    renderAppNavigationAt('/clientes')
    const railContainer = await screen.findByTestId('nav-rail-container')

    // WHEN: inspecting the rail items
    const clientesItem = within(railContainer).getByRole('button', { name: /clientes/i })
    const contactosItem = within(railContainer).getByRole('button', { name: /contactos/i })

    // THEN: only Clientes is marked as the current page
    expect(clientesItem).toHaveAttribute('aria-current', 'page')
    expect(contactosItem).not.toHaveAttribute('aria-current', 'page')
  })

  test('[P1] marks the Clientes bar item as active and Contactos as inactive on initial load', async () => {
    // GIVEN: the app is rendered directly at /clientes (the default landing route)
    renderAppNavigationAt('/clientes')
    const barContainer = await screen.findByTestId('nav-bar-container')

    // WHEN: inspecting the bar items
    const clientesButton = within(barContainer).getByRole('button', { name: /clientes/i })
    const contactosButton = within(barContainer).getByRole('button', { name: /contactos/i })

    // THEN: only Clientes is marked as the current page
    expect(clientesButton).toHaveAttribute('aria-current', 'page')
    expect(contactosButton).not.toHaveAttribute('aria-current', 'page')
  })
})

describe('AC2 — NavigationBar (mobile) item click triggers router navigation', () => {
  test('[P1] clicking the Contactos bar item navigates via the router with no window.location call', async () => {
    // GIVEN: the app is on /clientes and the mobile bar is rendered
    const router = renderAppNavigationAt('/clientes')
    const barContainer = await screen.findByTestId('nav-bar-container')

    // WHEN: the user taps the "Contactos" bar item
    fireEvent.click(within(barContainer).getByRole('button', { name: /contactos/i }))

    // THEN: the router's location updates to /contactos (client-side navigation)
    await waitFor(() => expect(router.state.location.pathname).toBe('/contactos'))
  })
})

describe('AC1/AC6 — Re-selecting the already-active item is a safe no-op', () => {
  test('[P2] clicking the currently active Clientes rail item keeps the route unchanged', async () => {
    // GIVEN: the app is already on /clientes
    const router = renderAppNavigationAt('/clientes')
    const railContainer = await screen.findByTestId('nav-rail-container')

    // WHEN: the user clicks the already-selected "Clientes" item again
    fireEvent.click(within(railContainer).getByRole('button', { name: /clientes/i }))

    // THEN: the route remains /clientes with no error thrown
    await waitFor(() => expect(router.state.location.pathname).toBe('/clientes'))
  })
})

describe('Regression guard — exactly two nav items per container', () => {
  test('[P2] renders exactly 2 buttons in the rail container and 2 in the bar container', async () => {
    // GIVEN: the app shell is rendered
    renderAppNavigationAt('/clientes')
    const railContainer = await screen.findByTestId('nav-rail-container')
    const barContainer = await screen.findByTestId('nav-bar-container')

    // WHEN: counting rendered nav item buttons
    const railButtons = within(railContainer).getAllByRole('button')
    const barButtons = within(barContainer).getAllByRole('button')

    // THEN: exactly Clientes + Contactos are present in each container (no orphan/duplicate items)
    expect(railButtons).toHaveLength(2)
    expect(barButtons).toHaveLength(2)
  })
})
