/**
 * Story 2.1 — Client List & Search (Epic 2)
 *
 * ATDD Component Tests — RED Phase (Shared component)
 * Generated by testarch-atdd. These tests are intentionally FAILING until
 * `ClientListItem.tsx` is created per AC-2.1.h (Task 6).
 *
 * Covers AC-2.1.a, AC-2.1.h, AC-2.1.i:
 *   - Renders as a <button type="button"> (keyboard-accessible, Enter/Space)
 *   - Shows nombre (primary) and nit (secondary) text
 *   - aria-label "{nombre} — NIT {nit}"
 *   - aria-current="true" when isSelected, absent otherwise
 *   - onClick fires exactly once when clicked
 *   - Visible focus ring (focus-visible:ring-2) in the className
 *
 * Expected RED failure reason:
 *   "Cannot find module './ClientListItem'" — module does not yet exist.
 */

import { describe, it, expect, vi, afterEach } from 'vitest'
import { cleanup, render, screen, fireEvent } from '@testing-library/react'
import { ClientListItem } from './ClientListItem'
import type { Cliente } from '@/modules/crm/clientes/domain/Cliente'

const CLIENTE: Cliente = {
  id: '00000000-0000-4000-8000-000000000001',
  nombre: 'Acme S.A.',
  nit: '900123456-1',
  telefono: '+57 1 2223333',
  ciudad: 'Bogota',
  createdAt: '2026-05-30T10:00:00.000Z',
  updatedAt: '2026-05-30T10:00:00.000Z',
}

describe('ClientListItem — shared list item (AC-2.1.a / .h / .i)', () => {
  afterEach(() => cleanup())

  it('[P1] renders the nombre as visible text', () => {
    // GIVEN/WHEN
    render(<ClientListItem cliente={CLIENTE} isSelected={false} onClick={() => {}} />)

    // THEN
    expect(screen.getByText('Acme S.A.')).toBeInTheDocument()
  })

  it('[P1] renders the nit as visible text', () => {
    // GIVEN/WHEN
    render(<ClientListItem cliente={CLIENTE} isSelected={false} onClick={() => {}} />)

    // THEN
    expect(screen.getByText('900123456-1')).toBeInTheDocument()
  })

  it('[P1] renders as a button (keyboard-accessible)', () => {
    // GIVEN/WHEN
    render(<ClientListItem cliente={CLIENTE} isSelected={false} onClick={() => {}} />)

    // THEN: a real <button> is exposed (NOT a plain <div>)
    const button = screen.getByRole('button')
    expect(button.tagName).toBe('BUTTON')
  })

  it('[P1] exposes the Spanish aria-label "{nombre} — NIT {nit}"', () => {
    // GIVEN/WHEN
    render(<ClientListItem cliente={CLIENTE} isSelected={false} onClick={() => {}} />)

    // THEN
    expect(
      screen.getByRole('button', { name: 'Acme S.A. — NIT 900123456-1' }),
    ).toBeInTheDocument()
  })

  it('[P1] sets aria-current="true" when isSelected', () => {
    // GIVEN/WHEN: rendered in the selected state
    render(<ClientListItem cliente={CLIENTE} isSelected onClick={() => {}} />)

    // THEN: AT users know which item is current
    const button = screen.getByRole('button')
    expect(button).toHaveAttribute('aria-current', 'true')
  })

  it('[P1] does NOT set aria-current when not selected', () => {
    // GIVEN/WHEN: rendered in the unselected state
    render(<ClientListItem cliente={CLIENTE} isSelected={false} onClick={() => {}} />)

    // THEN: the attribute is absent (NOT "false") so AT does not announce a current item
    const button = screen.getByRole('button')
    expect(button.getAttribute('aria-current')).toBeNull()
  })

  it('[P1] fires onClick exactly once when clicked', () => {
    // GIVEN: a spy onClick handler
    const onClick = vi.fn()
    render(<ClientListItem cliente={CLIENTE} isSelected={false} onClick={onClick} />)

    // WHEN: user clicks the item
    fireEvent.click(screen.getByRole('button'))

    // THEN: handler invoked once
    expect(onClick).toHaveBeenCalledTimes(1)
  })

  it('[P2] preserves focus-visible ring tokens (WCAG 2.1 AA — AC-2.1.i)', () => {
    // GIVEN/WHEN
    render(<ClientListItem cliente={CLIENTE} isSelected={false} onClick={() => {}} />)

    // THEN: the focus-visible utility tokens are present in the className
    const button = screen.getByRole('button')
    expect(button.className).toMatch(/\bfocus-visible:ring-2\b/)
  })
})
