/**
 * Story 2.1: Client List & Search — Expanded Automation Coverage
 * Epic 2: Client Management
 *
 * Generated by TEA testarch-automate (BMad-Integrated mode)
 * Unit tests for the ClientListItem shared component.
 *
 * Covers edge cases NOT in ATDD tests:
 *   - Renders nombre and nit fields correctly
 *   - Renders long strings (truncation via CSS, text present in DOM)
 *   - Calls onClick callback with the correct client object
 *   - Does NOT call onClick when no handler is provided (no crash)
 *   - Has accessible aria-label combining nombre and nit
 *   - Applies correct data-testid attribute
 */

import { render, screen, fireEvent } from '@testing-library/react';
import { describe, it, expect, vi } from 'vitest';
import { ClientListItem } from './ClientListItem';
import type { Cliente } from '../../modules/crm/clientes/domain/Cliente';

const mockCliente: Cliente = {
  id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
  nombre: 'Empresa Alpha',
  nit: '900123456-1',
  telefono: '6014567890',
  ciudad: 'Bogotá',
  createdAt: '2026-01-01T00:00:00Z',
  updatedAt: '2026-01-01T00:00:00Z',
};

// [P1] Renders nombre and nit in the list item
describe('ClientListItem — renders nombre and nit', () => {
  it('[P1] should render the cliente nombre in the button', () => {
    // GIVEN: A cliente with nombre "Empresa Alpha"
    // WHEN: ClientListItem is rendered
    render(<ClientListItem cliente={mockCliente} />);

    // THEN: The nombre text is visible
    expect(screen.getByText('Empresa Alpha')).toBeInTheDocument();
  });

  it('[P1] should render the cliente nit in the button', () => {
    // GIVEN: A cliente with nit "900123456-1"
    // WHEN: ClientListItem is rendered
    render(<ClientListItem cliente={mockCliente} />);

    // THEN: The nit text is visible
    expect(screen.getByText('900123456-1')).toBeInTheDocument();
  });
});

// [P1] Click handler edge cases
describe('ClientListItem — onClick handler', () => {
  it('[P1] should call onClick with the cliente object when button is clicked', () => {
    // GIVEN: An onClick handler and a rendered ClientListItem
    const handleClick = vi.fn();
    render(<ClientListItem cliente={mockCliente} onClick={handleClick} />);

    // WHEN: The button is clicked
    const button = screen.getByRole('button');
    fireEvent.click(button);

    // THEN: onClick is called once with the cliente
    expect(handleClick).toHaveBeenCalledTimes(1);
    expect(handleClick).toHaveBeenCalledWith(mockCliente);
  });

  it('[P1] should NOT throw when clicked without an onClick handler', () => {
    // GIVEN: No onClick prop provided
    render(<ClientListItem cliente={mockCliente} />);

    // WHEN: The button is clicked
    const button = screen.getByRole('button');

    // THEN: No error is thrown
    expect(() => fireEvent.click(button)).not.toThrow();
  });

  it('[P2] should not call onClick more than once per click', () => {
    // GIVEN: A click handler
    const handleClick = vi.fn();
    render(<ClientListItem cliente={mockCliente} onClick={handleClick} />);

    // WHEN: Button is clicked once
    fireEvent.click(screen.getByRole('button'));

    // THEN: Handler is called exactly once
    expect(handleClick).toHaveBeenCalledTimes(1);
  });
});

// [P1] Accessibility attributes
describe('ClientListItem — accessibility', () => {
  it('[P1] should have an aria-label combining nombre and nit', () => {
    // GIVEN: A cliente with nombre and nit
    render(<ClientListItem cliente={mockCliente} />);

    // WHEN: The button is queried by aria-label
    const button = screen.getByRole('button', { name: /Empresa Alpha.*900123456-1/i });

    // THEN: The button is found (aria-label is set)
    expect(button).toBeInTheDocument();
  });

  it('[P1] should have data-testid="cliente-list-item" on the button', () => {
    // GIVEN: A rendered ClientListItem
    render(<ClientListItem cliente={mockCliente} />);

    // THEN: data-testid selector is present
    expect(screen.getByTestId('cliente-list-item')).toBeInTheDocument();
  });
});

// [P2] Long string edge cases
describe('ClientListItem — long string edge cases', () => {
  it('[P2] should render a very long nombre without crashing', () => {
    // GIVEN: A cliente with an extremely long nombre (200 chars)
    const longNombre = 'A'.repeat(200);
    const clienteWithLongNombre: Cliente = { ...mockCliente, nombre: longNombre };

    // WHEN: ClientListItem is rendered
    render(<ClientListItem cliente={clienteWithLongNombre} />);

    // THEN: The nombre text is present in the DOM (truncation via CSS, not DOM removal)
    expect(screen.getByText(longNombre)).toBeInTheDocument();
  });

  it('[P2] should render a very long nit without crashing', () => {
    // GIVEN: A cliente with an extremely long nit
    const longNit = '9'.repeat(50);
    const clienteWithLongNit: Cliente = { ...mockCliente, nit: longNit };

    // WHEN: ClientListItem is rendered
    render(<ClientListItem cliente={clienteWithLongNit} />);

    // THEN: The nit text is present in the DOM
    expect(screen.getByText(longNit)).toBeInTheDocument();
  });
});

// [P2] Special characters in nombre and nit
describe('ClientListItem — special character edge cases', () => {
  it('[P2] should render nombre with accents and special Spanish characters', () => {
    // GIVEN: A cliente with accented Spanish nombre
    const clienteEspecial: Cliente = {
      ...mockCliente,
      nombre: 'Empresa Ñoño & Cía. Ltda.',
      nit: '800-456-789/10',
    };

    // WHEN: Rendered
    render(<ClientListItem cliente={clienteEspecial} />);

    // THEN: Special chars are rendered correctly
    expect(screen.getByText('Empresa Ñoño & Cía. Ltda.')).toBeInTheDocument();
    expect(screen.getByText('800-456-789/10')).toBeInTheDocument();
  });
});
