/**
 * Story 2.1 — Client List & Search (Epic 2)
 *
 * ATDD Component Tests — RED Phase (Shared component)
 * Generated by testarch-atdd. These tests are intentionally FAILING until
 * `EmptyState.tsx` is created per AC-2.1.c (Task 6).
 *
 * Covers AC-2.1.c contract:
 *   - role="status" + aria-live="polite" (screen-reader announcement)
 *   - data-testid="empty-state" by default (overridable via prop)
 *   - Title + description rendered as text
 *   - CTA button rendered when `ctaLabel` is provided; click fires `onCtaClick`
 *   - When `ctaLabel` is omitted, NO button is rendered
 *
 * Expected RED failure reason:
 *   "Cannot find module './EmptyState'" — module does not yet exist.
 */

import { describe, it, expect, vi, afterEach } from 'vitest'
import { cleanup, render, screen, fireEvent } from '@testing-library/react'
import { EmptyState } from './EmptyState'

describe('EmptyState — shared empty-state component (AC-2.1.c)', () => {
  afterEach(() => cleanup())

  it('[P1] exposes default data-testid="empty-state"', () => {
    // GIVEN/WHEN: component rendered with minimum props
    render(<EmptyState icon={<svg data-testid="icon" />} title="Sin datos" />)

    // THEN: the canonical test id is on the root
    expect(screen.getByTestId('empty-state')).toBeInTheDocument()
  })

  it('[P1] applies role="status" and aria-live="polite" for screen readers', () => {
    // GIVEN/WHEN: component rendered
    render(<EmptyState icon={<svg />} title="Sin datos" />)

    // THEN: announced as a status region with polite live updates
    const root = screen.getByTestId('empty-state')
    expect(root).toHaveAttribute('role', 'status')
    expect(root).toHaveAttribute('aria-live', 'polite')
  })

  it('[P1] renders the title as visible text', () => {
    // GIVEN/WHEN: component rendered with a Spanish title
    render(<EmptyState icon={<svg />} title="Aún no hay clientes" />)

    // THEN: the title text is in the DOM
    expect(screen.getByText('Aún no hay clientes')).toBeInTheDocument()
  })

  it('[P1] renders the optional description when provided', () => {
    // GIVEN/WHEN: component rendered with title + description
    render(
      <EmptyState
        icon={<svg />}
        title="Aún no hay clientes"
        description="Crea el primer cliente para empezar."
      />,
    )

    // THEN: description copy is visible
    expect(screen.getByText('Crea el primer cliente para empezar.')).toBeInTheDocument()
  })

  it('[P1] renders a CTA button when ctaLabel is provided', () => {
    // GIVEN/WHEN: component rendered with ctaLabel="Nuevo cliente"
    render(
      <EmptyState
        icon={<svg />}
        title="Aún no hay clientes"
        ctaLabel="Nuevo cliente"
        onCtaClick={() => {}}
      />,
    )

    // THEN: a button with that accessible name is rendered
    expect(screen.getByRole('button', { name: /nuevo cliente/i })).toBeInTheDocument()
  })

  it('[P1] does NOT render a CTA button when ctaLabel is omitted', () => {
    // GIVEN/WHEN: component rendered without ctaLabel
    render(<EmptyState icon={<svg />} title="Sin datos" />)

    // THEN: no button is rendered at all
    expect(screen.queryByRole('button')).toBeNull()
  })

  it('[P1] fires onCtaClick exactly once when the CTA is clicked', () => {
    // GIVEN: a spy onCtaClick handler
    const onCtaClick = vi.fn()
    render(
      <EmptyState
        icon={<svg />}
        title="Aún no hay clientes"
        ctaLabel="Nuevo cliente"
        onCtaClick={onCtaClick}
      />,
    )

    // WHEN: the user clicks the CTA
    fireEvent.click(screen.getByRole('button', { name: /nuevo cliente/i }))

    // THEN: the handler is invoked exactly once
    expect(onCtaClick).toHaveBeenCalledTimes(1)
  })

  it('[P2] respects a custom data-testid override', () => {
    // GIVEN/WHEN: component rendered with explicit data-testid
    render(
      <EmptyState
        icon={<svg />}
        title="Sin datos"
        data-testid="custom-empty"
      />,
    )

    // THEN: the override is on the root, and the default id is NOT used
    expect(screen.getByTestId('custom-empty')).toBeInTheDocument()
    expect(screen.queryByTestId('empty-state')).toBeNull()
  })
})
