/**
 * Story 2.1: Client List & Search — Expanded Automation Coverage
 * Epic 2: Client Management
 *
 * Generated by TEA testarch-automate (BMad-Integrated mode)
 * Unit tests for the EmptyState shared component.
 *
 * Covers edge cases NOT in ATDD tests:
 *   - Renders title text
 *   - Renders optional description when provided
 *   - Does NOT render description element when not provided
 *   - Renders optional action slot when provided
 *   - Has correct data-testid="empty-state"
 *   - Has correct role="status" for screen readers
 */

import { render, screen } from '@testing-library/react';
import { describe, it, expect } from 'vitest';
import { EmptyState } from './EmptyState';

// [P1] Core rendering
describe('EmptyState — renders title', () => {
  it('[P1] should render the title text', () => {
    // GIVEN: An EmptyState with title
    // WHEN: Rendered
    render(<EmptyState title="No hay clientes registrados" />);

    // THEN: Title is visible
    expect(screen.getByText('No hay clientes registrados')).toBeInTheDocument();
  });

  it('[P1] should have data-testid="empty-state"', () => {
    // GIVEN: An EmptyState component
    render(<EmptyState title="No hay clientes registrados" />);

    // THEN: data-testid selector is present
    expect(screen.getByTestId('empty-state')).toBeInTheDocument();
  });

  it('[P1] should have role="status" for screen readers', () => {
    // GIVEN: An EmptyState component
    render(<EmptyState title="No hay clientes registrados" />);

    // THEN: role="status" is present for accessibility
    expect(screen.getByRole('status')).toBeInTheDocument();
  });
});

// [P1] Optional description
describe('EmptyState — optional description', () => {
  it('[P1] should render description when provided', () => {
    // GIVEN: EmptyState with both title and description
    render(
      <EmptyState
        title="No hay clientes registrados"
        description="Crear el primer cliente"
      />
    );

    // THEN: Description text is visible
    expect(screen.getByText('Crear el primer cliente')).toBeInTheDocument();
  });

  it('[P1] should NOT render description element when description is not provided', () => {
    // GIVEN: EmptyState with only a title
    render(<EmptyState title="No hay clientes registrados" />);

    // THEN: The description text is absent from the DOM
    expect(screen.queryByText('Crear el primer cliente')).not.toBeInTheDocument();
  });
});

// [P2] Optional action slot
describe('EmptyState — optional action slot', () => {
  it('[P2] should render action ReactNode when provided', () => {
    // GIVEN: EmptyState with an action button
    render(
      <EmptyState
        title="No hay clientes"
        action={<button type="button">Crear cliente</button>}
      />
    );

    // THEN: The action button is rendered
    expect(screen.getByRole('button', { name: 'Crear cliente' })).toBeInTheDocument();
  });

  it('[P2] should NOT render action container when action is not provided', () => {
    // GIVEN: EmptyState without action
    render(<EmptyState title="No hay clientes" />);

    // THEN: No button is rendered inside the EmptyState
    expect(screen.queryByRole('button')).not.toBeInTheDocument();
  });
});

// [P2] Accessibility — aria-label contains the title
describe('EmptyState — accessibility attributes', () => {
  it('[P2] should have aria-label set to the title text', () => {
    // GIVEN: EmptyState with a specific title
    render(<EmptyState title="No hay clientes registrados" />);

    // THEN: The container has aria-label matching the title
    const container = screen.getByTestId('empty-state');
    expect(container).toHaveAttribute('aria-label', 'No hay clientes registrados');
  });
});
