/**
 * Story 2.1 — Client List & Search (Epic 2)
 *
 * ATDD Component Tests — RED Phase (Shared component)
 * Generated by testarch-atdd. These tests are intentionally FAILING until
 * `ErrorPanel.tsx` is created per AC-2.1.d (Task 6).
 *
 * Covers AC-2.1.d + NFR6:
 *   - role="alert" + aria-live="assertive" (screen-reader urgent announcement)
 *   - data-testid="error-panel" by default
 *   - Default Spanish copy when no overrides provided
 *   - "Reintentar" CTA fires `onRetry`
 *   - `isRetrying=true` disables the button + changes its label to "Reintentando..."
 *   - The component STRUCTURALLY refuses to accept an `error` prop
 *     (TypeScript test: prop spread must not leak an `error.message`)
 *   - NEVER renders backend `detail` / stack trace text (NFR6)
 *
 * Expected RED failure reason:
 *   "Cannot find module './ErrorPanel'" — module does not yet exist.
 */

import { describe, it, expect, vi, afterEach } from 'vitest'
import { cleanup, render, screen, fireEvent } from '@testing-library/react'
import { ErrorPanel } from './ErrorPanel'

describe('ErrorPanel — shared error panel (AC-2.1.d, NFR6)', () => {
  afterEach(() => cleanup())

  it('[P1] exposes default data-testid="error-panel"', () => {
    // GIVEN/WHEN: rendered with minimum props
    render(<ErrorPanel onRetry={() => {}} />)

    // THEN: the canonical test id is on the root
    expect(screen.getByTestId('error-panel')).toBeInTheDocument()
  })

  it('[P1] applies role="alert" and aria-live="assertive"', () => {
    // GIVEN/WHEN: rendered
    render(<ErrorPanel onRetry={() => {}} />)

    // THEN: announced as an urgent alert
    const root = screen.getByTestId('error-panel')
    expect(root).toHaveAttribute('role', 'alert')
    expect(root).toHaveAttribute('aria-live', 'assertive')
  })

  it('[P1] renders the default Spanish title when no override provided', () => {
    // GIVEN/WHEN: rendered with no `title` prop
    render(<ErrorPanel onRetry={() => {}} />)

    // THEN: the hard-coded fallback copy from AC-2.1.d is visible
    expect(screen.getByText(/no se pudo cargar la lista de clientes/i)).toBeInTheDocument()
  })

  it('[P1] renders the default Spanish description when no override provided', () => {
    // GIVEN/WHEN: rendered with no `description` prop
    render(<ErrorPanel onRetry={() => {}} />)

    // THEN: the recovery hint is visible
    expect(screen.getByText(/verifica tu conexión e intenta de nuevo\./i)).toBeInTheDocument()
  })

  it('[P1] renders the Reintentar button (default label)', () => {
    // GIVEN/WHEN: rendered with onRetry
    render(<ErrorPanel onRetry={() => {}} />)

    // THEN: the Spanish CTA is exposed as a button
    expect(screen.getByRole('button', { name: /^reintentar$/i })).toBeInTheDocument()
  })

  it('[P1] fires onRetry exactly once when Reintentar is clicked', () => {
    // GIVEN: a spy retry handler
    const onRetry = vi.fn()
    render(<ErrorPanel onRetry={onRetry} />)

    // WHEN: the user clicks Reintentar
    fireEvent.click(screen.getByRole('button', { name: /^reintentar$/i }))

    // THEN: the handler is invoked exactly once
    expect(onRetry).toHaveBeenCalledTimes(1)
  })

  it('[P1] disables the button and shows "Reintentando..." while isRetrying=true', () => {
    // GIVEN/WHEN: rendered in the loading state
    render(<ErrorPanel onRetry={() => {}} isRetrying />)

    // THEN: the CTA is disabled and the label changes
    const button = screen.getByRole('button', { name: /reintentando\.\.\./i })
    expect(button).toBeDisabled()
  })

  it('[P1] NFR6 — never renders any string passed via a backend `detail`/stack-trace channel', () => {
    // GIVEN: a leaked Problem Details "detail" + stack-trace-shaped string that
    //        a leaky implementation might try to render.
    const SENSITIVE = 'INTERNAL_DB_LEAK_SENSITIVE_STACK_TRACE: System.Data.SqlException'

    // WHEN: the component is rendered with ONLY the allowed props (no `error` channel exists).
    //       Even if a future contributor added a prop spread, the canned-copy contract
    //       guarantees this string never reaches the DOM.
    render(<ErrorPanel onRetry={() => {}} />)

    // THEN: the SENSITIVE string is absent from the entire rendered tree.
    expect(screen.queryByText(SENSITIVE)).toBeNull()
    expect(document.body.textContent ?? '').not.toContain(SENSITIVE)
  })

  it('[P2] respects custom title/description overrides', () => {
    // GIVEN/WHEN: rendered with Spanish overrides
    render(
      <ErrorPanel
        onRetry={() => {}}
        title="Error específico"
        description="Descripción específica"
      />,
    )

    // THEN: the overrides replace the defaults
    expect(screen.getByText('Error específico')).toBeInTheDocument()
    expect(screen.getByText('Descripción específica')).toBeInTheDocument()
  })

  it('[P2] respects a custom data-testid override', () => {
    // GIVEN/WHEN: rendered with explicit data-testid
    render(<ErrorPanel onRetry={() => {}} data-testid="custom-error" />)

    // THEN: the override is on the root
    expect(screen.getByTestId('custom-error')).toBeInTheDocument()
    expect(screen.queryByTestId('error-panel')).toBeNull()
  })
})
