/**
 * Story 2.1: Client List & Search — Expanded Automation Coverage
 * Epic 2: Client Management
 *
 * Generated by TEA testarch-automate (BMad-Integrated mode)
 * Unit tests for the ErrorPanel shared component.
 *
 * Covers edge cases NOT in ATDD tests:
 *   - Renders default message when no message prop is provided
 *   - Renders custom message when provided
 *   - Shows "Reintentar" button only when onRetry is provided
 *   - Calls onRetry when "Reintentar" is clicked
 *   - Does NOT render button when onRetry is absent
 *   - Has correct data-testid="error-panel"
 *   - Has role="alert" for accessibility
 */

import { render, screen, fireEvent } from '@testing-library/react';
import { describe, it, expect, vi } from 'vitest';
import { ErrorPanel } from './ErrorPanel';

// [P1] Core rendering
describe('ErrorPanel — core rendering', () => {
  it('[P1] should render the default error message when no message prop is provided', () => {
    // GIVEN: ErrorPanel with no message
    render(<ErrorPanel />);

    // THEN: The default Spanish error message is shown
    expect(screen.getByText('Error al cargar los clientes')).toBeInTheDocument();
  });

  it('[P1] should render a custom message when provided', () => {
    // GIVEN: ErrorPanel with a custom message
    render(<ErrorPanel message="Error al obtener los datos" />);

    // THEN: The custom message is shown
    expect(screen.getByText('Error al obtener los datos')).toBeInTheDocument();
  });

  it('[P1] should have data-testid="error-panel"', () => {
    // GIVEN: An ErrorPanel component
    render(<ErrorPanel />);

    // THEN: data-testid is present for E2E selectors
    expect(screen.getByTestId('error-panel')).toBeInTheDocument();
  });

  it('[P1] should have role="alert" for screen reader accessibility', () => {
    // GIVEN: An ErrorPanel component
    render(<ErrorPanel />);

    // THEN: role="alert" announces the error to screen readers immediately
    expect(screen.getByRole('alert')).toBeInTheDocument();
  });
});

// [P1] Retry button presence
describe('ErrorPanel — Reintentar button presence', () => {
  it('[P1] should render a "Reintentar" button when onRetry is provided', () => {
    // GIVEN: ErrorPanel with an onRetry handler
    render(<ErrorPanel onRetry={() => {}} />);

    // THEN: The button with Spanish "Reintentar" label is present
    expect(screen.getByRole('button', { name: 'Reintentar' })).toBeInTheDocument();
  });

  it('[P1] should NOT render a button when onRetry is not provided', () => {
    // GIVEN: ErrorPanel without onRetry
    render(<ErrorPanel />);

    // THEN: No button is rendered (nothing to retry)
    expect(screen.queryByRole('button')).not.toBeInTheDocument();
  });
});

// [P1] Retry handler invocation
describe('ErrorPanel — onRetry callback', () => {
  it('[P1] should call onRetry when "Reintentar" is clicked', () => {
    // GIVEN: An onRetry spy and a rendered ErrorPanel
    const handleRetry = vi.fn();
    render(<ErrorPanel onRetry={handleRetry} />);

    // WHEN: The "Reintentar" button is clicked
    fireEvent.click(screen.getByRole('button', { name: 'Reintentar' }));

    // THEN: The handler is called once
    expect(handleRetry).toHaveBeenCalledTimes(1);
  });

  it('[P2] should call onRetry exactly once per click (no double-firing)', () => {
    // GIVEN: An onRetry spy
    const handleRetry = vi.fn();
    render(<ErrorPanel onRetry={handleRetry} />);

    // WHEN: The button is clicked once
    fireEvent.click(screen.getByRole('button', { name: 'Reintentar' }));

    // THEN: The handler is called exactly once
    expect(handleRetry).toHaveBeenCalledTimes(1);
  });

  it('[P2] should call onRetry multiple times when button is clicked multiple times', () => {
    // GIVEN: An onRetry spy
    const handleRetry = vi.fn();
    render(<ErrorPanel onRetry={handleRetry} />);

    // WHEN: The button is clicked 3 times
    const button = screen.getByRole('button', { name: 'Reintentar' });
    fireEvent.click(button);
    fireEvent.click(button);
    fireEvent.click(button);

    // THEN: The handler is called 3 times
    expect(handleRetry).toHaveBeenCalledTimes(3);
  });
});

// [P2] Message styling edge cases
describe('ErrorPanel — message rendering edge cases', () => {
  it('[P2] should render an empty string message without crashing', () => {
    // GIVEN: ErrorPanel with an empty string message
    // This tests the graceful fallback — empty string triggers default
    render(<ErrorPanel message="" />);

    // THEN: No crash occurs (component renders)
    expect(screen.getByTestId('error-panel')).toBeInTheDocument();
  });
});
