/**
 * Story 1.2 — Frontend Navigation Shell
 * Epic 1: Project Foundation & Application Shell
 *
 * Component tests for NotFoundView (Spanish 404 view).
 *
 * Generated by testarch-automate (BMad-Integrated Mode) — expands ATDD coverage
 * with isolated tests for the NotFoundView outside the AppShell composition.
 *
 * Covers AC #5 / TC-E1-P1-04 at the component level (isolated):
 *   - Spanish heading "Página no encontrada"
 *   - Recovery link "Ir a Clientes" wired to /clientes via TanStack Router Link
 *   - data-testid="not-found-view" exposed for E2E selectors
 *   - Brand primary styling applied (focus-visible ring tokens preserved for WCAG)
 *
 * The integration test (NotFoundView rendered INSIDE AppShell via the root
 * notFoundComponent) is already covered by AppShell.test.tsx — this file tests
 * the component in isolation to catch regressions in the standalone Spanish
 * copy contract and the Link target.
 */

import { describe, it, expect, afterEach } from 'vitest'
import { cleanup, render, screen } from '@testing-library/react'
import {
  RouterProvider,
  createMemoryHistory,
  createRootRoute,
  createRoute,
  createRouter,
  Outlet,
} from '@tanstack/react-router'

import { NotFoundView } from './NotFoundView'

/**
 * Mount the view inside a real TanStack Router context so the `Link` component
 * resolves its target. Without a router context, `Link` throws.
 */
function buildRouterAroundView(initialPath: string) {
  const rootRoute = createRootRoute({
    component: () => <Outlet />,
  })

  const fourOhFourRoute = createRoute({
    getParentRoute: () => rootRoute,
    path: '/404',
    component: NotFoundView,
  })

  const clientesRoute = createRoute({
    getParentRoute: () => rootRoute,
    path: '/clientes',
    component: () => <div data-testid="clientes-view">Clientes</div>,
  })

  return createRouter({
    routeTree: rootRoute.addChildren([fourOhFourRoute, clientesRoute]),
    history: createMemoryHistory({ initialEntries: [initialPath] }),
  })
}

describe('NotFoundView — Spanish 404 view (Story 1.2, AC #5)', () => {
  afterEach(() => {
    cleanup()
  })

  it('[P1] renders the Spanish heading "Página no encontrada"', async () => {
    // GIVEN: the view is rendered in isolation
    const router = buildRouterAroundView('/404')
    render(<RouterProvider router={router} />)

    // THEN: the Spanish heading is visible to screen readers
    const heading = await screen.findByRole('heading', {
      level: 1,
      name: /página no encontrada/i,
    })
    expect(heading).toBeInTheDocument()
  })

  it('[P1] exposes data-testid="not-found-view" for E2E selectors', async () => {
    // GIVEN: the view is rendered
    const router = buildRouterAroundView('/404')
    render(<RouterProvider router={router} />)

    // THEN: the test id is present on the root section
    const section = await screen.findByTestId('not-found-view')
    expect(section).toBeInTheDocument()
  })

  it('[P1] renders the recovery link with the Spanish label "Ir a Clientes"', async () => {
    // GIVEN: the view is rendered
    const router = buildRouterAroundView('/404')
    render(<RouterProvider router={router} />)

    // THEN: a link (NOT a button) named "Ir a Clientes" is exposed
    const link = await screen.findByRole('link', { name: /ir a clientes/i })
    expect(link).toBeInTheDocument()
  })

  it('[P1] the recovery link targets /clientes (href attribute)', async () => {
    // GIVEN: the view is rendered
    const router = buildRouterAroundView('/404')
    render(<RouterProvider router={router} />)

    // THEN: the link href resolves to /clientes (TanStack Router Link renders <a href="/clientes">)
    const link = await screen.findByRole('link', { name: /ir a clientes/i })
    expect(link.getAttribute('href')).toBe('/clientes')
  })

  it('[P2] renders the supplementary Spanish copy "La ruta solicitada no existe."', async () => {
    // GIVEN: the view is rendered
    const router = buildRouterAroundView('/404')
    render(<RouterProvider router={router} />)

    // THEN: the secondary copy line is visible (await async router mount)
    expect(await screen.findByText(/la ruta solicitada no existe\./i)).toBeInTheDocument()
  })

  it('[P2] recovery link preserves focus-visible styling tokens (WCAG 2.1 AA — AC #8)', async () => {
    // GIVEN: the view is rendered
    const router = buildRouterAroundView('/404')
    render(<RouterProvider router={router} />)

    // THEN: the link className contains the focus-visible ring tokens (no removal of focus outlines)
    const link = await screen.findByRole('link', { name: /ir a clientes/i })
    expect(link.className).toMatch(/\bfocus-visible:ring-2\b/)
    expect(link.className).toMatch(/\bfocus-visible:ring-brand-primary\b/)
  })

  it('[P2] recovery link uses brand-primary background (visual contract)', async () => {
    // GIVEN: the view is rendered
    const router = buildRouterAroundView('/404')
    render(<RouterProvider router={router} />)

    // THEN: the brand background utility is present in the link className
    const link = await screen.findByRole('link', { name: /ir a clientes/i })
    expect(link.className).toMatch(/\bbg-brand-primary\b/)
  })
})
