/**
 * Story 2.1 — Client List & Search (Epic 2)
 *
 * ATDD E2E Tests — RED Phase (Playwright)
 * Generated by testarch-atdd.
 *
 * Covers the user-journey acceptance criteria that ONLY make sense at the
 * browser level (real layout, real keyboard, real focus):
 *   - AC-2.1.a — Split-panel layout, 280 px left list at lg viewport
 *   - AC-2.1.c — EmptyState appears when API returns []
 *   - AC-2.1.d — ErrorPanel + Reintentar appears on 500 (NFR6)
 *   - AC-2.1.b — Real-time client-side filter (no extra requests during typing)
 *   - AC-2.1.i — Keyboard reach: Tab moves focus to the search input, then list
 *
 * Network-first pattern (CRITICAL):
 *   - All `page.route(...)` interceptors are installed BEFORE `page.goto()`
 *     so the SPA's TanStack Query fetch hits the stub on first paint.
 *
 * Selector discipline:
 *   - Uses `data-testid` for the panel root, EmptyState, ErrorPanel — never
 *     class-name matching (per test-quality.md "selector-resilience").
 *
 * Expected RED outcome:
 *   The /clientes route currently renders the placeholder (Story 1.2) — the
 *   new data-testids and split-panel layout do not yet exist, so every test
 *   in this file will time out waiting for them.
 */

import { test, expect } from '@playwright/test'

const API_GET_CLIENTES = '**/api/v1/clientes**'

// ─── helpers ────────────────────────────────────────────────────────────────

const THREE_CLIENTES = [
  {
    id: '00000000-0000-4000-8000-000000000001',
    nombre: 'Acme S.A.',
    nit: '900123456-1',
    telefono: '+57 1 2223333',
    ciudad: 'Bogota',
    createdAt: '2026-05-30T10:00:00.000Z',
    updatedAt: '2026-05-30T10:00:00.000Z',
  },
  {
    id: '00000000-0000-4000-8000-000000000002',
    nombre: 'Beta Corp',
    nit: '800000000-2',
    telefono: '+57 4 5556666',
    ciudad: 'Medellin',
    createdAt: '2026-05-29T10:00:00.000Z',
    updatedAt: '2026-05-29T10:00:00.000Z',
  },
  {
    id: '00000000-0000-4000-8000-000000000003',
    nombre: 'José Pérez',
    nit: '700111222-3',
    telefono: '+57 2 7778888',
    ciudad: 'Cali',
    createdAt: '2026-05-28T10:00:00.000Z',
    updatedAt: '2026-05-28T10:00:00.000Z',
  },
]

// ─── tests ──────────────────────────────────────────────────────────────────

test.describe('Story 2.1 — Client List & Search', () => {
  test.use({ viewport: { width: 1280, height: 800 } })

  test('[P1] AC-2.1.a — list panel renders 280 px wide on lg viewport', async ({ page }) => {
    // GIVEN: backend returns 3 clientes (intercept BEFORE goto)
    await page.route(API_GET_CLIENTES, (route) =>
      route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(THREE_CLIENTES),
      }),
    )

    // WHEN: the user navigates to /clientes
    await page.goto('/clientes')

    // THEN: the aside container is exactly 280 px wide
    const panel = page.getByRole('complementary', { name: /lista de clientes/i })
    await expect(panel).toBeVisible()
    const box = await panel.boundingBox()
    expect(box).not.toBeNull()
    expect(box!.width).toBe(280)
  })

  test('[P1] AC-2.1.a — detail placeholder appears on lg viewport', async ({ page }) => {
    // GIVEN
    await page.route(API_GET_CLIENTES, (route) =>
      route.fulfill({ status: 200, contentType: 'application/json', body: '[]' }),
    )

    // WHEN
    await page.goto('/clientes')

    // THEN: the detail placeholder section is visible
    await expect(page.getByTestId('cliente-detail-placeholder')).toBeVisible()
    await expect(page.getByTestId('cliente-detail-placeholder')).toContainText(
      /selecciona un cliente para ver el detalle/i,
    )
  })

  test('[P1] AC-2.1.c — EmptyState renders when API returns []', async ({ page }) => {
    // GIVEN: backend returns an empty list (network-first intercept)
    await page.route(API_GET_CLIENTES, (route) =>
      route.fulfill({ status: 200, contentType: 'application/json', body: '[]' }),
    )

    // WHEN
    await page.goto('/clientes')

    // THEN: the EmptyState is visible with Spanish copy + Nuevo cliente CTA
    const empty = page.getByTestId('empty-state')
    await expect(empty).toBeVisible()
    await expect(empty).toContainText(/aún no hay clientes/i)
    await expect(empty.getByRole('button', { name: /nuevo cliente/i })).toBeVisible()
  })

  test('[P1] AC-2.1.d — ErrorPanel renders on 500 + does NOT leak Problem Details', async ({
    page,
  }) => {
    // GIVEN: backend returns 500 + Problem Details with a sensitive marker
    const SENSITIVE = 'INTERNAL_DB_LEAK_SENSITIVE_STACK_TRACE'
    await page.route(API_GET_CLIENTES, (route) =>
      route.fulfill({
        status: 500,
        contentType: 'application/problem+json',
        body: JSON.stringify({
          type: 'about:blank',
          title: 'Internal Server Error',
          status: 500,
          detail: SENSITIVE,
          instance: '/api/v1/clientes',
        }),
      }),
    )

    // WHEN
    await page.goto('/clientes')

    // THEN: the ErrorPanel surfaces with the canned Spanish copy
    const panel = page.getByTestId('error-panel')
    await expect(panel).toBeVisible()
    await expect(panel).toContainText(/no se pudo cargar la lista de clientes/i)
    await expect(panel.getByRole('button', { name: /^reintentar$/i })).toBeVisible()

    // AND: NFR6 — the sensitive marker does NOT leak into the DOM
    const body = await page.locator('body').textContent()
    expect(body ?? '').not.toContain(SENSITIVE)
  })

  test('[P1] AC-2.1.b — typing in the search box does NOT fire additional API requests', async ({
    page,
  }) => {
    // GIVEN: count GETs to /api/v1/clientes — the initial fetch is fine, typing is not.
    let getCount = 0
    await page.route(API_GET_CLIENTES, (route) => {
      getCount += 1
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(THREE_CLIENTES),
      })
    })

    // WHEN: navigate, wait for the list, then type into the search box
    await page.goto('/clientes')
    await expect(page.getByText('Acme S.A.')).toBeVisible()
    const initial = getCount

    const search = page.getByRole('searchbox', { name: /buscar cliente/i })
    await search.fill('ACM')

    // THEN: typing must NOT trigger additional GETs (search is 100% client-side)
    await expect(page.getByText('Acme S.A.')).toBeVisible()
    await expect(page.getByText('Beta Corp')).toBeHidden()
    expect(getCount).toBe(initial)
  })

  test('[P1] AC-2.1.i — search input is keyboard-reachable via Tab and exposes Spanish aria-label', async ({
    page,
  }) => {
    // GIVEN
    await page.route(API_GET_CLIENTES, (route) =>
      route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(THREE_CLIENTES),
      }),
    )

    // WHEN: navigate and start tabbing from the document root
    await page.goto('/clientes')
    const search = page.getByRole('searchbox', { name: /buscar cliente/i })
    await expect(search).toBeVisible()
    await search.focus()

    // THEN: the input has the Spanish aria-label AND can receive focus
    await expect(search).toBeFocused()
    expect(await search.getAttribute('aria-label')).toMatch(/buscar cliente/i)
  })
})
